/**
 * Generates `lib/bugReport/privacy.ts`, the privacy classification of every public column, RPC, and
 * edge-function wrapper (bug reporter spec §4.3, package 2).
 *
 *   npx tsx scripts/bugReport/generatePrivacyDraft.ts            # add entries for new keys, keep the rest
 *   npx tsx scripts/bugReport/generatePrivacyDraft.ts --fresh    # rebuild every entry from the rules
 *   npx tsx scripts/bugReport/generatePrivacyDraft.ts --check    # exit 1 if privacy.ts would change
 *
 * Without `--fresh`, entries already in privacy.ts (including hand edits and their comments) are kept
 * as they are, entries for keys that no longer exist are dropped, and new keys get a draft entry from
 * `privacyOverrides.ts` if it has one, otherwise from the column heuristics. Every new entry carries a
 * `// DRAFT` comment so the reviewer can find it; see `lib/bugReport/PRIVACY_REVIEW.md`.
 */
/* eslint-disable no-console -- CLI script */
import fs from "fs";
import path from "path";
import ts from "typescript";
import { format, resolveConfig } from "prettier";
import type { JsonPathMap, PiiKind, RpcClassification } from "../../lib/bugReport/privacyTypes";
import { isPiiKind, isTableRef, parseJsonPath } from "../../lib/bugReport/privacyTypes";
import { classifyColumn, type Classified } from "./columnHeuristics";
import {
  COLUMN_OVERRIDES,
  EDGE_FUNCTION_OVERRIDES,
  RPC_OVERRIDES,
  type ColumnOverride,
  type Override
} from "./privacyOverrides";
import { readEdgeFunctionWrappers, readSchema, type FunctionOverload, type SchemaInfo } from "./schemaReader";

const ROOT = path.resolve(__dirname, "../..");
export const PRIVACY_PATH = path.join(ROOT, "lib/bugReport/privacy.ts");
const TYPES_PATH = path.join(ROOT, "utils/supabase/SupabaseTypes.d.ts");
const EDGE_FUNCTIONS_PATH = path.join(ROOT, "lib/edgeFunctions.ts");

type Entry = { key: string; value: string; comments: string[] };
type Section = "COLUMNS" | "RPCS" | "EDGE_FUNCTIONS";

const HEADER = `/**
 * Privacy classification for the bug reporter's taint set (spec §4.3).
 *
 * DRAFT PENDING HUMAN APPROVAL (HU6). Generated by \`scripts/bugReport/generatePrivacyDraft.ts\` from
 * column-name heuristics, \`docs/operations/data-retention.md\` §"PII / grades", the SQL of each RPC,
 * and the response types of \`lib/edgeFunctions.ts\`. Entries marked \`// UNCERTAIN\` are guesses the
 * reviewer should check; \`lib/bugReport/PRIVACY_REVIEW.md\` explains the rules and what to look at.
 *
 * Edit entries here by hand. Rerun the generator after a schema change (\`npm run client-local\` fails
 * and names the missing keys); it keeps existing entries and adds \`// DRAFT\` entries for new keys.
 *
 * - COLUMNS: every column of every table and view in the public schema, key "table.column".
 * - RPCS: a kind for scalar returns (and arrays of scalars), \`{ $table }\` for table rows, or a
 *   JSONPath map for Json and \`RETURNS TABLE\` results.
 * - EDGE_FUNCTIONS: every exported wrapper in lib/edgeFunctions.ts, JSONPath map of its response.
 *   Wrappers that only call RPCs map \`$\` to "none" here; the RPCS entries classify their results.
 *
 * JSONPath subset: \`$\`, \`.key\`, \`[*]\`. There is no default kind: \`none\` is always explicit.
 */
import type { JsonPathMap, PiiKind, RpcClassification } from "./privacyTypes";

export type { JsonPathMap, PiiKind, RpcClassification, TableRef } from "./privacyTypes";
`;

function jsonLiteral(v: RpcClassification): string {
  return JSON.stringify(v);
}

function draftComment(c: Classified | Override): string[] {
  const out: string[] = [];
  if (c.uncertain) out.push(`// UNCERTAIN: ${c.uncertain}`);
  return out;
}

// --- existing file -----------------------------------------------------------------------------

/** Converts a string or object literal (the only forms privacy.ts uses) to its value. */
function literalValue(node: ts.Expression, sf: ts.SourceFile): unknown {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
  if (ts.isObjectLiteralExpression(node)) {
    const out: Record<string, unknown> = {};
    for (const prop of node.properties) {
      if (!ts.isPropertyAssignment(prop) || !(ts.isStringLiteral(prop.name) || ts.isIdentifier(prop.name))) {
        throw new Error(`unsupported property in privacy.ts: ${prop.getText(sf)}`);
      }
      out[prop.name.text] = literalValue(prop.initializer, sf);
    }
    return out;
  }
  throw new Error(`privacy.ts values must be string or object literals, got: ${node.getText(sf)}`);
}

function readExisting(): Record<Section, Map<string, Entry>> {
  const result: Record<Section, Map<string, Entry>> = {
    COLUMNS: new Map(),
    RPCS: new Map(),
    EDGE_FUNCTIONS: new Map()
  };
  if (!fs.existsSync(PRIVACY_PATH)) return result;
  const text = fs.readFileSync(PRIVACY_PATH, "utf8");
  const sf = ts.createSourceFile("privacy.ts", text, ts.ScriptTarget.Latest, true);
  for (const stmt of sf.statements) {
    if (!ts.isVariableStatement(stmt)) continue;
    for (const decl of stmt.declarationList.declarations) {
      const name = decl.name.getText(sf) as Section;
      if (!(name in result) || !decl.initializer) continue;
      let init: ts.Expression = decl.initializer;
      while (ts.isAsExpression(init) || ts.isSatisfiesExpression(init)) init = init.expression;
      if (!ts.isObjectLiteralExpression(init)) continue;
      for (const prop of init.properties) {
        if (!ts.isPropertyAssignment(prop)) continue;
        const key =
          ts.isStringLiteral(prop.name) || ts.isIdentifier(prop.name) ? prop.name.text : prop.name.getText(sf);
        const comments = (ts.getLeadingCommentRanges(text, prop.getFullStart()) ?? []).map((r) =>
          text.slice(r.pos, r.end)
        );
        result[name].set(key, { key, value: JSON.stringify(literalValue(prop.initializer, sf)), comments });
      }
    }
  }
  return result;
}

// --- draft entries -----------------------------------------------------------------------------

function columnDrafts(schema: SchemaInfo): Entry[] {
  const entries: Entry[] = [];
  for (const [relation, info] of Object.entries(schema.relations)) {
    const fkColumns = new Set(info.relationships.flatMap((r) => r.columns));
    for (const [column, type] of Object.entries(info.columns)) {
      const key = `${relation}.${column}`;
      const c: Classified | ColumnOverride =
        COLUMN_OVERRIDES[key] ?? classifyColumn(relation, column, type, fkColumns.has(column));
      entries.push({ key, value: JSON.stringify(c.kind), comments: draftComment(c) });
    }
  }
  return entries;
}

const SCALAR_NONE = /^(undefined|boolean|number|number\[\]|boolean\[\]|unknown)$/;

/** Heuristic RPC classification from the generated return type alone. */
function rpcHeuristic(name: string, overloads: FunctionOverload[]): Override {
  const maps: Record<string, PiiKind> = {};
  const uncertain: string[] = [];
  let tableRef: string | undefined;
  let scalar: PiiKind | undefined;
  for (const o of overloads) {
    if (o.setof) {
      tableRef = o.setof.to;
      continue;
    }
    if (o.returnsColumns) {
      for (const [col, type] of Object.entries(o.returnsColumns)) {
        const c: Classified | ColumnOverride =
          COLUMN_OVERRIDES[`rpc:${name}.${col}`] ?? classifyColumn(`rpc:${name}`, col, type, false);
        const p = o.returnsArray ? `$[*].${col}` : `$.${col}`;
        maps[p] = c.kind;
        if (c.uncertain) uncertain.push(`${col}: ${c.uncertain}`);
      }
      continue;
    }
    if (SCALAR_NONE.test(o.returns)) {
      scalar = scalar ?? "none";
      continue;
    }
    scalar = "free_text";
    uncertain.push(`returns ${o.returns}; shape not reviewed, free_text taints every string in it`);
  }
  if (tableRef && Object.keys(maps).length === 0 && !scalar) return { kind: { $table: tableRef } };
  if (Object.keys(maps).length > 0) {
    if (scalar) maps["$"] = scalar;
    return { kind: maps, uncertain: uncertain.join("; ") || undefined };
  }
  return { kind: scalar ?? "free_text", uncertain: uncertain.join("; ") || undefined };
}

function rpcDrafts(schema: SchemaInfo): Entry[] {
  return Object.entries(schema.functions).map(([name, overloads]) => {
    const c = RPC_OVERRIDES[name] ?? rpcHeuristic(name, overloads);
    return { key: name, value: jsonLiteral(c.kind), comments: draftComment(c) };
  });
}

function edgeDrafts(wrappers: ReturnType<typeof readEdgeFunctionWrappers>): Entry[] {
  return Object.entries(wrappers).map(([name, target]) => {
    const override = EDGE_FUNCTION_OVERRIDES[name];
    if (override) return { key: name, value: jsonLiteral(override.kind), comments: draftComment(override) };
    if (target.edgeFunctions.length === 0) {
      return {
        key: name,
        value: jsonLiteral({ $: "none" }),
        comments: [`// calls RPCs only (${target.rpcs.join(", ")}); RPCS classifies the results`]
      };
    }
    return {
      key: name,
      value: jsonLiteral({ $: "free_text" }),
      comments: [`// UNCERTAIN: new wrapper for ${target.edgeFunctions.join(", ")}; classify its response shape`]
    };
  });
}

// --- validation and output ---------------------------------------------------------------------

function validate(section: Section, key: string, value: unknown, relations: Set<string>): string[] {
  const errors: string[] = [];
  const checkMapValue = (p: string, v: unknown) => {
    try {
      parseJsonPath(p);
    } catch (e) {
      errors.push(`${section}.${key}: ${(e as Error).message}`);
    }
    if (isTableRef(v)) {
      if (!relations.has(v.$table)) errors.push(`${section}.${key}: unknown $table ${v.$table}`);
    } else if (!isPiiKind(v)) errors.push(`${section}.${key}: ${p} has invalid kind ${JSON.stringify(v)}`);
  };
  if (section === "COLUMNS") {
    if (!isPiiKind(value)) errors.push(`COLUMNS.${key}: invalid kind ${JSON.stringify(value)}`);
  } else if (isPiiKind(value) && section === "RPCS") {
    // scalar kind
  } else if (isTableRef(value) && section === "RPCS") {
    if (!relations.has(value.$table)) errors.push(`RPCS.${key}: unknown $table ${value.$table}`);
  } else if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value as JsonPathMap);
    if (entries.length === 0) errors.push(`${section}.${key}: empty map (use { "$": "none" })`);
    for (const [p, v] of entries) checkMapValue(p, v);
  } else errors.push(`${section}.${key}: invalid classification ${JSON.stringify(value)}`);
  return errors;
}

function render(sections: Record<Section, Entry[]>): string {
  const body = (entries: Entry[]) =>
    entries
      .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
      .map((e) => [...e.comments.map((c) => `  ${c}`), `  ${JSON.stringify(e.key)}: ${e.value},`].join("\n"))
      .join("\n");
  return `${HEADER}
export const COLUMNS: Readonly<Record<string, PiiKind>> = {
${body(sections.COLUMNS)}
};

export const RPCS: Readonly<Record<string, RpcClassification>> = {
${body(sections.RPCS)}
};

export const EDGE_FUNCTIONS: Readonly<Record<string, JsonPathMap>> = {
${body(sections.EDGE_FUNCTIONS)}
};
`;
}

export async function generate(opts: {
  fresh: boolean;
}): Promise<{ text: string; added: string[]; dropped: string[] }> {
  const schema = readSchema(TYPES_PATH);
  const wrappers = readEdgeFunctionWrappers(fs.readFileSync(EDGE_FUNCTIONS_PATH, "utf8"));
  const existing = opts.fresh
    ? { COLUMNS: new Map<string, Entry>(), RPCS: new Map<string, Entry>(), EDGE_FUNCTIONS: new Map<string, Entry>() }
    : readExisting();
  const drafts: Record<Section, Entry[]> = {
    COLUMNS: columnDrafts(schema),
    RPCS: rpcDrafts(schema),
    EDGE_FUNCTIONS: edgeDrafts(wrappers)
  };
  const added: string[] = [];
  const dropped: string[] = [];
  const merged = {} as Record<Section, Entry[]>;
  const relations = new Set(Object.keys(schema.relations));
  const errors: string[] = [];
  for (const section of Object.keys(drafts) as Section[]) {
    const wanted = new Set(drafts[section].map((d) => d.key));
    merged[section] = drafts[section].map((d) => {
      const kept = existing[section].get(d.key);
      if (kept) return kept;
      if (!opts.fresh) {
        added.push(`${section}.${d.key}`);
        return { ...d, comments: [...d.comments, "// DRAFT: new entry, review and remove this comment"] };
      }
      return d;
    });
    for (const key of existing[section].keys()) if (!wanted.has(key)) dropped.push(`${section}.${key}`);
    for (const e of merged[section]) {
      errors.push(...validate(section, e.key, JSON.parse(e.value), relations));
    }
  }
  const overrideTargets = new Set(drafts.COLUMNS.map((d) => d.key));
  for (const [fn, overloads] of Object.entries(schema.functions)) {
    for (const o of overloads)
      for (const col of Object.keys(o.returnsColumns ?? {})) overrideTargets.add(`rpc:${fn}.${col}`);
  }
  for (const key of Object.keys(COLUMN_OVERRIDES)) {
    if (!overrideTargets.has(key)) errors.push(`privacyOverrides COLUMN_OVERRIDES: ${key} matches no column`);
  }
  for (const key of Object.keys(RPC_OVERRIDES)) {
    if (!schema.functions[key]) errors.push(`privacyOverrides RPC_OVERRIDES: ${key} is not a function`);
  }
  for (const key of Object.keys(EDGE_FUNCTION_OVERRIDES)) {
    if (!wrappers[key]) errors.push(`privacyOverrides EDGE_FUNCTION_OVERRIDES: ${key} is not a wrapper`);
  }
  if (errors.length > 0) throw new Error(`invalid classification entries:\n  ${errors.join("\n  ")}`);
  const prettierConfig = (await resolveConfig(PRIVACY_PATH)) ?? {};
  const text = await format(render(merged), { ...prettierConfig, filepath: PRIVACY_PATH });
  return { text, added, dropped };
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const { text, added, dropped } = await generate({ fresh: args.has("--fresh") });
  const current = fs.existsSync(PRIVACY_PATH) ? fs.readFileSync(PRIVACY_PATH, "utf8") : "";
  if (args.has("--check")) {
    if (text !== current) {
      console.error("lib/bugReport/privacy.ts is out of date; run npx tsx scripts/bugReport/generatePrivacyDraft.ts");
      process.exit(1);
    }
    return;
  }
  fs.writeFileSync(PRIVACY_PATH, text, "utf8");
  console.log(`Wrote ${path.relative(ROOT, PRIVACY_PATH)}`);
  if (added.length) console.log(`Added ${added.length} draft entries:\n  ${added.join("\n  ")}`);
  if (dropped.length)
    console.log(`Dropped ${dropped.length} entries for keys that no longer exist:\n  ${dropped.join("\n  ")}`);
}

if (require.main === module) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
