/**
 * Unit tests for isHandoutSyncPush.
 *
 * This predicate is what keeps instructor-driven handout syncs from becoming
 * student submissions on repo-only (no-autograder) assignments, where every
 * student push IS a submission. A false negative fabricates a submission the
 * student never made, so the cases below pin down both routes a sync can take.
 *
 * Run from supabase/functions:  deno test --no-check _shared/handoutSyncPush.test.ts
 */
import { assertEquals } from "jsr:@std/assert@^1";
import { isHandoutSyncPush, type HandoutSyncPushInputs } from "./handoutSyncPush.ts";

const STUDENT_SHA = "a".repeat(40);
/** Filler so a fixture sha is a plausible 40 hex characters. */
const SAFE_SUFFIX = "0".repeat(40);
// A realistic sha whose 7-character abbreviation is what syncRepositoryToHandout puts in
// the branch name, PR title and commit subject (`toSha.substring(0, 7)`). The markers below
// use "abc1234" precisely because it abbreviates THIS sha: a hex-shaped token that matches
// no known handout revision must not be treated as instructor machinery.
const HANDOUT_SHA = "abc1234" + "0".repeat(33);
const HANDOUT_SHA_7 = HANDOUT_SHA.slice(0, 7);
// A second handout revision, for the fixtures whose marker names a different one.
const OTHER_HANDOUT_SHA = "9f8e7d6" + "1".repeat(33);
// Hex-shaped but not an abbreviation of any handout sha these inputs carry.
const UNKNOWN_SHA_7 = "deadbee";

function inputs(overrides: Partial<HandoutSyncPushInputs> = {}): HandoutSyncPushInputs {
  return {
    headCommitMessage: "Finish part 1",
    // A student push: a real user, not the app's installation token.
    senderType: "User",
    afterSha: STUDENT_SHA,
    latestTemplateSha: HANDOUT_SHA,
    desiredHandoutSha: null,
    syncedHandoutSha: null,
    syncedRepoSha: null,
    ...overrides
  };
}

Deno.test("ordinary student push -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs()), false);
});

Deno.test("student push using #submit -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "done #submit" })), false);
});

// Route 1: auto-merged sync-to-* PR.
Deno.test("GitHub auto-merge commit for a sync-to-* PR -> sync", () => {
  const msg = "Merge pull request #12 from pawtograder/sync-to-abc1234\n\n[Instructor Update] Sync handout to abc1234";
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: msg })), true);
});

Deno.test("merge commit naming the sync branch without the PR title -> sync", () => {
  assertEquals(
    isHandoutSyncPush({
      ...inputs({ desiredHandoutSha: OTHER_HANDOUT_SHA }),
      headCommitMessage: "Merge pull request #3 from org/sync-to-9f8e7d6"
    }),
    true
  );
});

// The worker asks for `merge_method: "merge"`, but that is rejected on a repo where merge
// commits are disabled, so the sync PR can be landed with Squash or Rebase instead. Both
// replay the sync COMMIT's message (the PR has one commit, so GitHub uses its subject, not
// the PR title), which names neither the sync branch nor the PR-title prefix. Missing this
// shape turns an instructor's handout update into the student's newest submission.
Deno.test("squash/rebase-merged sync replaying the sync commit message -> sync", () => {
  const msg =
    "Sync handout updates to abc1234\n\nThis commit was automatically generated by an instructor to sync\nchanges from the template repository.";
  // A squash/rebase produces a NEW sha, so no handout sha matches either.
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: msg })), true);
});

// The commit-subject check requires the generated sha too, for the same reason the
// branch check does: a student commit that happens to start with the same words must
// keep its submission.
Deno.test("student commit starting with the sync subject but no sha -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "Sync handout updates to latest starter" })), false);
});

Deno.test("squashed sync commit keeping only the PR title -> sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "[Instructor Update] Sync handout to abc1234" })), true);
});

// The title matcher is sha-qualified too, so a student commit that merely opens with
// the marker keeps its submission.
Deno.test("student commit starting with [Instructor Update] but no sync title -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "[Instructor Update] said to refactor this" })), false);
});

// The title check is anchored to the start of a line, so a student mentioning the phrase
// mid-sentence keeps their submission. A bare substring test dropped it silently.
Deno.test("student message mentioning the sync PR title mid-sentence -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "fixing what the [Instructor Update] broke" })), false);
});

Deno.test("a student branch merge that is NOT a handout sync -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #4 from me/my-feature-branch" })),
    false
  );
});

// The merge-commit check matches the FULL generated branch name (`sync-to-<sha7>`),
// not a bare `sync-to-` prefix. A student branch that merely starts the same way keeps
// its submission — on a repo-only assignment that push IS the submission, so a false
// positive silently discards their work.
Deno.test("student branch merely starting with the sync prefix -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #4 from me/sync-to-my-own-thing" })),
    false
  );
});

Deno.test("student branch named sync-to-tests -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #9 from student/sync-to-tests" })),
    false
  );
});

// ...but the real thing, whose suffix is an abbreviated sha, still matches.
Deno.test("real sync branch merge (sync-to-<sha7>) -> sync", () => {
  assertEquals(
    isHandoutSyncPush(
      inputs({
        headCommitMessage: "Merge pull request #12 from org/sync-to-9f8e7d6",
        desiredHandoutSha: OTHER_HANDOUT_SHA
      })
    ),
    true
  );
});

// The hole every matcher shared: "7-40 hex characters" is a SHAPE, not an identity. A
// student commit body can contain one, and each of the three message shapes below was
// enough on its own to classify their push as instructor machinery and drop it. The marker
// must abbreviate a handout revision this row actually knows about.
Deno.test("sync commit subject naming an unknown sha -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: `Sync handout updates to ${UNKNOWN_SHA_7}` })), false);
});

Deno.test("sync PR title naming an unknown sha -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: `[Instructor Update] Sync handout to ${UNKNOWN_SHA_7}` })),
    false
  );
});

Deno.test("merge of a sync-to-<sha7> branch naming an unknown sha -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: `Merge pull request #7 from org/sync-to-${UNKNOWN_SHA_7}` })),
    false
  );
});

// Any of the four recorded revisions is a legitimate target: desired_handout_sha is the one
// in flight, synced_handout_sha the one already reached.
Deno.test("marker abbreviating synced_handout_sha -> sync", () => {
  assertEquals(
    isHandoutSyncPush(
      inputs({
        headCommitMessage: `Sync handout updates to ${OTHER_HANDOUT_SHA.slice(0, 7)}`,
        latestTemplateSha: null,
        syncedHandoutSha: OTHER_HANDOUT_SHA
      })
    ),
    true
  );
});

// The worker abbreviates to 7, but a full sha is still a valid abbreviation of itself.
Deno.test("marker carrying the full 40-character handout sha -> sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: `Sync handout updates to ${HANDOUT_SHA}` })), true);
});

// The generated subject is exactly "Sync handout updates to <sha7>" and nothing else, so a
// student sentence that merely opens that way keeps its submission even when it does quote
// a real handout sha.
Deno.test("student prose continuing past a real sha -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: `Sync handout updates to ${HANDOUT_SHA_7} broke my tests` })),
    false
  );
});

// Case-insensitive: git prints lowercase, but a stored sha is not guaranteed to be.
Deno.test("marker in a different case than the stored sha -> sync", () => {
  assertEquals(
    isHandoutSyncPush(
      inputs({
        headCommitMessage: `Sync handout updates to ${HANDOUT_SHA_7.toUpperCase()}`,
        latestTemplateSha: HANDOUT_SHA
      })
    ),
    true
  );
});

// Route 2: fork fast-forward — head becomes exactly a handout sha.
Deno.test("head equals assignments.latest_template_sha -> sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ afterSha: HANDOUT_SHA })), true);
});

Deno.test("head equals repositories.desired_handout_sha -> sync", () => {
  const desired = "c".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: desired, desiredHandoutSha: desired })), true);
});

Deno.test("head equals repositories.synced_handout_sha -> sync", () => {
  const synced = "d".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: synced, syncedHandoutSha: synced })), true);
});

// synced_repo_sha is the REPOSITORY-side result of the last sync. On a merge-based sync that commit
// contains the student's own work, so matching it classified a student's force-push back to that
// state as machinery and left a newer commit active while the head had moved. The automated
// delivery that produced it is identified by its bot sender instead.
Deno.test("student push whose head equals synced_repo_sha -> NOT a sync", () => {
  const mergeSha = "e".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: mergeSha, syncedRepoSha: mergeSha, senderType: "User" })), false);
});

Deno.test("the sync that produced synced_repo_sha is still recognised, by its sender", () => {
  const mergeSha = "e".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: mergeSha, syncedRepoSha: mergeSha, senderType: "Bot" })), true);
});

Deno.test("short-prefix overlap with a handout sha is NOT enough -> not a sync", () => {
  // Route 2 has no generated marker to anchor a prefix against, so it stays full-equality
  // only. Guards against the truncated-SHA false positives this codebase has hit before.
  assertEquals(isHandoutSyncPush(inputs({ afterSha: HANDOUT_SHA_7 })), false);
});

// Route 0: the push was made by an app. This is the only route that catches a merge-upstream
// whose result is a MERGE commit — the head is then a brand-new sha matching no handout
// revision, and synced_repo_sha is not written until the worker's API call returns, so a
// delivery in that gap fails every sha comparison.
Deno.test("push from the app's installation token -> sync", () => {
  assertEquals(
    isHandoutSyncPush(
      inputs({
        senderType: "Bot",
        // A merge commit from merge-upstream: unremarkable message, head matches no handout sha.
        headCommitMessage: "Merge branch 'main' of github.com/org/handout",
        afterSha: `beefbeef${SAFE_SUFFIX}`.slice(0, 40)
      })
    ),
    true
  );
});

// The mirror: the same unremarkable merge commit from a PERSON is student work.
Deno.test("merge commit from a user with no known sha -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(
      inputs({
        senderType: "User",
        headCommitMessage: "Merge branch 'main' of github.com/org/handout",
        afterSha: `beefbeef${SAFE_SUFFIX}`.slice(0, 40)
      })
    ),
    false
  );
});

Deno.test("null handout shas never match -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush({
      headCommitMessage: "work",
      senderType: "User",
      afterSha: STUDENT_SHA,
      latestTemplateSha: null,
      desiredHandoutSha: null,
      syncedHandoutSha: null,
      syncedRepoSha: null
    }),
    false
  );
});

Deno.test("missing afterSha and no message match -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ afterSha: null, headCommitMessage: null })), false);
});
