/**
 * Unit tests for isHandoutSyncPush.
 *
 * This predicate is what keeps instructor-driven handout syncs from becoming
 * student submissions on repo-only (no-autograder) assignments, where every
 * student push IS a submission. A false negative fabricates a submission the
 * student never made, so the cases below pin down both routes a sync can take.
 *
 * Run from supabase/functions:  deno test --no-check _shared/handoutSyncPush.test.ts
 */
import { assertEquals } from "jsr:@std/assert@^1";
import { isHandoutSyncPush, type HandoutSyncPushInputs } from "./handoutSyncPush.ts";

const STUDENT_SHA = "a".repeat(40);
const HANDOUT_SHA = "b".repeat(40);

function inputs(overrides: Partial<HandoutSyncPushInputs> = {}): HandoutSyncPushInputs {
  return {
    headCommitMessage: "Finish part 1",
    afterSha: STUDENT_SHA,
    latestTemplateSha: HANDOUT_SHA,
    desiredHandoutSha: null,
    syncedHandoutSha: null,
    syncedRepoSha: null,
    ...overrides
  };
}

Deno.test("ordinary student push -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs()), false);
});

Deno.test("student push using #submit -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "done #submit" })), false);
});

// Route 1: auto-merged sync-to-* PR.
Deno.test("GitHub auto-merge commit for a sync-to-* PR -> sync", () => {
  const msg = "Merge pull request #12 from pawtograder/sync-to-abc1234\n\n[Instructor Update] Sync handout to abc1234";
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: msg })), true);
});

Deno.test("merge commit naming the sync branch without the PR title -> sync", () => {
  assertEquals(
    isHandoutSyncPush({ ...inputs(), headCommitMessage: "Merge pull request #3 from org/sync-to-9f8e7d6" }),
    true
  );
});

// The worker asks for `merge_method: "merge"`, but that is rejected on a repo where merge
// commits are disabled, so the sync PR can be landed with Squash or Rebase instead. Both
// replay the sync COMMIT's message (the PR has one commit, so GitHub uses its subject, not
// the PR title), which names neither the sync branch nor the PR-title prefix. Missing this
// shape turns an instructor's handout update into the student's newest submission.
Deno.test("squash/rebase-merged sync replaying the sync commit message -> sync", () => {
  const msg =
    "Sync handout updates to abc1234\n\nThis commit was automatically generated by an instructor to sync\nchanges from the template repository.";
  // A squash/rebase produces a NEW sha, so no handout sha matches either.
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: msg })), true);
});

// The commit-subject check requires the generated sha too, for the same reason the
// branch check does: a student commit that happens to start with the same words must
// keep its submission.
Deno.test("student commit starting with the sync subject but no sha -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "Sync handout updates to latest starter" })), false);
});

Deno.test("squashed sync commit keeping only the PR title -> sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "[Instructor Update] Sync handout to abc1234" })), true);
});

// The title check is anchored to the start of a line, so a student mentioning the phrase
// mid-sentence keeps their submission. A bare substring test dropped it silently.
Deno.test("student message mentioning the sync PR title mid-sentence -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ headCommitMessage: "fixing what the [Instructor Update] broke" })), false);
});

Deno.test("a student branch merge that is NOT a handout sync -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #4 from me/my-feature-branch" })),
    false
  );
});

// The merge-commit check matches the FULL generated branch name (`sync-to-<sha7>`),
// not a bare `sync-to-` prefix. A student branch that merely starts the same way keeps
// its submission — on a repo-only assignment that push IS the submission, so a false
// positive silently discards their work.
Deno.test("student branch merely starting with the sync prefix -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #4 from me/sync-to-my-own-thing" })),
    false
  );
});

Deno.test("student branch named sync-to-tests -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #9 from student/sync-to-tests" })),
    false
  );
});

// ...but the real thing, whose suffix is an abbreviated sha, still matches.
Deno.test("real sync branch merge (sync-to-<sha7>) -> sync", () => {
  assertEquals(
    isHandoutSyncPush(inputs({ headCommitMessage: "Merge pull request #12 from org/sync-to-9f8e7d6" })),
    true
  );
});

// Route 2: fork fast-forward — head becomes exactly a handout sha.
Deno.test("head equals assignments.latest_template_sha -> sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ afterSha: HANDOUT_SHA })), true);
});

Deno.test("head equals repositories.desired_handout_sha -> sync", () => {
  const desired = "c".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: desired, desiredHandoutSha: desired })), true);
});

Deno.test("head equals repositories.synced_handout_sha -> sync", () => {
  const synced = "d".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: synced, syncedHandoutSha: synced })), true);
});

Deno.test("head equals repositories.synced_repo_sha (merge commit of a prior sync) -> sync", () => {
  const mergeSha = "e".repeat(40);
  assertEquals(isHandoutSyncPush(inputs({ afterSha: mergeSha, syncedRepoSha: mergeSha })), true);
});

Deno.test("short-prefix overlap with a handout sha is NOT enough -> not a sync", () => {
  // Guards against the truncated-SHA false positives this codebase has hit before.
  assertEquals(isHandoutSyncPush(inputs({ afterSha: HANDOUT_SHA.slice(0, 7) })), false);
});

Deno.test("null handout shas never match -> not a sync", () => {
  assertEquals(
    isHandoutSyncPush({
      headCommitMessage: "work",
      afterSha: STUDENT_SHA,
      latestTemplateSha: null,
      desiredHandoutSha: null,
      syncedHandoutSha: null,
      syncedRepoSha: null
    }),
    false
  );
});

Deno.test("missing afterSha and no message match -> not a sync", () => {
  assertEquals(isHandoutSyncPush(inputs({ afterSha: null, headCommitMessage: null })), false);
});
