#!/usr/bin/env bash
# Pulls a per-PR preview's secrets out of its k8s namespace and emits a
# `.env.local`-compatible block. Same shape as export-staging-env.sh,
# but reads from `pawtograder-preview-pr-<id>` namespace via kubectl
# instead of OpenBao.
#
# Usage:
#   ./scripts/export-preview-env.sh helm        > .env.local
#   ./scripts/export-preview-env.sh 123         > .env.local
#   ./scripts/export-preview-env.sh helm --shell        # eval-able
#   eval "$(./scripts/export-preview-env.sh helm --shell)"
#
# Reads from these in-namespace Secrets (created by the preview workflow's
# `secrets` job):
#   pawtograder-jwt       JWT_SECRET, ANON_KEY, SERVICE_ROLE_KEY, …
#   pawtograder-postgres  POSTGRES_PASSWORD, PAWTOGRADER_PASSWORD
#   pawtograder-e2e       END_TO_END_SECRET, EDGE_FUNCTION_SECRET
#   pawtograder-s3        AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
#
# Connecting to postgres directly: requires either a port-forward
#   kubectl -n pawtograder-preview-pr-<id> port-forward svc/pawtograder-postgres 5433:5432
# then use the printed PG* vars with localhost:5433.

set -euo pipefail

if [ $# -lt 1 ] || [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
  grep '^#' "$0" | sed 's/^# \?//'
  exit 0
fi

PREVIEW_ID="$1"
mode=env
case "${2:-}" in
  --shell) mode=shell ;;
  --env|"") mode=env ;;
  *) echo "unknown arg: $2" >&2; exit 2 ;;
esac

NS="pawtograder-preview-pr-${PREVIEW_ID}"
WEB_URL="${NEXT_PUBLIC_PAWTOGRADER_WEB_URL_OVERRIDE:-https://pr-${PREVIEW_ID}.preview.pawtograder.net}"
API_URL="${NEXT_PUBLIC_SUPABASE_URL_OVERRIDE:-https://api.pr-${PREVIEW_ID}.preview.pawtograder.net}"

command -v kubectl >/dev/null 2>&1 || { echo "missing dependency: kubectl" >&2; exit 1; }

if ! kubectl get namespace "$NS" >/dev/null 2>&1; then
  echo "namespace $NS not found — was the preview deployed?" >&2
  exit 1
fi

emit() {
  if [ "$mode" = shell ]; then
    printf 'export %s=%q\n' "$1" "${2:-}"
  else
    # .env-style output: dotenv parsers (Next.js, dotenv) accept double-quoted
    # values with \n, \", \\ escapes — required for multiline secrets like
    # JWT_PRIVATE_JWKS or PEM-formatted keys.
    local value="${2:-}"
    value="${value//\\/\\\\}"   # backslash first, before introducing more
    value="${value//\"/\\\"}"   # double-quote
    value="${value//$'\n'/\\n}" # newline -> literal \n
    value="${value//$'\r'/\\r}" # CR -> literal \r
    printf '%s="%s"\n' "$1" "$value"
  fi
}

field() {
  # $1 = secret name, $2 = key. Empty if missing.
  kubectl -n "$NS" get secret "$1" -o jsonpath="{.data.$2}" 2>/dev/null | base64 -d 2>/dev/null || true
}

JWT_SECRET=$(field pawtograder-jwt JWT_SECRET)
ANON_KEY=$(field pawtograder-jwt ANON_KEY)
SERVICE_ROLE_KEY=$(field pawtograder-jwt SERVICE_ROLE_KEY)
JWT_PRIVATE_JWKS=$(field pawtograder-jwt JWT_PRIVATE_JWKS)
JWT_PUBLIC_JWKS=$(field pawtograder-jwt JWT_PUBLIC_JWKS)

POSTGRES_PASSWORD=$(field pawtograder-postgres POSTGRES_PASSWORD)
PAWTOGRADER_PASSWORD=$(field pawtograder-postgres PAWTOGRADER_PASSWORD)

END_TO_END_SECRET=$(field pawtograder-e2e END_TO_END_SECRET)
EDGE_FUNCTION_SECRET=$(field pawtograder-e2e EDGE_FUNCTION_SECRET)

S3_ACCESS=$(field pawtograder-s3 AWS_ACCESS_KEY_ID)
S3_SECRET=$(field pawtograder-s3 AWS_SECRET_ACCESS_KEY)

if [ "$mode" = env ]; then
  echo "# Generated by scripts/export-preview-env.sh against namespace $NS"
  echo "# Per-PR secrets live in the cluster — re-run when keys rotate."
  echo
fi

emit NODE_ENV development
emit NEXT_PUBLIC_PAWTOGRADER_WEB_URL "$WEB_URL"
emit NEXT_PUBLIC_SUPABASE_URL "$API_URL"
emit NEXT_PUBLIC_SUPABASE_ANON_KEY "$ANON_KEY"
emit SUPABASE_URL "$API_URL"
emit SUPABASE_ANON_KEY "$ANON_KEY"
emit SUPABASE_SERVICE_ROLE_KEY "$SERVICE_ROLE_KEY"
emit JWT_SECRET "$JWT_SECRET"
emit JWT_PRIVATE_JWKS "$JWT_PRIVATE_JWKS"
emit JWT_PUBLIC_JWKS "$JWT_PUBLIC_JWKS"
emit ENABLE_SIGNUPS "true"
emit NEXT_PUBLIC_ENABLE_SIGNUPS "true"

# Postgres direct-connect (use with `kubectl port-forward svc/pawtograder-postgres 5433:5432`)
emit PGHOST "127.0.0.1"
emit PGPORT "5433"
emit PGUSER "postgres"
emit PGDATABASE "postgres"
emit PGPASSWORD "$POSTGRES_PASSWORD"
emit PAWTOGRADER_PASSWORD "$PAWTOGRADER_PASSWORD"

# E2E load-test bypass tokens
emit END_TO_END_SECRET "$END_TO_END_SECRET"
emit EDGE_FUNCTION_SECRET "$EDGE_FUNCTION_SECRET"

# S3 / MinIO (shared previews bucket)
emit AWS_ACCESS_KEY_ID "$S3_ACCESS"
emit AWS_SECRET_ACCESS_KEY "$S3_SECRET"
emit S3_ENDPOINT "https://s3.talos.ripley.cloud"
emit S3_BUCKET "pawtograder-previews-shared"

if [ "$mode" = env ]; then
  cat <<EOF

# To open a psql session against this preview:
#   kubectl -n $NS port-forward svc/pawtograder-postgres 5433:5432 &
#   PGPASSWORD=\$PGPASSWORD psql -h 127.0.0.1 -p 5433 -U postgres
EOF
fi
