#!/usr/bin/env bash
# Pulls a per-PR preview's secrets out of its k8s namespace and emits a
# `.env`-style block tuned for an agent running INSIDE the cluster as a
# tenant pod. Same secrets as scripts/export-preview-env.sh, but every
# service URL points at the in-cluster Service DNS instead of the
# public ingress — no port-forward, no TLS, no ingress hops.
#
# Usage:
#   ./scripts/export-preview-incluster-env.sh helm        > tenant.env
#   ./scripts/export-preview-incluster-env.sh helm --shell        # eval-able
#   eval "$(./scripts/export-preview-incluster-env.sh helm --shell)"
#
# Hand-off shape:
#   - Tenant pod runs anywhere in the cluster (CoreDNS resolves the
#     <svc>.<ns>.svc.cluster.local names).
#   - All inbound auth uses the JWT bundle: anon for unauth, service
#     role for admin-equivalent, raw JWT_SECRET for HS256 signing if
#     they need to mint custom tokens.
#   - Postgres is reachable directly; PGHOST is the service DNS, no
#     port-forward needed. Use POSTGRES_PASSWORD (superuser) or
#     PAWTOGRADER_PASSWORD (application role) depending on needs.
#   - Edge functions are reachable directly on port 9000 (Kong-bypass)
#     or via Kong at /functions/v1/<name>.
#   - GitHub App credentials are present when secrets.externalSecret is
#     enabled (or when CI's topup stub-generated them). Mock GitHub is
#     active in preview, so these only matter when actually exercising
#     a real-GitHub code path.
#
# Reads from these in-namespace Secrets:
#   pawtograder-jwt              JWT bundle
#   pawtograder-postgres         POSTGRES_PASSWORD, PAWTOGRADER_PASSWORD
#   pawtograder-e2e              E2E + edge bypass tokens
#   pawtograder-s3               MinIO creds (Chime / storage)
#   pawtograder-edge-functions   GitHub App + integrations (best-effort)

set -euo pipefail

if [ $# -lt 1 ] || [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
  grep '^#' "$0" | sed 's/^# \?//'
  exit 0
fi

PREVIEW_ID="$1"
mode=env
case "${2:-}" in
  --shell) mode=shell ;;
  --env|"") mode=env ;;
  *) echo "unknown arg: $2" >&2; exit 2 ;;
esac

NS="pawtograder-preview-pr-${PREVIEW_ID}"

command -v kubectl >/dev/null 2>&1 || { echo "missing dependency: kubectl" >&2; exit 1; }

if ! kubectl get namespace "$NS" >/dev/null 2>&1; then
  echo "namespace $NS not found — was the preview deployed?" >&2
  exit 1
fi

emit() {
  if [ "$mode" = shell ]; then
    printf 'export %s=%q\n' "$1" "${2:-}"
  else
    local value="${2:-}"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\r'/\\r}"
    printf '%s="%s"\n' "$1" "$value"
  fi
}

field() {
  # $1 = secret name, $2 = key. Empty if missing.
  kubectl -n "$NS" get secret "$1" -o jsonpath="{.data.$2}" 2>/dev/null | base64 -d 2>/dev/null || true
}

# --- read JWT bundle ---------------------------------------------------------
JWT_SECRET=$(field pawtograder-jwt JWT_SECRET)
ANON_KEY=$(field pawtograder-jwt ANON_KEY)
SERVICE_ROLE_KEY=$(field pawtograder-jwt SERVICE_ROLE_KEY)
JWT_PRIVATE_JWKS=$(field pawtograder-jwt JWT_PRIVATE_JWKS)
JWT_PUBLIC_JWKS=$(field pawtograder-jwt JWT_PUBLIC_JWKS)
JWT_REALTIME_JWKS=$(field pawtograder-jwt JWT_REALTIME_JWKS)

# --- read postgres -----------------------------------------------------------
POSTGRES_PASSWORD=$(field pawtograder-postgres POSTGRES_PASSWORD)
PAWTOGRADER_PASSWORD=$(field pawtograder-postgres PAWTOGRADER_PASSWORD)

# --- read e2e bypass ---------------------------------------------------------
END_TO_END_SECRET=$(field pawtograder-e2e END_TO_END_SECRET)
EDGE_FUNCTION_SECRET=$(field pawtograder-e2e EDGE_FUNCTION_SECRET)

# --- read s3 / chime ---------------------------------------------------------
S3_ACCESS=$(field pawtograder-s3 AWS_ACCESS_KEY_ID)
S3_SECRET=$(field pawtograder-s3 AWS_SECRET_ACCESS_KEY)

# --- read edge-functions integration creds (best-effort, may be absent) -----
GITHUB_APP_ID=$(field pawtograder-edge-functions GITHUB_APP_ID)
GITHUB_PRIVATE_KEY_STRING=$(field pawtograder-edge-functions GITHUB_PRIVATE_KEY_STRING)
GITHUB_OAUTH_CLIENT_ID=$(field pawtograder-edge-functions GITHUB_OAUTH_CLIENT_ID)
GITHUB_OAUTH_CLIENT_SECRET=$(field pawtograder-edge-functions GITHUB_OAUTH_CLIENT_SECRET)
GITHUB_WEBHOOK_SECRET=$(field pawtograder-edge-functions GITHUB_WEBHOOK_SECRET)

# --- in-cluster URLs ---------------------------------------------------------
# Short names work within the same namespace. FQDN works from anywhere in
# the cluster. Use FQDN to be safe — agents running in their own tenant
# namespace will resolve these.
SVC="svc.cluster.local"
KONG_HOST="pawtograder-kong.${NS}.${SVC}:8000"

if [ "$mode" = env ]; then
  echo "# Generated by scripts/export-preview-incluster-env.sh against namespace $NS"
  echo "# Service URLs use in-cluster DNS — no port-forward, no ingress, no TLS."
  echo "# Source this from a tenant pod scheduled anywhere in the cluster."
  echo
fi

emit NODE_ENV development
emit PAWTOGRADER_NAMESPACE "$NS"

# --- API surface (via Kong gateway, same routing as the public ingress) -----
emit NEXT_PUBLIC_PAWTOGRADER_WEB_URL "http://pawtograder-web.${NS}.${SVC}:3000"
emit NEXT_PUBLIC_SUPABASE_URL        "http://${KONG_HOST}"
emit NEXT_PUBLIC_SUPABASE_ANON_KEY   "$ANON_KEY"
emit SUPABASE_URL                    "http://${KONG_HOST}"
emit SUPABASE_ANON_KEY               "$ANON_KEY"
emit SUPABASE_SERVICE_ROLE_KEY       "$SERVICE_ROLE_KEY"

# --- direct service URLs (bypass Kong for low-level debugging) --------------
emit PAWTOGRADER_POSTGREST_URL       "http://pawtograder-rest.${NS}.${SVC}:3000"
emit PAWTOGRADER_AUTH_URL            "http://pawtograder-auth.${NS}.${SVC}:9999"
emit PAWTOGRADER_STORAGE_URL         "http://pawtograder-storage.${NS}.${SVC}:5000"
emit PAWTOGRADER_REALTIME_URL        "ws://pawtograder-realtime.${NS}.${SVC}:4000/socket"
emit PAWTOGRADER_EDGE_FUNCTIONS_URL  "http://pawtograder-functions.${NS}.${SVC}:9000"
emit PAWTOGRADER_PG_META_URL         "http://pawtograder-meta.${NS}.${SVC}:8080"
emit PAWTOGRADER_KONG_ADMIN_URL      "http://pawtograder-kong.${NS}.${SVC}:8001"

# --- JWT material (sign custom tokens, verify signatures) -------------------
emit JWT_SECRET           "$JWT_SECRET"
emit JWT_PRIVATE_JWKS     "$JWT_PRIVATE_JWKS"
emit JWT_PUBLIC_JWKS      "$JWT_PUBLIC_JWKS"
emit JWT_REALTIME_JWKS    "$JWT_REALTIME_JWKS"

# --- postgres direct-connect ------------------------------------------------
emit PGHOST                "pawtograder-postgres.${NS}.${SVC}"
emit PGPORT                "5432"
emit PGUSER                "postgres"
emit PGDATABASE            "postgres"
emit PGPASSWORD            "$POSTGRES_PASSWORD"
emit PAWTOGRADER_DB_USER   "pawtograder"
emit PAWTOGRADER_PASSWORD  "$PAWTOGRADER_PASSWORD"
# Composed URLs for libraries that take a single DSN.
emit DATABASE_URL          "postgresql://postgres:${POSTGRES_PASSWORD}@pawtograder-postgres.${NS}.${SVC}:5432/postgres"
emit PAWTOGRADER_DB_URL    "postgresql://pawtograder:${PAWTOGRADER_PASSWORD}@pawtograder-postgres.${NS}.${SVC}:5432/postgres"

# --- E2E bypass tokens ------------------------------------------------------
emit END_TO_END_SECRET     "$END_TO_END_SECRET"
emit EDGE_FUNCTION_SECRET  "$EDGE_FUNCTION_SECRET"

# --- S3 / MinIO (Chime + storage backend) -----------------------------------
emit AWS_ACCESS_KEY_ID     "$S3_ACCESS"
emit AWS_SECRET_ACCESS_KEY "$S3_SECRET"
# MinIO sits at cluster scope (not in the preview namespace).
emit S3_ENDPOINT           "http://minio.minio.svc.cluster.local:9000"
emit S3_BUCKET             "pawtograder-previews-shared"

# --- GitHub App (only present if ESO or topup populated the Secret) ---------
if [ -n "$GITHUB_APP_ID" ]; then
  emit GITHUB_APP_ID              "$GITHUB_APP_ID"
  emit GITHUB_PRIVATE_KEY_STRING  "$GITHUB_PRIVATE_KEY_STRING"
  emit GITHUB_OAUTH_CLIENT_ID     "$GITHUB_OAUTH_CLIENT_ID"
  emit GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
  emit GITHUB_WEBHOOK_SECRET      "$GITHUB_WEBHOOK_SECRET"
fi

if [ "$mode" = env ]; then
  cat <<EOF

# In-cluster usage notes:
#   - All <svc>.${NS}.${SVC} names resolve from any pod in the cluster.
#   - Kong handles auth/rest/storage/realtime path routing; SUPABASE_URL
#     is the recommended entrypoint for supabase-js clients.
#   - For low-level debugging, hit each service directly via the
#     PAWTOGRADER_*_URL vars (skips Kong, no rate-limiting, no JWT
#     verification at the gateway — but the services still verify).
#   - Postgres connects directly: psql "\$DATABASE_URL"
#   - The edge runtime has E2E_MOCK_GITHUB=true in preview, so GitHub
#     calls return synthesized data; real GitHub creds are still loaded
#     in case a code path explicitly bypasses the mock.
EOF
fi
