#!/usr/bin/env bash
# Fetches a per-PR preview's e2e bundle from OpenBao and emits it as env —
# the out-of-cluster counterpart of export-preview-env.sh (which needs
# kubectl). Used by the a11y VoiceOver Mac runner; the bundle is published
# by preview.yml via scripts/publish-preview-e2e-to-bao.sh.
#
# Usage:
#   ./scripts/export-preview-e2e-from-bao.sh 123           > .env.preview
#   eval "$(./scripts/export-preview-e2e-from-bao.sh 123 --shell)"
#
# Auth resolution order:
#   1. BAO_TOKEN already exported — used as-is;
#   2. AppRole creds at ~/.config/pawtograder/bao/{role_id,secret_id}
#      (the Mac runner's standing setup — runbook §6);
#   3. whatever token `bao login` left in the token helper.
#
# Requires `bao` (or `vault`) on PATH and BAO_ADDR exported (defaults to
# the work cluster's OpenBao).
set -euo pipefail

if [ $# -lt 1 ] || [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
  grep '^#' "$0" | sed 's/^# \?//'
  exit 0
fi

PREVIEW_ID="$1"
mode=env
case "${2:-}" in
  --shell) mode=shell ;;
  --env|"") mode=env ;;
  *) echo "unknown arg: $2" >&2; exit 2 ;;
esac

if [[ ! "$PREVIEW_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]{0,38}$ ]]; then
  echo "ERROR: invalid preview_id '$PREVIEW_ID'" >&2
  exit 1
fi

export BAO_ADDR="${BAO_ADDR:-https://bao.work.ripley.cloud}"
BAO_MOUNT="${BAO_MOUNT:-kv}"
BAO_PATH="apps/pawtograder/preview-e2e/pr-${PREVIEW_ID}"
APPROLE_DIR="${APPROLE_DIR:-$HOME/.config/pawtograder/bao}"

CLI=""
if command -v bao >/dev/null 2>&1; then
  CLI=bao
elif command -v vault >/dev/null 2>&1; then
  CLI=vault
  : "${VAULT_ADDR:=$BAO_ADDR}"
  export VAULT_ADDR
else
  echo "ERROR: neither 'bao' nor 'vault' found on PATH (brew install openbao)" >&2
  exit 2
fi

# AppRole login when no token is present and standing creds exist.
if [ -z "${BAO_TOKEN:-}${VAULT_TOKEN:-}" ] && [ -r "$APPROLE_DIR/role_id" ] && [ -r "$APPROLE_DIR/secret_id" ]; then
  BAO_TOKEN=$($CLI write -field=token auth/approle/login \
    role_id="$(cat "$APPROLE_DIR/role_id")" \
    secret_id="$(cat "$APPROLE_DIR/secret_id")")
  export BAO_TOKEN
  [ "$CLI" = vault ] && export VAULT_TOKEN="$BAO_TOKEN"
fi

$CLI status >/dev/null 2>&1 || {
  echo "ERROR: $CLI status failed — set BAO_ADDR and log in (or provision $APPROLE_DIR, runbook §6)" >&2
  exit 1
}

if ! $CLI kv get -mount="$BAO_MOUNT" "$BAO_PATH" >/dev/null 2>&1; then
  echo "ERROR: no e2e bundle at ${BAO_MOUNT}/${BAO_PATH} — the preview for pr-${PREVIEW_ID} either" >&2
  echo "  isn't deployed, or predates the publish step. Re-run the preview deploy, or run" >&2
  echo "  scripts/publish-preview-e2e-to-bao.sh ${PREVIEW_ID} from a machine with cluster access." >&2
  exit 1
fi

bao_field() {
  $CLI kv get -mount="$BAO_MOUNT" -field="$1" "$BAO_PATH" 2>/dev/null || true
}

BASE_URL=$(bao_field BASE_URL)
SUPABASE_URL=$(bao_field SUPABASE_URL)
SUPABASE_ANON_KEY=$(bao_field SUPABASE_ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(bao_field SUPABASE_SERVICE_ROLE_KEY)
END_TO_END_SECRET=$(bao_field END_TO_END_SECRET)
EDGE_FUNCTION_SECRET=$(bao_field EDGE_FUNCTION_SECRET)

emit() {
  if [ "$mode" = shell ]; then
    printf 'export %s=%q\n' "$1" "${2:-}"
  else
    local value="${2:-}"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\r'/\\r}"
    printf '%s="%s"\n' "$1" "$value"
  fi
}

if [ "$mode" = env ]; then
  echo "# Generated by scripts/export-preview-e2e-from-bao.sh against ${BAO_MOUNT}/${BAO_PATH}"
  echo "# Published from the preview namespace by preview.yml — dies with the PR."
  echo
fi

emit BASE_URL "$BASE_URL"
emit SUPABASE_URL "$SUPABASE_URL"
emit NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
emit SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
emit NEXT_PUBLIC_SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
emit SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
emit E2E_ENABLE "true"
emit END_TO_END_SECRET "$END_TO_END_SECRET"
emit EDGE_FUNCTION_SECRET "$EDGE_FUNCTION_SECRET"
