#!/usr/bin/env bash
# Pulls staging secrets out of OpenBao and emits a `.env.local`-compatible
# block so you can run the Next.js frontend locally against the deployed
# staging Supabase. Same vars the GHA build workflow consumes, plus the
# server-only SUPABASE_SERVICE_ROLE_KEY.
#
# Usage:
#   export BAO_ADDR=https://bao.work.ripley.cloud   # if not already
#   bao login                                       # if not already
#   ./scripts/export-staging-env.sh > .env.local
#
# Or eval into the current shell:
#   eval "$(./scripts/export-staging-env.sh --shell)"
#
# Reads from kv/apps/pawtograder-staging/{jwt,github-app,discord,canvas,llm,sentry}.
# Skips integration credentials whose bao path doesn't exist (idempotent;
# fields stay unset rather than blocking).
set -euo pipefail

mode=env
case "${1:-}" in
  --shell) mode=shell ;;
  --env|"") mode=env ;;
  -h|--help)
    grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
esac

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "missing dependency: $1" >&2; exit 1; }
}
require bao

emit() {
  # $1 = name, $2 = value (may be empty)
  if [ "$mode" = shell ]; then
    printf 'export %s=%q\n' "$1" "${2:-}"
  else
    printf '%s=%s\n' "$1" "${2:-}"
  fi
}

bao_field() {
  # silent fetch — empty string if path or field missing
  bao kv get -field="$2" "$1" 2>/dev/null || true
}

KV_PREFIX=kv/apps/pawtograder-staging

# Hostnames — match what's in the chart's ingress for staging.
WEB_URL="${NEXT_PUBLIC_PAWTOGRADER_WEB_URL_OVERRIDE:-https://staging.pawtograder.net}"
API_URL="${NEXT_PUBLIC_SUPABASE_URL_OVERRIDE:-https://api.staging.pawtograder.net}"

# To run the LOCAL Next.js against the staging backend, you usually want
# WEB_URL=http://localhost:3000 (so OAuth redirects come back to your
# laptop). Override via env if so:
#   NEXT_PUBLIC_PAWTOGRADER_WEB_URL_OVERRIDE=http://localhost:3000 ./scripts/export-staging-env.sh

ANON_KEY=$(bao_field "$KV_PREFIX/jwt" ANON_KEY)
SERVICE_ROLE_KEY=$(bao_field "$KV_PREFIX/jwt" SERVICE_ROLE_KEY)

GITHUB_OAUTH_CLIENT_ID=$(bao_field "$KV_PREFIX/github-app" GITHUB_OAUTH_CLIENT_ID)
GITHUB_OAUTH_CLIENT_SECRET=$(bao_field "$KV_PREFIX/github-app" GITHUB_OAUTH_CLIENT_SECRET)
GITHUB_APP_ID=$(bao_field "$KV_PREFIX/github-app" GITHUB_APP_ID)
GITHUB_PRIVATE_KEY_STRING=$(bao_field "$KV_PREFIX/github-app" GITHUB_PRIVATE_KEY_STRING)
GITHUB_WEBHOOK_SECRET=$(bao_field "$KV_PREFIX/github-app" GITHUB_WEBHOOK_SECRET)

DISCORD_PUBLIC_KEY=$(bao_field "$KV_PREFIX/discord" DISCORD_PUBLIC_KEY)
DISCORD_BOT_TOKEN=$(bao_field "$KV_PREFIX/discord" DISCORD_BOT_TOKEN)
DISCORD_APPLICATION_ID=$(bao_field "$KV_PREFIX/discord" DISCORD_APPLICATION_ID)

CANVAS_API_URL=$(bao_field "$KV_PREFIX/canvas" CANVAS_API_URL)
CANVAS_API_KEY=$(bao_field "$KV_PREFIX/canvas" CANVAS_API_KEY)

OPENAI_API_KEY=$(bao_field "$KV_PREFIX/llm" OPENAI_API_KEY)
AZURE_OPENAI_KEY=$(bao_field "$KV_PREFIX/llm" AZURE_OPENAI_KEY)
ANTHROPIC_API_KEY=$(bao_field "$KV_PREFIX/llm" ANTHROPIC_API_KEY)

NEXT_PUBLIC_BUGSINK_DSN=$(bao_field "$KV_PREFIX/sentry" NEXT_PUBLIC_BUGSINK_DSN)
NEXT_PUBLIC_BUGSINK_HOST=$(bao_field "$KV_PREFIX/sentry" NEXT_PUBLIC_BUGSINK_HOST)

END_TO_END_SECRET=$(bao_field "$KV_PREFIX/e2e" END_TO_END_SECRET)
EDGE_FUNCTION_SECRET=$(bao_field "$KV_PREFIX/e2e" EDGE_FUNCTION_SECRET)

# ---------- emit -----------------------------------------------------------
if [ "$mode" = env ]; then
  echo "# Generated by scripts/export-staging-env.sh against $KV_PREFIX"
  echo "# Source of truth is OpenBao — re-run when keys rotate."
  echo
fi

emit NODE_ENV development
emit NEXT_PUBLIC_PAWTOGRADER_WEB_URL "$WEB_URL"
emit NEXT_PUBLIC_SUPABASE_URL "$API_URL"
emit NEXT_PUBLIC_SUPABASE_ANON_KEY "$ANON_KEY"
emit SUPABASE_URL "$API_URL"
emit SUPABASE_ANON_KEY "$ANON_KEY"
emit SUPABASE_SERVICE_ROLE_KEY "$SERVICE_ROLE_KEY"
emit ENABLE_SIGNUPS "false"
emit NEXT_PUBLIC_ENABLE_SIGNUPS "false"

emit NEXT_PUBLIC_GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
emit GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
emit GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
emit GITHUB_APP_ID "$GITHUB_APP_ID"
emit GITHUB_PRIVATE_KEY_STRING "$GITHUB_PRIVATE_KEY_STRING"
emit GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET"

emit DISCORD_PUBLIC_KEY "$DISCORD_PUBLIC_KEY"
emit DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"
emit DISCORD_APPLICATION_ID "$DISCORD_APPLICATION_ID"

emit CANVAS_API_URL "$CANVAS_API_URL"
emit CANVAS_API_KEY "$CANVAS_API_KEY"

emit OPENAI_API_KEY "$OPENAI_API_KEY"
emit AZURE_OPENAI_KEY "$AZURE_OPENAI_KEY"
emit ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

emit NEXT_PUBLIC_BUGSINK_DSN "$NEXT_PUBLIC_BUGSINK_DSN"
emit NEXT_PUBLIC_BUGSINK_HOST "$NEXT_PUBLIC_BUGSINK_HOST"

# E2E / load-test wiring. Backend edge functions check E2E_ENABLE and
# END_TO_END_SECRET to gate test-only privileged paths.
emit E2E_ENABLE "true"
emit END_TO_END_SECRET "$END_TO_END_SECRET"
emit EDGE_FUNCTION_SECRET "$EDGE_FUNCTION_SECRET"
