#!/usr/bin/env bash
# Emit a .env.local that points local frontend dev at a deploy preview.
#
#   scripts/preview-env.sh <pr-id>            # print to stdout
#   scripts/preview-env.sh <pr-id> > .env.local
#   scripts/preview-env.sh <pr-id> --write    # write ./.env.local in place
#
# Reads the anon + service-role keys straight from the preview's namespace
# (pawtograder-preview-pr-<id>) on the ripley cluster, so it always matches
# what that preview is actually running. Requires kubectl access to ripley:
# set KUBECONFIG, or it falls back to Jon's default path.
set -euo pipefail

id="${1:?usage: preview-env.sh <pr-id> [--write]}"
write="${2:-}"

export KUBECONFIG="${KUBECONFIG:-/home/jon/work/k8s/talos/kube/kubeconfig}"

ns="pawtograder-preview-pr-${id}"
web="https://pr-${id}.preview.pawtograder.net"
api="https://pr-${id}-api.preview.pawtograder.net"

kubectl get ns "$ns" >/dev/null 2>&1 || {
  echo "error: namespace $ns not found (is the preview for PR $id deployed?)" >&2
  exit 1
}

get() { kubectl -n "$ns" get secret pawtograder-jwt -o "jsonpath={.data.$1}" | base64 -d; }
anon="$(get ANON_KEY)"
service="$(get SERVICE_ROLE_KEY)"

read -r -d '' out <<EOF || true
# Preview PR ${id} — ${web}
# Generated by scripts/preview-env.sh from cluster secrets in ${ns}
NEXT_PUBLIC_SUPABASE_URL=${api}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
NEXT_PUBLIC_PAWTOGRADER_WEB_URL=${web}
SUPABASE_URL=${api}
SUPABASE_SERVICE_ROLE_KEY=${service}
ENABLE_SIGNUPS=true
EOF

if [ "$write" = "--write" ]; then
  printf '%s\n' "$out" > .env.local
  echo "wrote .env.local for preview PR ${id} (${web})" >&2
else
  printf '%s\n' "$out"
fi
