/**
 * Assessment export — streams a privacy-controlled snapshot of rubrics, final
 * grading review scores, autograder test results, Feedbot hint responses, hint
 * feedback, and gradebook columns for a class.
 *
 * Architecture (see /docs design discussion):
 *   - One CLI run = one random salt held only by the CLI.
 *   - The CLI fans out parallel calls keyed on assignment_slug. Each call
 *     constructs its own tokenizer using the same salt, so tokens for the
 *     same raw id agree across calls and can be joined on the analyst side.
 *   - First call: assessment.export.preamble emits manifest, students, and
 *     sections (the thin slice this file currently implements).
 *   - Subsequent calls (future tasks): assessment.export.assignment streams
 *     per-assignment rubric, autograder, scores, tests, hints; and
 *     assessment.export.gradebook streams gradebook columns + private cells.
 *
 * Identity modes:
 *   - "raw"    — emit real ids/emails/names. Requires confirm_pii: true.
 *   - "hash"   — HMAC of id with caller-supplied salt + server vault pepper;
 *                joinable across runs on the same deployment. Offline recompute
 *                requires the pepper, which never leaves the server.
 *   - "opaque" — per-run random CLI salt + server pepper; intra-run only.
 */

import type { MCPAuthContext } from "../../_shared/MCPAuth.ts";
import { registerCommand } from "../router.ts";
import { CLICommandError } from "../errors.ts";
import { getAdminClient } from "../utils/supabase.ts";
import { resolveClass } from "../utils/resolvers.ts";
import { assertUserCanAccessClass } from "../utils/auth.ts";
import { streamNdjson } from "../utils/ndjson.ts";
import { fetchRubricWithHierarchy } from "../utils/rubric.ts";
import { resolveSelectors } from "../utils/selectors.ts";
import { createExportTokenizer } from "../utils/assessmentExportPepper.ts";
import { validateExportIdentityParams } from "../utils/exportIdentity.ts";
import { prepareInstructorBuildOutput } from "../utils/sanitizeGradingPaths.ts";
import { streamSubmissions } from "../utils/submissionExportStream.ts";
import { type IdentityMode, type Tokenizer } from "../utils/tokenization.ts";

const SCHEMA_VERSION = 1;
const STUDENT_PAGE_SIZE = 500;
const FACT_PAGE_SIZE = 1000;
/** Max UUIDs per PostgREST `.in()` filter — long lists exceed HTTP URL limits. */
const UUID_IN_BATCH_SIZE = 50;
const DEFAULT_TEST_OUTPUT_MAX_BYTES = 4096;
const DEFAULT_INSTRUCTOR_BUILD_OUTPUT_MAX_BYTES = 4096;

interface PreambleParams {
  class?: string | number;
  identity_mode?: IdentityMode;
  salt?: string;
  /** Required when identity_mode === "raw" — explicit acknowledgement. */
  confirm_pii?: boolean;
  /** UUID generated by the CLI per run. Echoed in the manifest for traceability. */
  dump_id?: string;
  /**
   * Assignment selectors. Each entry is one of:
   *   - numeric id (string of digits or number)
   *   - exact slug
   *   - minimatch-style glob on slug (e.g. "hw-*", "lab?")
   * Null/empty array => all assignments in the class.
   */
  assignments?: Array<string | number>;
  /** Gradebook column selectors, same id|slug|glob shape. Empty => all columns. */
  gradebook_columns?: Array<string | number>;
  /** When true, omit gradebook column metadata from the preamble. */
  skip_gradebook?: boolean;
}

async function handlePreamble(ctx: MCPAuthContext, rawParams: Record<string, unknown>): Promise<Response> {
  const params = rawParams as unknown as PreambleParams;
  const classIdentifier = params.class;
  const mode = validateExportIdentityParams(params);
  const dumpId = params.dump_id ?? crypto.randomUUID();

  if (!classIdentifier) throw new CLICommandError("class is required");

  const supabase = getAdminClient();
  const classData = await resolveClass(supabase, classIdentifier);
  await assertUserCanAccessClass(supabase, ctx.userId, classData.id);

  const tokenizer = mode === "raw" ? null : await createExportTokenizer(supabase, params.salt!);

  return streamNdjson(async (writer) => {
    await writer.write({
      kind: "manifest",
      schema_version: SCHEMA_VERSION,
      dump_id: dumpId,
      identity_mode: mode,
      exported_at: new Date().toISOString(),
      class: { id: classData.id, slug: classData.slug, name: classData.name }
    });

    const subjectCount = await streamStudents(supabase, classData.id, mode, tokenizer, writer);
    const sectionCount = await streamSections(supabase, classData.id, mode, tokenizer, writer);
    const assignmentCount = await streamAssignments(supabase, classData.id, params.assignments, writer);
    const gradebookColumnCount =
      params.skip_gradebook === true
        ? 0
        : await streamGradebookColumns(supabase, classData.id, params.gradebook_columns, writer);

    await writer.write({
      kind: "end",
      counts: {
        subjects: subjectCount,
        sections: sectionCount,
        assignments: assignmentCount,
        gradebook_columns: gradebookColumnCount
      }
    });
  });
}

/**
 * Page through students in the class and emit one {kind:"subject"} record per
 * student. Pagination is by private_profile_id, NOT OFFSET, so a class with
 * 1000 students still completes in O(1) DB cursors regardless of page size.
 *
 * The subject token is derived from private_profile_id — this is the foreign
 * key used by every per-assignment fact table (submissions.profile_id,
 * grader_result_tests.student_id, submission_*_comments.target_student_profile_id,
 * gradebook_column_students.student_id, assignment_groups_members.profile_id).
 * Using user_id would mean the analyst couldn't join subjects to fact rows.
 */
async function streamStudents(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  let cursor: string | null = null;
  let total = 0;

  while (true) {
    let query = supabase
      .from("user_roles")
      .select("user_id, class_section_id, lab_section_id, private_profile_id")
      .eq("class_id", classId)
      .eq("disabled", false)
      .eq("role", "student")
      .order("private_profile_id", { ascending: true })
      .limit(STUDENT_PAGE_SIZE);

    if (cursor !== null) query = query.gt("private_profile_id", cursor);

    const { data: rows, error } = await query;
    if (error) throw new CLICommandError(`Failed to load students: ${error.message}`, 500);
    if (!rows || rows.length === 0) break;

    // For raw mode, join users to surface email/name. We do this per-page in
    // a single roundtrip rather than nesting in the user_roles select to keep
    // the query plan simple and avoid PostgREST's nested-select overhead.
    let userInfo: Map<string, { email: string | null; name: string | null }> | null = null;
    if (mode === "raw") {
      userInfo = new Map();
      const userIds = rows.map((r) => r.user_id);
      for (const batch of chunked(userIds, UUID_IN_BATCH_SIZE)) {
        const { data: userRows, error: userErr } = await supabase
          .from("users")
          .select("user_id, email, name")
          .in("user_id", batch);
        if (userErr) throw new CLICommandError(`Failed to load user emails: ${userErr.message}`, 500);
        for (const u of userRows ?? []) {
          userInfo.set(u.user_id, { email: u.email, name: u.name });
        }
      }
    }

    for (const row of rows) {
      const subjectRef =
        tokenizer === null
          ? { id: row.private_profile_id }
          : { token: await tokenizer.token("subject", row.private_profile_id) };

      const classSectionRef =
        row.class_section_id === null
          ? null
          : tokenizer === null
            ? { id: row.class_section_id }
            : { token: await tokenizer.token("section_class", row.class_section_id) };

      const labSectionRef =
        row.lab_section_id === null
          ? null
          : tokenizer === null
            ? { id: row.lab_section_id }
            : { token: await tokenizer.token("section_lab", row.lab_section_id) };

      const record: Record<string, unknown> = {
        kind: "subject",
        subject_kind: "student",
        ...subjectRef,
        class_section: classSectionRef,
        lab_section: labSectionRef
      };

      if (mode === "raw") {
        const info = userInfo!.get(row.user_id);
        // user_id is included alongside private_profile_id ("id") in raw mode
        // because it's the only id stable across classes — useful for analysts
        // joining multiple class exports for the same student.
        record.user_id = row.user_id;
        record.email = info?.email ?? null;
        record.name = info?.name ?? null;
      }

      await writer.write(record);
      total += 1;
    }

    if (rows.length < STUDENT_PAGE_SIZE) break;
    cursor = rows[rows.length - 1]!.private_profile_id;
  }

  return total;
}

/**
 * Class and lab sections in the class. Section names are passed through
 * verbatim — they are usually what instructors want for analysis. The risk
 * (section names can re-identify students in small labs) is documented in
 * the manifest and surfaced to the CLI user; this function does not redact.
 */
async function streamSections(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  let total = 0;

  const { data: classSections, error: csErr } = await supabase
    .from("class_sections")
    .select("id, name, meeting_times, meeting_location, campus")
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (csErr) throw new CLICommandError(`Failed to load class sections: ${csErr.message}`, 500);

  for (const sec of classSections ?? []) {
    const ref = tokenizer === null ? { id: sec.id } : { token: await tokenizer.token("section_class", sec.id) };
    await writer.write({
      kind: "section",
      section_kind: "class",
      ...ref,
      name: sec.name,
      meeting_times: sec.meeting_times,
      meeting_location: sec.meeting_location,
      campus: sec.campus
    });
    total += 1;
  }

  const { data: labSections, error: lsErr } = await supabase
    .from("lab_sections")
    .select("id, name, meeting_times, meeting_location, campus, day_of_week, start_time, end_time")
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (lsErr) throw new CLICommandError(`Failed to load lab sections: ${lsErr.message}`, 500);

  for (const sec of labSections ?? []) {
    const ref = tokenizer === null ? { id: sec.id } : { token: await tokenizer.token("section_lab", sec.id) };
    await writer.write({
      kind: "section",
      section_kind: "lab",
      ...ref,
      name: sec.name,
      meeting_times: sec.meeting_times,
      meeting_location: sec.meeting_location,
      campus: sec.campus,
      day_of_week: sec.day_of_week,
      start_time: sec.start_time,
      end_time: sec.end_time
    });
    total += 1;
  }

  return total;
}

/**
 * Resolve assignment selectors against the class and emit one
 * {kind:"assignment"} record per match. Assignment ids/slugs are NOT
 * tokenized — they are the analyst's primary key for joining per-assignment
 * fact rows to the catalog, and the slug is course design metadata, not PII.
 *
 * Unmatched selectors are emitted as a single {kind:"warning"} record so the
 * CLI can surface them; the stream does not fail.
 */
async function streamAssignments(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  selectors: PreambleParams["assignments"],
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  const { data: rows, error } = await supabase
    .from("assignments")
    .select(
      "id, slug, title, group_config, due_date, release_date, total_points, has_autograder, has_handgrader, grading_rubric_id"
    )
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (error) throw new CLICommandError(`Failed to load assignments: ${error.message}`, 500);

  const candidates = (rows ?? []).map((r) => ({ ...r, slug: r.slug ?? null }));
  const { resolved, unmatched } = resolveSelectors(selectors, candidates);

  if (unmatched.length > 0) {
    await writer.write({
      kind: "warning",
      scope: "assignments",
      message: `${unmatched.length} assignment selector(s) matched nothing`,
      selectors: unmatched
    });
  }

  for (const a of resolved) {
    await writer.write({
      kind: "assignment",
      id: a.id,
      slug: a.slug,
      title: a.title,
      group_config: a.group_config,
      due_date: a.due_date,
      release_date: a.release_date,
      total_points: a.total_points,
      has_autograder: a.has_autograder,
      has_handgrader: a.has_handgrader,
      grading_rubric_id: a.grading_rubric_id
    });
  }
  return resolved.length;
}

/**
 * Resolve gradebook column selectors. instructor_only columns are always
 * included (this export is for instructor analysis). The accompanying
 * gradebook_score rows are filtered server-side to is_private = true; that
 * filter is owned by the per-assignment gradebook stream, not here.
 */
async function streamGradebookColumns(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  selectors: PreambleParams["gradebook_columns"],
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  const { data: rows, error } = await supabase
    .from("gradebook_columns")
    .select(
      "id, slug, name, description, max_score, instructor_only, released, sort_order, score_expression, render_expression, dependencies"
    )
    .eq("class_id", classId)
    .order("sort_order", { ascending: true, nullsFirst: false })
    .order("id", { ascending: true });
  if (error) throw new CLICommandError(`Failed to load gradebook columns: ${error.message}`, 500);

  const candidates = (rows ?? []).map((r) => ({ ...r, slug: r.slug }));
  const { resolved, unmatched } = resolveSelectors(selectors, candidates);

  if (unmatched.length > 0) {
    await writer.write({
      kind: "warning",
      scope: "gradebook_columns",
      message: `${unmatched.length} gradebook column selector(s) matched nothing`,
      selectors: unmatched
    });
  }

  for (const c of resolved) {
    await writer.write({
      kind: "gradebook_column",
      id: c.id,
      slug: c.slug,
      name: c.name,
      description: c.description,
      max_score: c.max_score,
      instructor_only: c.instructor_only,
      released: c.released,
      sort_order: c.sort_order,
      score_expression: c.score_expression,
      render_expression: c.render_expression,
      dependencies: c.dependencies
    });
  }
  return resolved.length;
}

type AssignmentExportSection = "all" | "meta" | "submissions" | "scores" | "tests" | "build_output" | "engagement";

interface AssignmentExportParams {
  class?: string | number;
  identity_mode?: IdentityMode;
  salt?: string;
  confirm_pii?: boolean;
  /** Single assignment id or slug. The CLI resolves selectors via preamble and fans out one call per id. */
  assignment?: string | number;
  /** Include grader_result_tests.output (truncated to test_output_max_bytes). */
  with_test_output?: boolean;
  test_output_max_bytes?: number;
  /** Include grader_result_output where visibility=hidden (truncated, paths sanitized). */
  with_instructor_build_output?: boolean;
  instructor_build_output_max_bytes?: number;
  /** When set, each hidden build log is trimmed to start at this substring (after path sanitization). */
  instructor_build_output_from_sentinel?: string;
  /** When true, export every submission attempt; default is is_active only. */
  all_submissions?: boolean;
  /**
   * Export slice for chunked assignment dumps. The CLI calls meta → submissions →
   * scores → tests → build_output → engagement separately so each edge invocation
   * gets a fresh CPU budget. Omit or "all" for a single monolithic stream (may time out).
   */
  section?: AssignmentExportSection;
  /** Paginate scores section: batch index over grading-review ids (0-based). */
  score_review_batch_index?: number;
  /** Paginate tests section: batch index over submission ids (0-based). */
  test_submission_batch_index?: number;
  /** Paginate build_output section: batch index over submission ids (0-based). */
  build_output_submission_batch_index?: number;
  /** Paginate engagement section: batch index over submission ids (0-based). */
  engagement_submission_batch_index?: number;
}

/** Grading reviews processed per scores-section edge call. */
const SCORE_REVIEW_BATCH_SIZE = 80;
/** Submissions per tests-section call when output is included (output is heavy). */
const TEST_SUBMISSION_BATCH_WITH_OUTPUT = 20;
/** Submissions per tests-section call without output. */
const TEST_SUBMISSION_BATCH_NO_OUTPUT = 100;
/** Submissions per build_output-section call (hidden build logs are heavy). */
const BUILD_OUTPUT_SUBMISSION_BATCH_SIZE = 20;
/** Submissions per engagement-section call (hints + error-pin rows). */
const ENGAGEMENT_SUBMISSION_BATCH_SIZE = 150;

type AssignmentExportContext = {
  supabase: ReturnType<typeof getAdminClient>;
  classData: { id: number; slug: string };
  assignmentRow: { id: number; slug: string; title: string; grading_rubric_id: number | null };
  tokenizer: Tokenizer | null;
  mode: IdentityMode;
  allSubmissions: boolean;
  withTestOutput: boolean;
  testOutputMax: number;
  withInstructorBuildOutput: boolean;
  instructorBuildOutputMax: number;
  instructorBuildOutputFromSentinel: string | null;
};

/** Strip multi-kilobyte LLM prompt/result blobs from test rows — hints.json carries results. */
function slimExtraDataForExport(extra: unknown): unknown {
  if (extra === null || extra === undefined || typeof extra !== "object") return extra ?? null;
  const data = extra as Record<string, unknown>;
  const llm = data.llm;
  if (llm === null || llm === undefined || typeof llm !== "object") return extra;
  const llmObj = llm as Record<string, unknown>;
  const { prompt: _prompt, result: _result, ...llmRest } = llmObj;
  return {
    ...data,
    llm: {
      ...llmRest,
      has_prompt: typeof llmObj.prompt === "string" && llmObj.prompt.length > 0,
      has_result: typeof llmObj.result === "string" && llmObj.result.trim().length > 0
    }
  };
}

async function resolveAssignmentExportContext(
  ctx: MCPAuthContext,
  params: AssignmentExportParams
): Promise<AssignmentExportContext> {
  const classIdentifier = params.class;
  const assignmentIdentifier = params.assignment;
  const mode = validateExportIdentityParams(params);
  const withTestOutput = params.with_test_output === true;
  const withInstructorBuildOutput = params.with_instructor_build_output === true;
  const allSubmissions = params.all_submissions === true;
  const testOutputMax = Math.max(
    0,
    Math.min(1024 * 1024, params.test_output_max_bytes ?? DEFAULT_TEST_OUTPUT_MAX_BYTES)
  );
  const instructorBuildOutputMax = Math.max(
    0,
    Math.min(
      1024 * 1024,
      params.instructor_build_output_max_bytes ?? DEFAULT_INSTRUCTOR_BUILD_OUTPUT_MAX_BYTES
    )
  );
  const instructorBuildOutputFromSentinel =
    typeof params.instructor_build_output_from_sentinel === "string" &&
    params.instructor_build_output_from_sentinel.length > 0
      ? params.instructor_build_output_from_sentinel
      : null;

  if (!classIdentifier) throw new CLICommandError("class is required");
  if (!assignmentIdentifier) throw new CLICommandError("assignment is required");

  const supabase = getAdminClient();
  const classData = await resolveClass(supabase, classIdentifier);
  await assertUserCanAccessClass(supabase, ctx.userId, classData.id);
  const assignmentRow = await resolveOneAssignment(supabase, classData.id, assignmentIdentifier);
  const tokenizer = mode === "raw" ? null : await createExportTokenizer(supabase, params.salt!);

  return {
    supabase,
    classData,
    assignmentRow,
    tokenizer,
    mode,
    allSubmissions,
    withTestOutput,
    testOutputMax,
    withInstructorBuildOutput,
    instructorBuildOutputMax,
    instructorBuildOutputFromSentinel
  };
}

function exportAssignmentMeta(exportCtx: AssignmentExportContext): Promise<Response> {
  const { supabase, classData, assignmentRow, tokenizer, mode, allSubmissions } = exportCtx;
  return streamNdjson(async (writer) => {
    await writer.write({
      kind: "manifest",
      schema_version: SCHEMA_VERSION,
      identity_mode: mode,
      class: { id: classData.id, slug: classData.slug },
      assignment: { id: assignmentRow.id, slug: assignmentRow.slug, title: assignmentRow.title },
      submissions_scope: allSubmissions ? "all" : "active",
      scores_scope: "active"
    });

    const rubricCount = await streamRubric(supabase, assignmentRow.grading_rubric_id, mode, tokenizer, writer);
    const autograderTestCount = await streamAutograderConfig(supabase, assignmentRow.id, writer);
    const groupCount = await streamGroups(supabase, assignmentRow.id, classData.id, mode, tokenizer, writer);

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: rubricCount,
        autograder_tests: autograderTestCount,
        groups: groupCount,
        submissions: 0,
        scores: 0,
        grader_tests: 0,
        hints: 0,
        instructor_build_outputs: 0,
        error_pin_engagement: 0
      }
    });
  });
}

function exportAssignmentSubmissions(exportCtx: AssignmentExportContext): Promise<Response> {
  const { supabase, assignmentRow, tokenizer, mode, allSubmissions } = exportCtx;
  return streamNdjson(async (writer) => {
    const { submissionCount } = await streamSubmissions(
      supabase,
      assignmentRow.id,
      allSubmissions,
      mode,
      tokenizer,
      writer
    );

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: 0,
        autograder_tests: 0,
        groups: 0,
        submissions: submissionCount,
        scores: 0,
        grader_tests: 0,
        hints: 0,
        instructor_build_outputs: 0,
        error_pin_engagement: 0
      }
    });
  });
}

function exportAssignmentScores(exportCtx: AssignmentExportContext, batchIndex: number): Promise<Response> {
  const { supabase, assignmentRow, tokenizer, mode, allSubmissions } = exportCtx;
  return streamNdjson(async (writer) => {
    const { activeSubmissionIds } = await loadSubmissionScope(supabase, assignmentRow.id, allSubmissions);
    const { reviewIds, reviewToSubmission } = await loadReviewScope(supabase, activeSubmissionIds);

    const start = batchIndex * SCORE_REVIEW_BATCH_SIZE;
    const reviewBatch = reviewIds.slice(start, start + SCORE_REVIEW_BATCH_SIZE);
    const hasMore = start + SCORE_REVIEW_BATCH_SIZE < reviewIds.length;

    const scoreCount =
      reviewBatch.length === 0
        ? 0
        : await streamScoresForReviews(supabase, reviewBatch, reviewToSubmission, mode, tokenizer, writer);

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: 0,
        autograder_tests: 0,
        groups: 0,
        submissions: 0,
        scores: scoreCount,
        grader_tests: 0,
        hints: 0,
        instructor_build_outputs: 0,
        error_pin_engagement: 0
      },
      ...(hasMore ? { next_score_review_batch_index: batchIndex + 1 } : {})
    });
  });
}

function exportAssignmentTests(exportCtx: AssignmentExportContext, batchIndex: number): Promise<Response> {
  const { supabase, assignmentRow, tokenizer, mode, allSubmissions, withTestOutput, testOutputMax } = exportCtx;
  const batchSize = withTestOutput ? TEST_SUBMISSION_BATCH_WITH_OUTPUT : TEST_SUBMISSION_BATCH_NO_OUTPUT;

  return streamNdjson(async (writer) => {
    const { submissionIds } = await loadSubmissionScope(supabase, assignmentRow.id, allSubmissions);
    const start = batchIndex * batchSize;
    const submissionBatch = submissionIds.slice(start, start + batchSize);
    const hasMore = start + batchSize < submissionIds.length;

    const { testCount } = await streamGraderTests(
      supabase,
      submissionBatch,
      mode,
      tokenizer,
      writer,
      withTestOutput,
      testOutputMax
    );

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: 0,
        autograder_tests: 0,
        groups: 0,
        submissions: 0,
        scores: 0,
        grader_tests: testCount,
        hints: 0,
        instructor_build_outputs: 0,
        error_pin_engagement: 0
      },
      ...(hasMore ? { next_test_submission_batch_index: batchIndex + 1 } : {})
    });
  });
}

function exportAssignmentBuildOutput(exportCtx: AssignmentExportContext, batchIndex: number): Promise<Response> {
  const {
    supabase,
    assignmentRow,
    tokenizer,
    mode,
    allSubmissions,
    withInstructorBuildOutput,
    instructorBuildOutputMax,
    instructorBuildOutputFromSentinel
  } = exportCtx;

  return streamNdjson(async (writer) => {
    const { submissionIds } = await loadSubmissionScope(supabase, assignmentRow.id, allSubmissions);
    const start = batchIndex * BUILD_OUTPUT_SUBMISSION_BATCH_SIZE;
    const submissionBatch = submissionIds.slice(start, start + BUILD_OUTPUT_SUBMISSION_BATCH_SIZE);
    const hasMore = start + BUILD_OUTPUT_SUBMISSION_BATCH_SIZE < submissionIds.length;

    const buildOutputCount =
      withInstructorBuildOutput && submissionBatch.length > 0
        ? await streamInstructorBuildOutput(
            supabase,
            submissionBatch,
            mode,
            tokenizer,
            writer,
            instructorBuildOutputMax,
            instructorBuildOutputFromSentinel
          )
        : 0;

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: 0,
        autograder_tests: 0,
        groups: 0,
        submissions: 0,
        scores: 0,
        grader_tests: 0,
        hints: 0,
        instructor_build_outputs: buildOutputCount,
        error_pin_engagement: 0
      },
      ...(hasMore ? { next_build_output_submission_batch_index: batchIndex + 1 } : {})
    });
  });
}

function exportAssignmentEngagement(exportCtx: AssignmentExportContext, batchIndex: number): Promise<Response> {
  const { supabase, classData, assignmentRow, tokenizer, mode, allSubmissions } = exportCtx;

  return streamNdjson(async (writer) => {
    const { submissionIds } = await loadSubmissionScope(supabase, assignmentRow.id, allSubmissions);
    const start = batchIndex * ENGAGEMENT_SUBMISSION_BATCH_SIZE;
    const submissionBatch = submissionIds.slice(start, start + ENGAGEMENT_SUBMISSION_BATCH_SIZE);
    const hasMore = start + ENGAGEMENT_SUBMISSION_BATCH_SIZE < submissionIds.length;

    const hintCount = await streamHints(supabase, submissionBatch, mode, tokenizer, writer);
    const errorPinEngagementCount = await streamErrorPinEngagement(
      supabase,
      classData.id,
      submissionBatch,
      mode,
      tokenizer,
      writer
    );

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: 0,
        autograder_tests: 0,
        groups: 0,
        submissions: 0,
        scores: 0,
        grader_tests: 0,
        hints: hintCount,
        instructor_build_outputs: 0,
        error_pin_engagement: errorPinEngagementCount
      },
      ...(hasMore ? { next_engagement_submission_batch_index: batchIndex + 1 } : {})
    });
  });
}

function exportAssignmentAll(exportCtx: AssignmentExportContext): Promise<Response> {
  const {
    supabase,
    classData,
    assignmentRow,
    tokenizer,
    mode,
    allSubmissions,
    withTestOutput,
    testOutputMax,
    withInstructorBuildOutput,
    instructorBuildOutputMax,
    instructorBuildOutputFromSentinel
  } = exportCtx;

  return streamNdjson(async (writer) => {
    await writer.write({
      kind: "manifest",
      schema_version: SCHEMA_VERSION,
      identity_mode: mode,
      class: { id: classData.id, slug: classData.slug },
      assignment: { id: assignmentRow.id, slug: assignmentRow.slug, title: assignmentRow.title },
      submissions_scope: allSubmissions ? "all" : "active",
      scores_scope: "active"
    });

    const rubricCount = await streamRubric(supabase, assignmentRow.grading_rubric_id, mode, tokenizer, writer);
    const autograderTestCount = await streamAutograderConfig(supabase, assignmentRow.id, writer);
    const groupCount = await streamGroups(supabase, assignmentRow.id, classData.id, mode, tokenizer, writer);

    const { submissionCount, submissionIds, activeSubmissionIds } = await streamSubmissions(
      supabase,
      assignmentRow.id,
      allSubmissions,
      mode,
      tokenizer,
      writer
    );

    const scoreCount = await streamScores(supabase, activeSubmissionIds, mode, tokenizer, writer);
    const { testCount } = await streamGraderTests(
      supabase,
      submissionIds,
      mode,
      tokenizer,
      writer,
      withTestOutput,
      testOutputMax
    );
    const buildOutputCount = withInstructorBuildOutput
      ? await streamInstructorBuildOutput(
          supabase,
          submissionIds,
          mode,
          tokenizer,
          writer,
          instructorBuildOutputMax,
          instructorBuildOutputFromSentinel
        )
      : 0;
    const hintCount = await streamHints(supabase, submissionIds, mode, tokenizer, writer);
    const errorPinEngagementCount = await streamErrorPinEngagement(
      supabase,
      classData.id,
      submissionIds,
      mode,
      tokenizer,
      writer
    );

    await writer.write({
      kind: "end",
      counts: {
        rubric_checks: rubricCount,
        autograder_tests: autograderTestCount,
        groups: groupCount,
        submissions: submissionCount,
        scores: scoreCount,
        grader_tests: testCount,
        hints: hintCount,
        instructor_build_outputs: buildOutputCount,
        error_pin_engagement: errorPinEngagementCount
      }
    });
  });
}

/**
 * Streams everything specific to one assignment. The CLI fans out sectioned
 * calls (meta → submissions → scores → tests → build_output → engagement) so each edge
 * invocation stays within CPU limits on large classes.
 */
async function handleAssignmentExport(ctx: MCPAuthContext, rawParams: Record<string, unknown>): Promise<Response> {
  const params = rawParams as unknown as AssignmentExportParams;
  const exportCtx = await resolveAssignmentExportContext(ctx, params);
  const section: AssignmentExportSection = params.section ?? "all";

  switch (section) {
    case "meta":
      return exportAssignmentMeta(exportCtx);
    case "submissions":
      return exportAssignmentSubmissions(exportCtx);
    case "scores":
      return exportAssignmentScores(exportCtx, Math.max(0, params.score_review_batch_index ?? 0));
    case "tests":
      return exportAssignmentTests(exportCtx, Math.max(0, params.test_submission_batch_index ?? 0));
    case "build_output":
      return exportAssignmentBuildOutput(exportCtx, Math.max(0, params.build_output_submission_batch_index ?? 0));
    case "engagement":
      return exportAssignmentEngagement(exportCtx, Math.max(0, params.engagement_submission_batch_index ?? 0));
    case "all":
    default:
      return exportAssignmentAll(exportCtx);
  }
}

async function resolveOneAssignment(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  identifier: string | number
) {
  const idStr = String(identifier);
  if (/^\d+$/.test(idStr)) {
    const { data } = await supabase
      .from("assignments")
      .select("id, slug, title, grading_rubric_id, group_config")
      .eq("class_id", classId)
      .eq("id", Number(idStr))
      .maybeSingle();
    if (data) return data;
  }
  const { data } = await supabase
    .from("assignments")
    .select("id, slug, title, grading_rubric_id, group_config")
    .eq("class_id", classId)
    .eq("slug", idStr)
    .maybeSingle();
  if (!data) throw new CLICommandError(`assignment not found in class ${classId}: ${identifier}`, 404);
  return data;
}

/**
 * Emit the rubric tree as a flat sequence of part/criteria/check records.
 * Each record carries the parent ids so analysts can rebuild the hierarchy.
 * rubric_check_token comes from rubric_check.id; check ids are not PII (they
 * are course design data) but the analyst will join score rows on the token.
 */
async function streamRubric(
  supabase: ReturnType<typeof getAdminClient>,
  rubricId: number | null,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  if (rubricId === null) return 0;
  const rubric = await fetchRubricWithHierarchy(supabase, rubricId);
  if (!rubric) return 0;

  await writer.write({
    kind: "rubric",
    id: rubric.id,
    name: rubric.name,
    description: rubric.description,
    cap_score_to_assignment_points: rubric.cap_score_to_assignment_points,
    review_round: rubric.review_round
  });

  let checkCount = 0;
  for (const part of rubric.rubric_parts ?? []) {
    await writer.write({
      kind: "rubric_part",
      id: part.id,
      rubric_id: rubric.id,
      name: part.name,
      description: part.description,
      ordinal: part.ordinal
    });
    for (const criteria of part.rubric_criteria ?? []) {
      await writer.write({
        kind: "rubric_criteria",
        id: criteria.id,
        rubric_part_id: part.id,
        name: criteria.name,
        description: criteria.description,
        ordinal: criteria.ordinal,
        total_points: criteria.total_points,
        is_additive: criteria.is_additive,
        is_deduction_only: criteria.is_deduction_only,
        min_checks_per_submission: criteria.min_checks_per_submission,
        max_checks_per_submission: criteria.max_checks_per_submission
      });
      for (const check of criteria.rubric_checks ?? []) {
        const ref = tokenizer === null ? { id: check.id } : { token: await tokenizer.token("rubric_check", check.id) };
        await writer.write({
          kind: "rubric_check",
          ...ref,
          rubric_criteria_id: criteria.id,
          name: check.name,
          description: check.description,
          ordinal: check.ordinal,
          points: check.points,
          is_annotation: check.is_annotation,
          is_required: check.is_required,
          student_visibility: check.student_visibility
        });
        checkCount += 1;
      }
    }
  }
  return checkCount;
}

/**
 * Emit the autograder test catalog from autograder.config. The catalog is
 * the source of truth for "what tests exist" — tests no student triggered
 * still appear here. grader_result_tests rows reference (name, part) since
 * the autograder doesn't assign stable test ids.
 */
async function streamAutograderConfig(
  supabase: ReturnType<typeof getAdminClient>,
  assignmentId: number,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  const { data, error } = await supabase
    .from("autograder")
    .select(
      "id, config, grader_repo, grader_commit_sha, latest_autograder_sha, max_submissions_count, max_submissions_period_secs"
    )
    .eq("id", assignmentId)
    .maybeSingle();
  if (error) throw new CLICommandError(`Failed to load autograder config: ${error.message}`, 500);
  if (!data) return 0;

  await writer.write({
    kind: "autograder",
    grader_repo: data.grader_repo,
    grader_commit_sha: data.grader_commit_sha,
    latest_autograder_sha: data.latest_autograder_sha,
    max_submissions_count: data.max_submissions_count,
    max_submissions_period_secs: data.max_submissions_period_secs
  });

  // The autograder config schema lives in PawtograderYml.d.ts but its shape
  // varies across versions. We pass through the test catalog verbatim if it
  // looks like a list of test specs; otherwise we just emit the raw config
  // so analysts can introspect and we don't lose data on schema drift.
  const config = data.config as Record<string, unknown> | null;
  if (config && Array.isArray((config as { tests?: unknown }).tests)) {
    const tests = (config as { tests: Array<Record<string, unknown>> }).tests;
    for (const t of tests) {
      await writer.write({
        kind: "autograder_test",
        name: t.name ?? null,
        part: t.part ?? null,
        max_score: t.max_score ?? null,
        is_released: t.is_released ?? null,
        // Pass through the rest so analysts have the full spec. Excluded from
        // the named columns above to keep this stable as the schema evolves.
        spec: t
      });
    }
    return tests.length;
  }
  await writer.write({ kind: "autograder_raw_config", config });
  return 0;
}

/**
 * Emit assignment_groups + members for group assignments. Group token is
 * derived from group.id; member references use subject tokens so analysts
 * can join groups → group members → subjects without a separate lookup.
 */
async function streamGroups(
  supabase: ReturnType<typeof getAdminClient>,
  assignmentId: number,
  classId: number,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  const { data: groups, error: gErr } = await supabase
    .from("assignment_groups")
    .select("id, name")
    .eq("assignment_id", assignmentId)
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (gErr) throw new CLICommandError(`Failed to load groups: ${gErr.message}`, 500);
  if (!groups || groups.length === 0) return 0;

  const groupIds = groups.map((g) => g.id);
  const { data: members, error: mErr } = await supabase
    .from("assignment_groups_members")
    .select("assignment_group_id, profile_id")
    .in("assignment_group_id", groupIds);
  if (mErr) throw new CLICommandError(`Failed to load group members: ${mErr.message}`, 500);

  const membersByGroup = new Map<number, string[]>();
  for (const m of members ?? []) {
    const list = membersByGroup.get(m.assignment_group_id) ?? [];
    list.push(m.profile_id);
    membersByGroup.set(m.assignment_group_id, list);
  }

  for (const g of groups) {
    const ref = tokenizer === null ? { id: g.id } : { token: await tokenizer.token("group", g.id) };
    const memberRefs = await Promise.all(
      (membersByGroup.get(g.id) ?? []).map(async (pid) =>
        tokenizer === null ? { id: pid } : { token: await tokenizer.token("subject", pid) }
      )
    );
    await writer.write({
      kind: "group",
      ...ref,
      // Group names are usually instructor-assigned ("Group 7") not PII; keep
      // them in raw form. If a course uses identifying group names this is
      // documented in the manifest's identity-mode notes for the analyst.
      name: g.name,
      members: memberRefs
    });
  }
  return groups.length;
}

/** Lightweight submission id list for sectioned/paginated export slices. */
async function loadSubmissionScope(
  supabase: ReturnType<typeof getAdminClient>,
  assignmentId: number,
  allSubmissions: boolean
): Promise<{ submissionIds: number[]; activeSubmissionIds: number[] }> {
  let cursor = 0;
  const submissionIds: number[] = [];
  const activeSubmissionIds: number[] = [];

  while (true) {
    let query = supabase
      .from("submissions")
      .select("id, is_active")
      .eq("assignment_id", assignmentId)
      .gt("id", cursor)
      .order("id", { ascending: true })
      .limit(FACT_PAGE_SIZE);
    if (!allSubmissions) query = query.eq("is_active", true);

    const { data: rows, error } = await query;
    if (error) throw new CLICommandError(`Failed to load submissions: ${error.message}`, 500);
    if (!rows || rows.length === 0) break;

    for (const row of rows) {
      submissionIds.push(row.id);
      if (row.is_active) activeSubmissionIds.push(row.id);
    }

    if (rows.length < FACT_PAGE_SIZE) break;
    cursor = rows[rows.length - 1]!.id;
  }

  return { submissionIds, activeSubmissionIds };
}

async function loadReviewScope(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[]
): Promise<{ reviewIds: number[]; reviewToSubmission: Map<number, number> }> {
  const submissionToReview = new Map<number, number>();
  for (const batch of chunked(submissionIds, 500)) {
    const { data, error } = await supabase.from("submissions").select("id, grading_review_id").in("id", batch);
    if (error) throw new CLICommandError(`Failed to load grading review ids: ${error.message}`, 500);
    for (const r of data ?? []) {
      if (r.grading_review_id !== null) submissionToReview.set(r.id, r.grading_review_id);
    }
  }
  const reviewIds = Array.from(submissionToReview.values());
  const reviewToSubmission = new Map<number, number>();
  for (const [subId, revId] of submissionToReview.entries()) reviewToSubmission.set(revId, subId);
  return { reviewIds, reviewToSubmission };
}

/**
 * Rubric check results from the final grading review of each is_active
 * submission. Spans three tables (general comments, file-line comments,
 * artifact comments) — they share the (submission_review_id, rubric_check_id,
 * points, target_student_profile_id) shape so we normalize them into one
 * "score" record kind with a `surface` discriminator.
 *
 * The grading-review filter happens in two steps:
 *   1. Look up submissions.grading_review_id for the is_active submission ids.
 *   2. Filter each comments table by submission_review_id IN (those ids) AND
 *      rubric_check_id IS NOT NULL (chat-only comments aren't scores).
 */
async function streamScores(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[],
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  if (submissionIds.length === 0) return 0;
  const { reviewIds, reviewToSubmission } = await loadReviewScope(supabase, submissionIds);
  if (reviewIds.length === 0) return 0;
  return streamScoresForReviews(supabase, reviewIds, reviewToSubmission, mode, tokenizer, writer);
}

async function streamScoresForReviews(
  supabase: ReturnType<typeof getAdminClient>,
  reviewIds: number[],
  reviewToSubmission: Map<number, number>,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  if (reviewIds.length === 0) return 0;

  let total = 0;
  total += await streamScoresFromTable(
    supabase,
    "submission_comments",
    reviewIds,
    reviewToSubmission,
    mode,
    tokenizer,
    writer,
    "submission"
  );
  total += await streamScoresFromTable(
    supabase,
    "submission_file_comments",
    reviewIds,
    reviewToSubmission,
    mode,
    tokenizer,
    writer,
    "file"
  );
  total += await streamScoresFromTable(
    supabase,
    "submission_artifact_comments",
    reviewIds,
    reviewToSubmission,
    mode,
    tokenizer,
    writer,
    "artifact"
  );
  return total;
}

async function streamScoresFromTable(
  supabase: ReturnType<typeof getAdminClient>,
  table: "submission_comments" | "submission_file_comments" | "submission_artifact_comments",
  reviewIds: number[],
  reviewToSubmission: Map<number, number>,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> },
  surface: "submission" | "file" | "artifact"
): Promise<number> {
  let total = 0;
  // submission_review_id IN list — Postgres handles up to ~32k values, but to
  // be safe we batch on the review-id side; pagination within a batch is by
  // primary key cursor.
  for (const batch of chunked(reviewIds, 500)) {
    let cursor = 0;
    while (true) {
      const { data: rows, error } = await supabase
        .from(table)
        .select(
          "id, submission_review_id, rubric_check_id, points, comment, target_student_profile_id, released, created_at, deleted_at"
        )
        .in("submission_review_id", batch)
        .not("rubric_check_id", "is", null)
        .is("deleted_at", null)
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load ${table}: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      for (const row of rows) {
        const submissionId = reviewToSubmission.get(row.submission_review_id!);
        if (submissionId === undefined) continue;

        const submissionRef =
          tokenizer === null ? { id: submissionId } : { token: await tokenizer.token("submission", submissionId) };
        const rubricCheckRef =
          tokenizer === null
            ? { id: row.rubric_check_id }
            : { token: await tokenizer.token("rubric_check", row.rubric_check_id!) };
        const targetSubject =
          row.target_student_profile_id === null
            ? null
            : tokenizer === null
              ? { id: row.target_student_profile_id }
              : { token: await tokenizer.token("subject", row.target_student_profile_id) };

        await writer.write({
          kind: "score",
          surface,
          submission: submissionRef,
          rubric_check: rubricCheckRef,
          target_subject: targetSubject,
          points: row.points,
          comment: row.comment,
          released: row.released,
          created_at: row.created_at
        });
        total += 1;
      }

      if (rows.length < FACT_PAGE_SIZE) break;
      cursor = rows[rows.length - 1]!.id;
    }
  }
  return total;
}

/**
 * grader_result_tests for the is_active submissions of this assignment. Each
 * row carries student_id XOR assignment_group_id (per the schema), preserving
 * the dual-nullability that captures whether a test scored an individual or
 * a group. Output is included only when with_test_output=true and is
 * truncated to test_output_max_bytes — single test outputs can be megabytes.
 *
 * The join goes through grader_results.submission_id rather than
 * grader_result_tests.submission_id directly. Both columns exist on the
 * schema, but the latter is a denormalization that seeded test data leaves
 * NULL; the canonical FK is grader_result_id → grader_results.id.
 */
async function streamGraderTests(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[],
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> },
  withOutput: boolean,
  outputMaxBytes: number
): Promise<{ testCount: number; graderTestIds: number[] }> {
  if (submissionIds.length === 0) return { testCount: 0, graderTestIds: [] };
  let total = 0;
  const graderTestIds: number[] = [];

  // Step 1: resolve submission_id → grader_result_id list. Most submissions
  // have a single grader_result; multi-attempt runs can have several.
  const graderResultIdToSubmission = new Map<number, number>();
  for (const batch of chunked(submissionIds, 500)) {
    const { data, error } = await supabase
      .from("grader_results")
      .select("id, submission_id")
      .in("submission_id", batch);
    if (error) throw new CLICommandError(`Failed to load grader_results: ${error.message}`, 500);
    for (const r of data ?? []) {
      if (r.submission_id !== null) graderResultIdToSubmission.set(r.id, r.submission_id);
    }
  }
  const graderResultIds = Array.from(graderResultIdToSubmission.keys());
  if (graderResultIds.length === 0) return { testCount: 0, graderTestIds };

  // Step 2: page through grader_result_tests for those grader_result_ids.
  for (const batch of chunked(graderResultIds, 500)) {
    let cursor = 0;
    while (true) {
      const { data: rows, error } = await supabase
        .from("grader_result_tests")
        .select(
          "id, grader_result_id, submission_id, student_id, assignment_group_id, name, part, score, max_score, is_released, name_format, output_format, extra_data" +
            (withOutput ? ", output" : "")
        )
        .in("grader_result_id", batch)
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load grader_result_tests: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      // The select string is built conditionally to include `output` only when
      // requested; PostgREST's typed select can't see through that string
      // concatenation, so we narrow to the row shape we actually requested.
      const typedRows = rows as unknown as Array<{
        id: number;
        grader_result_id: number;
        submission_id: number | null;
        student_id: string | null;
        assignment_group_id: number | null;
        name: string;
        part: string | null;
        score: number | null;
        max_score: number | null;
        is_released: boolean;
        name_format: string;
        output_format: string | null;
        extra_data: unknown;
        output?: string | null;
      }>;

      for (const row of typedRows) {
        // Resolve submission_id via grader_result_id (canonical FK), falling
        // back to the denormalized submission_id column when present.
        const resolvedSubmissionId = graderResultIdToSubmission.get(row.grader_result_id) ?? row.submission_id ?? null;
        const submissionRef =
          resolvedSubmissionId === null
            ? null
            : tokenizer === null
              ? { id: resolvedSubmissionId }
              : { token: await tokenizer.token("submission", resolvedSubmissionId) };
        const studentRef =
          row.student_id === null
            ? null
            : tokenizer === null
              ? { id: row.student_id }
              : { token: await tokenizer.token("subject", row.student_id) };
        const groupRef =
          row.assignment_group_id === null
            ? null
            : tokenizer === null
              ? { id: row.assignment_group_id }
              : { token: await tokenizer.token("group", row.assignment_group_id) };
        const testRef = tokenizer === null ? { id: row.id } : { token: await tokenizer.token("grader_test", row.id) };

        const record: Record<string, unknown> = {
          kind: "grader_test",
          ...testRef,
          submission: submissionRef,
          subject: studentRef,
          group: groupRef,
          name: row.name,
          part: row.part,
          score: row.score,
          max_score: row.max_score,
          is_released: row.is_released,
          name_format: row.name_format,
          output_format: row.output_format,
          extra_data: slimExtraDataForExport(row.extra_data)
        };

        if (withOutput) {
          const output = row.output ?? null;
          if (output === null) {
            record.output = null;
          } else if (output.length <= outputMaxBytes) {
            record.output = output;
            record.output_truncated = false;
          } else {
            record.output = output.slice(0, outputMaxBytes);
            record.output_truncated = true;
            record.output_full_bytes = output.length;
          }
        }

        await writer.write(record);
        graderTestIds.push(row.id);
        total += 1;
      }

      if (typedRows.length < FACT_PAGE_SIZE) break;
      cursor = typedRows[typedRows.length - 1]!.id;
    }
  }
  return { testCount: total, graderTestIds };
}

/**
 * grader_result_output rows with visibility=hidden for the given submissions.
 * Output text is path-sanitized (runner/repo prefixes before pawtograder-grading
 * become /anonymous), optionally trimmed to start at outputFromSentinel, then
 * truncated to outputMaxBytes.
 */
async function streamInstructorBuildOutput(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[],
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> },
  outputMaxBytes: number,
  outputFromSentinel: string | null
): Promise<number> {
  if (submissionIds.length === 0) return 0;
  let total = 0;

  const graderResultIdToSubmission = new Map<number, number>();
  for (const batch of chunked(submissionIds, 500)) {
    const { data, error } = await supabase
      .from("grader_results")
      .select("id, submission_id")
      .in("submission_id", batch);
    if (error) throw new CLICommandError(`Failed to load grader_results: ${error.message}`, 500);
    for (const r of data ?? []) {
      if (r.submission_id !== null) graderResultIdToSubmission.set(r.id, r.submission_id);
    }
  }
  const graderResultIds = Array.from(graderResultIdToSubmission.keys());
  if (graderResultIds.length === 0) return 0;

  for (const batch of chunked(graderResultIds, 500)) {
    let cursor = 0;
    while (true) {
      const { data: rows, error } = await supabase
        .from("grader_result_output")
        .select("id, grader_result_id, student_id, assignment_group_id, output, format, visibility")
        .in("grader_result_id", batch)
        .eq("visibility", "hidden")
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load grader_result_output: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      for (const row of rows) {
        const resolvedSubmissionId = graderResultIdToSubmission.get(row.grader_result_id) ?? null;
        const submissionRef =
          resolvedSubmissionId === null
            ? null
            : tokenizer === null
              ? { id: resolvedSubmissionId }
              : { token: await tokenizer.token("submission", resolvedSubmissionId) };
        const studentRef =
          row.student_id === null
            ? null
            : tokenizer === null
              ? { id: row.student_id }
              : { token: await tokenizer.token("subject", row.student_id) };
        const groupRef =
          row.assignment_group_id === null
            ? null
            : tokenizer === null
              ? { id: row.assignment_group_id }
              : { token: await tokenizer.token("group", row.assignment_group_id) };

        const prepared = prepareInstructorBuildOutput(row.output, { sentinel: outputFromSentinel });
        if (prepared === null) continue;

        const record: Record<string, unknown> = {
          kind: "instructor_build_output",
          submission: submissionRef,
          subject: studentRef,
          group: groupRef,
          format: row.format,
          visibility: row.visibility
        };

        if (prepared.length <= outputMaxBytes) {
          record.output = prepared;
          record.output_truncated = false;
        } else {
          record.output = prepared.slice(0, outputMaxBytes);
          record.output_truncated = true;
          record.output_full_bytes = prepared.length;
        }

        await writer.write(record);
        total += 1;
      }

      if (rows.length < FACT_PAGE_SIZE) break;
      cursor = rows[rows.length - 1]!.id;
    }
  }
  return total;
}

/**
 * Feedbot / hint export for an assignment. Two sources:
 *   - feedback: student ratings in grader_result_tests_hint_feedback
 *   - llm: cached Feedbot responses on grader_result_tests.extra_data.llm.result
 *
 * Feedback rows carry rater/useful/comment; LLM rows carry the subject who
 * received the hint. When a student rated a hint we skip the duplicate LLM row
 * for that (grader_test, subject) pair.
 */
async function streamHints(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[],
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  if (submissionIds.length === 0) return 0;
  let total = 0;
  const feedbackKeys = new Set<string>();

  for (const batch of chunked(submissionIds, 500)) {
    let cursor = 0;
    while (true) {
      const { data: rows, error } = await supabase
        .from("grader_result_tests_hint_feedback")
        .select("id, submission_id, grader_result_tests_id, hint, useful, comment, created_by, created_at")
        .in("submission_id", batch)
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load hint feedback: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      for (const row of rows) {
        feedbackKeys.add(compoundKey(row.grader_result_tests_id, row.created_by));
        const submissionRef =
          tokenizer === null
            ? { id: row.submission_id }
            : { token: await tokenizer.token("submission", row.submission_id) };
        const graderTestRef =
          tokenizer === null
            ? { id: row.grader_result_tests_id }
            : { token: await tokenizer.token("grader_test", row.grader_result_tests_id) };
        const raterRef =
          tokenizer === null ? { id: row.created_by } : { token: await tokenizer.token("subject", row.created_by) };

        await writer.write({
          kind: "hint",
          source: "feedback",
          submission: submissionRef,
          grader_test: graderTestRef,
          rater: raterRef,
          hint: row.hint,
          useful: row.useful,
          comment: row.comment,
          created_at: row.created_at
        });
        total += 1;
      }

      if (rows.length < FACT_PAGE_SIZE) break;
      cursor = rows[rows.length - 1]!.id;
    }
  }

  for (const batch of chunked(submissionIds, 500)) {
    const graderResultIdToSubmission = new Map<number, number>();
    const { data: graderResults, error: grErr } = await supabase
      .from("grader_results")
      .select("id, submission_id")
      .in("submission_id", batch);
    if (grErr) throw new CLICommandError(`Failed to load grader_results for hints: ${grErr.message}`, 500);
    for (const r of graderResults ?? []) {
      if (r.submission_id !== null) graderResultIdToSubmission.set(r.id, r.submission_id);
    }
    const graderResultIds = Array.from(graderResultIdToSubmission.keys());
    if (graderResultIds.length === 0) continue;

    for (const grBatch of chunked(graderResultIds, 500)) {
      let cursor = 0;
      while (true) {
        const { data: rows, error } = await supabase
          .from("grader_result_tests")
          .select("id, grader_result_id, submission_id, student_id, extra_data")
          .in("grader_result_id", grBatch)
          .not("extra_data->llm->>result", "is", null)
          .gt("id", cursor)
          .order("id", { ascending: true })
          .limit(FACT_PAGE_SIZE);
        if (error) throw new CLICommandError(`Failed to load LLM hints: ${error.message}`, 500);
        if (!rows || rows.length === 0) break;

        for (const row of rows) {
          const extra = row.extra_data as { llm?: { result?: string } } | null;
          const hintText = extra?.llm?.result?.trim();
          if (!hintText) continue;
          if (row.student_id !== null && feedbackKeys.has(compoundKey(row.id, row.student_id))) continue;

          const resolvedSubmissionId =
            graderResultIdToSubmission.get(row.grader_result_id) ?? row.submission_id ?? null;
          const submissionRef =
            resolvedSubmissionId === null
              ? null
              : tokenizer === null
                ? { id: resolvedSubmissionId }
                : { token: await tokenizer.token("submission", resolvedSubmissionId) };
          const graderTestRef =
            tokenizer === null ? { id: row.id } : { token: await tokenizer.token("grader_test", row.id) };
          const subjectRef =
            row.student_id === null
              ? null
              : tokenizer === null
                ? { id: row.student_id }
                : { token: await tokenizer.token("subject", row.student_id) };

          await writer.write({
            kind: "hint",
            source: "llm",
            submission: submissionRef,
            grader_test: graderTestRef,
            subject: subjectRef,
            hint: hintText
          });
          total += 1;
        }

        if (rows.length < FACT_PAGE_SIZE) break;
        cursor = rows[rows.length - 1]!.id;
      }
    }
  }

  return total;
}

/**
 * Student engagement with discussion posts pinned to errors on exported
 * submissions. Emits one row per submission × pinned discussion post × student
 * participant so group submissions retain per-student read/like state.
 */
async function streamErrorPinEngagement(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  submissionIds: number[],
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  if (submissionIds.length === 0) return 0;

  const participants = await loadSubmissionParticipants(supabase, classId, submissionIds);
  const matches = await loadErrorPinMatches(supabase, submissionIds);
  if (matches.length === 0) return 0;

  const discussionThreadIds = unique(matches.map((m) => m.discussion_thread_id));
  const profileIds = unique(Array.from(participants.values()).flatMap((profiles) => Array.from(profiles)));
  const userIdByProfileId = await loadUserIdsByProfileId(supabase, classId, profileIds);
  const readAtByUserAndThread = await loadReadStatusByUserAndThread(
    supabase,
    discussionThreadIds,
    unique(Array.from(userIdByProfileId.values()))
  );
  const likedByProfileAndThread = await loadLikesByProfileAndThread(supabase, discussionThreadIds, profileIds);

  let total = 0;
  for (const match of matches) {
    const submissionParticipants = participants.get(match.submission_id) ?? new Set<string>();
    for (const profileId of submissionParticipants) {
      const userId = userIdByProfileId.get(profileId) ?? null;
      const submissionRef =
        tokenizer === null
          ? { id: match.submission_id }
          : { token: await tokenizer.token("submission", match.submission_id) };
      const subjectRef =
        tokenizer === null ? { id: profileId } : { token: await tokenizer.token("subject", profileId) };
      const graderTestRef =
        match.grader_result_test_id === null
          ? null
          : tokenizer === null
            ? { id: match.grader_result_test_id }
            : { token: await tokenizer.token("grader_test", match.grader_result_test_id) };

      await writer.write({
        kind: "error_pin_engagement",
        submission: submissionRef,
        subject: subjectRef,
        discussion_thread_id: match.discussion_thread_id,
        error_pin_id: match.error_pin_id,
        grader_test: graderTestRef,
        read_at:
          userId === null ? null : (readAtByUserAndThread.get(compoundKey(userId, match.discussion_thread_id)) ?? null),
        liked: likedByProfileAndThread.has(compoundKey(profileId, match.discussion_thread_id))
      });
      total += 1;
    }
  }
  return total;
}

async function loadSubmissionParticipants(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  submissionIds: number[]
): Promise<Map<number, Set<string>>> {
  const participants = new Map<number, Set<string>>();
  const groupIdsBySubmissionId = new Map<number, number>();

  for (const batch of chunked(submissionIds, 500)) {
    const { data, error } = await supabase
      .from("submissions")
      .select("id, profile_id, assignment_group_id")
      .in("id", batch);
    if (error) throw new CLICommandError(`Failed to load submission participants: ${error.message}`, 500);

    for (const row of data ?? []) {
      const profiles = participants.get(row.id) ?? new Set<string>();
      if (row.profile_id !== null) profiles.add(row.profile_id);
      if (row.assignment_group_id !== null) groupIdsBySubmissionId.set(row.id, row.assignment_group_id);
      participants.set(row.id, profiles);
    }
  }

  const groupIds = unique(Array.from(groupIdsBySubmissionId.values()));
  const membersByGroupId = new Map<number, string[]>();
  for (const batch of chunked(groupIds, 500)) {
    const { data, error } = await supabase
      .from("assignment_groups_members")
      .select("assignment_group_id, profile_id")
      .in("assignment_group_id", batch);
    if (error) throw new CLICommandError(`Failed to load assignment group members: ${error.message}`, 500);
    for (const row of data ?? []) {
      const profiles = membersByGroupId.get(row.assignment_group_id) ?? [];
      profiles.push(row.profile_id);
      membersByGroupId.set(row.assignment_group_id, profiles);
    }
  }

  for (const [submissionId, groupId] of groupIdsBySubmissionId.entries()) {
    const profiles = participants.get(submissionId) ?? new Set<string>();
    for (const profileId of membersByGroupId.get(groupId) ?? []) profiles.add(profileId);
    participants.set(submissionId, profiles);
  }

  const profileIds = unique(Array.from(participants.values()).flatMap((profiles) => Array.from(profiles)));
  const enrolledProfiles = new Set((await loadUserIdsByProfileId(supabase, classId, profileIds)).keys());
  for (const [submissionId, profiles] of participants.entries()) {
    participants.set(
      submissionId,
      new Set(Array.from(profiles).filter((profileId) => enrolledProfiles.has(profileId)))
    );
  }

  return participants;
}

type ErrorPinMatchForExport = {
  error_pin_id: number;
  submission_id: number;
  grader_result_test_id: number | null;
  discussion_thread_id: number;
};

async function loadErrorPinMatches(
  supabase: ReturnType<typeof getAdminClient>,
  submissionIds: number[]
): Promise<ErrorPinMatchForExport[]> {
  const rawMatches: Array<Omit<ErrorPinMatchForExport, "discussion_thread_id">> = [];

  for (const batch of chunked(submissionIds, 500)) {
    let cursor = 0;
    while (true) {
      const { data, error } = await supabase
        .from("error_pin_submission_matches")
        .select("id, error_pin_id, submission_id, grader_result_test_id")
        .in("submission_id", batch)
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load error pin matches: ${error.message}`, 500);
      if (!data || data.length === 0) break;

      for (const row of data) {
        rawMatches.push({
          error_pin_id: row.error_pin_id,
          submission_id: row.submission_id,
          grader_result_test_id: row.grader_result_test_id
        });
      }

      if (data.length < FACT_PAGE_SIZE) break;
      cursor = data[data.length - 1]!.id;
    }
  }

  if (rawMatches.length === 0) return [];

  const pinById = new Map<number, { discussion_thread_id: number }>();
  for (const batch of chunked(unique(rawMatches.map((m) => m.error_pin_id)), 500)) {
    const { data, error } = await supabase
      .from("error_pins")
      .select("id, discussion_thread_id")
      .eq("enabled", true)
      .in("id", batch);
    if (error) throw new CLICommandError(`Failed to load error pins: ${error.message}`, 500);
    for (const pin of data ?? []) {
      pinById.set(pin.id, { discussion_thread_id: pin.discussion_thread_id });
    }
  }

  return rawMatches.flatMap((match) => {
    const pin = pinById.get(match.error_pin_id);
    return pin ? [{ ...match, discussion_thread_id: pin.discussion_thread_id }] : [];
  });
}

async function loadUserIdsByProfileId(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  profileIds: string[]
): Promise<Map<string, string>> {
  const wanted = new Set(profileIds);
  const userIdByProfileId = new Map<string, string>();
  if (wanted.size === 0) return userIdByProfileId;

  // Page through enrolled students for the class instead of a giant
  // private_profile_id=in.(...) filter — long UUID lists blow past HTTP URL limits.
  let cursor: string | null = null;
  while (true) {
    let query = supabase
      .from("user_roles")
      .select("private_profile_id, user_id")
      .eq("class_id", classId)
      .eq("role", "student")
      .eq("disabled", false)
      .order("private_profile_id", { ascending: true })
      .limit(STUDENT_PAGE_SIZE);

    if (cursor !== null) query = query.gt("private_profile_id", cursor);

    const { data, error } = await query;
    if (error) throw new CLICommandError(`Failed to load student user ids: ${error.message}`, 500);
    if (!data || data.length === 0) break;

    for (const row of data) {
      if (row.private_profile_id !== null && wanted.has(row.private_profile_id)) {
        userIdByProfileId.set(row.private_profile_id, row.user_id);
      }
    }

    if (userIdByProfileId.size === wanted.size) break;
    if (data.length < STUDENT_PAGE_SIZE) break;
    cursor = data[data.length - 1]!.private_profile_id;
  }
  return userIdByProfileId;
}

async function loadReadStatusByUserAndThread(
  supabase: ReturnType<typeof getAdminClient>,
  discussionThreadIds: number[],
  userIds: string[]
): Promise<Map<string, string | null>> {
  const readAtByUserAndThread = new Map<string, string | null>();
  for (const threadBatch of chunked(discussionThreadIds, 200)) {
    for (const userBatch of chunked(userIds, UUID_IN_BATCH_SIZE)) {
      const { data, error } = await supabase
        .from("discussion_thread_read_status")
        .select("user_id, discussion_thread_id, read_at")
        .in("discussion_thread_id", threadBatch)
        .in("user_id", userBatch);
      if (error) throw new CLICommandError(`Failed to load discussion read status: ${error.message}`, 500);
      for (const row of data ?? []) {
        readAtByUserAndThread.set(compoundKey(row.user_id, row.discussion_thread_id), row.read_at);
      }
    }
  }
  return readAtByUserAndThread;
}

async function loadLikesByProfileAndThread(
  supabase: ReturnType<typeof getAdminClient>,
  discussionThreadIds: number[],
  profileIds: string[]
): Promise<Set<string>> {
  const likedByProfileAndThread = new Set<string>();
  for (const threadBatch of chunked(discussionThreadIds, 200)) {
    for (const profileBatch of chunked(profileIds, UUID_IN_BATCH_SIZE)) {
      const { data, error } = await supabase
        .from("discussion_thread_likes")
        .select("creator, discussion_thread")
        .in("discussion_thread", threadBatch)
        .in("creator", profileBatch);
      if (error) throw new CLICommandError(`Failed to load discussion likes: ${error.message}`, 500);
      for (const row of data ?? []) {
        likedByProfileAndThread.add(compoundKey(row.creator, row.discussion_thread));
      }
    }
  }
  return likedByProfileAndThread;
}

function unique<T>(values: T[]): T[] {
  return Array.from(new Set(values));
}

function compoundKey(left: string | number, right: string | number): string {
  return `${left}:${right}`;
}

function* chunked<T>(arr: T[], size: number): Generator<T[]> {
  for (let i = 0; i < arr.length; i += size) yield arr.slice(i, i + size);
}

registerCommand({
  name: "assessment.export.preamble",
  requiredScope: "cli:read",
  stream: true,
  handler: handlePreamble
});

interface GradebookExportParams {
  class?: string | number;
  identity_mode?: IdentityMode;
  salt?: string;
  confirm_pii?: boolean;
  /** Optional column selectors. If omitted, all columns' private cells are streamed. */
  gradebook_columns?: Array<string | number>;
}

/**
 * Streams instructor-side gradebook cells for the class. Per the design
 * decision: only is_private = true rows are emitted (those are the
 * instructor-owned values, which are what an instructor analysis cares
 * about), and instructor_only columns are always included regardless of
 * selectors.
 */
async function handleGradebookExport(ctx: MCPAuthContext, rawParams: Record<string, unknown>): Promise<Response> {
  const params = rawParams as unknown as GradebookExportParams;
  const classIdentifier = params.class;
  const mode = validateExportIdentityParams(params);

  if (!classIdentifier) throw new CLICommandError("class is required");

  const supabase = getAdminClient();
  const classData = await resolveClass(supabase, classIdentifier);
  await assertUserCanAccessClass(supabase, ctx.userId, classData.id);

  const tokenizer = mode === "raw" ? null : await createExportTokenizer(supabase, params.salt!);

  return streamNdjson(async (writer) => {
    await writer.write({
      kind: "manifest",
      schema_version: SCHEMA_VERSION,
      identity_mode: mode,
      class: { id: classData.id, slug: classData.slug }
    });

    const { data: cols, error: colErr } = await supabase
      .from("gradebook_columns")
      .select("id, slug")
      .eq("class_id", classData.id);
    if (colErr) throw new CLICommandError(`Failed to load gradebook columns: ${colErr.message}`, 500);

    const candidates = (cols ?? []).map((c) => ({ id: c.id, slug: c.slug }));
    const { resolved, unmatched } = resolveSelectors(params.gradebook_columns, candidates);

    // Same warning contract as the preamble: typoed or wholly-redundant
    // selectors surface as a {kind:"warning"} record rather than silently
    // producing an empty/partial stream. This handler is independently
    // dispatchable, so it can't rely on the preamble having warned first.
    if (unmatched.length > 0) {
      await writer.write({
        kind: "warning",
        scope: "gradebook_columns",
        message: `${unmatched.length} gradebook column selector(s) matched nothing`,
        selectors: unmatched
      });
    }

    const columnIds = new Set(resolved.map((c) => c.id));
    if (columnIds.size === 0) {
      await writer.write({ kind: "end", counts: { gradebook_scores: 0 } });
      return;
    }

    let cursor = 0;
    let total = 0;
    while (true) {
      const { data: rows, error } = await supabase
        .from("gradebook_column_students")
        .select(
          "id, gradebook_column_id, student_id, score, score_override, score_override_note, is_excused, is_missing, is_droppable, released, incomplete_values, is_private"
        )
        .eq("class_id", classData.id)
        .eq("is_private", true)
        .in("gradebook_column_id", Array.from(columnIds))
        .gt("id", cursor)
        .order("id", { ascending: true })
        .limit(FACT_PAGE_SIZE);
      if (error) throw new CLICommandError(`Failed to load gradebook scores: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      for (const row of rows) {
        const subjectRef =
          tokenizer === null ? { id: row.student_id } : { token: await tokenizer.token("subject", row.student_id) };
        // Gradebook columns aren't PII (the slug is course design metadata)
        // and `gradebook-columns.json` always emits raw {id, slug, name, ...},
        // so scores reference columns by id too — joining the two files is a
        // direct id match without a tokenization detour.

        await writer.write({
          kind: "gradebook_score",
          subject: subjectRef,
          column: { id: row.gradebook_column_id },
          score: row.score,
          score_override: row.score_override,
          score_override_note: row.score_override_note,
          is_excused: row.is_excused,
          is_missing: row.is_missing,
          is_droppable: row.is_droppable,
          released: row.released,
          incomplete_values: row.incomplete_values
        });
        total += 1;
      }

      if (rows.length < FACT_PAGE_SIZE) break;
      cursor = rows[rows.length - 1]!.id;
    }

    await writer.write({ kind: "end", counts: { gradebook_scores: total } });
  });
}

registerCommand({
  name: "assessment.export.assignment",
  requiredScope: "cli:read",
  stream: true,
  handler: handleAssignmentExport
});

registerCommand({
  name: "assessment.export.gradebook",
  requiredScope: "cli:read",
  stream: true,
  handler: handleGradebookExport
});

// ---------------------------------------------------------------------------
// assessment.export.roster — deanonymize: map subject tokens → student PII
// ---------------------------------------------------------------------------

interface RosterParams {
  class?: string | number;
  /** Must be "hash" — opaque tokens are per-run and unreproducible; raw has no tokens. */
  identity_mode?: string;
  salt?: string;
  /** Required — explicit PII acknowledgement. */
  confirm_pii?: boolean;
}

/**
 * Stream one {kind:"roster_row"} per enrolled student, pairing the subject
 * token (computed from the same salt as the export run) with the student's
 * real identifiers: name, email, SIS user id, class section name, and lab
 * section name.
 *
 * Only hash mode is supported. Opaque tokens use a per-run client salt plus the
 * server vault pepper and cannot be reproduced after the fact; raw exports have
 * no tokens to map back from.
 */
async function handleRoster(ctx: MCPAuthContext, rawParams: Record<string, unknown>): Promise<Response> {
  const params = rawParams as unknown as RosterParams;
  const classIdentifier = params.class;
  const mode = params.identity_mode;

  if (!classIdentifier) throw new CLICommandError("class is required");
  if (mode !== "hash") {
    throw new CLICommandError(
      'identity_mode must be "hash" — opaque tokens are per-run and cannot be reproduced; use the same salt as the original export run'
    );
  }
  if (params.confirm_pii !== true) {
    throw new CLICommandError(
      "assessment.export.roster exposes real student names, emails, and SIS ids. Re-run with confirm_pii: true to acknowledge.",
      400
    );
  }
  if (!params.salt || typeof params.salt !== "string") {
    throw new CLICommandError("salt is required for identity_mode=hash");
  }
  if (params.salt.length < 16) {
    throw new CLICommandError("salt must be at least 16 characters");
  }

  const supabase = getAdminClient();
  const classData = await resolveClass(supabase, classIdentifier);
  await assertUserCanAccessClass(supabase, ctx.userId, classData.id);

  const tokenizer = await createExportTokenizer(supabase, params.salt);

  // Pre-fetch section name maps so per-student rows don't need individual lookups.
  const { data: classSectionRows, error: csErr } = await supabase
    .from("class_sections")
    .select("id, name")
    .eq("class_id", classData.id);
  if (csErr) throw new CLICommandError(`Failed to load class sections: ${csErr.message}`, 500);
  const classSectionNames = new Map<number, string>((classSectionRows ?? []).map((s) => [s.id, s.name ?? ""]));

  const { data: labSectionRows, error: lsErr } = await supabase
    .from("lab_sections")
    .select("id, name")
    .eq("class_id", classData.id);
  if (lsErr) throw new CLICommandError(`Failed to load lab sections: ${lsErr.message}`, 500);
  const labSectionNames = new Map<number, string>((labSectionRows ?? []).map((s) => [s.id, s.name ?? ""]));

  return streamNdjson(async (writer) => {
    let cursor: string | null = null;
    let total = 0;

    while (true) {
      let query = supabase
        .from("user_roles")
        .select(
          "private_profile_id, class_section_id, lab_section_id, profiles!user_roles_private_profile_id_fkey(name), users(email, sis_user_id)"
        )
        .eq("class_id", classData.id)
        .eq("disabled", false)
        .eq("role", "student")
        .order("private_profile_id", { ascending: true })
        .limit(STUDENT_PAGE_SIZE);

      if (cursor !== null) query = query.gt("private_profile_id", cursor);

      const { data: rows, error } = await query;
      if (error) throw new CLICommandError(`Failed to load students: ${error.message}`, 500);
      if (!rows || rows.length === 0) break;

      for (const row of rows) {
        const token = await tokenizer.token("subject", row.private_profile_id);
        const profile = Array.isArray(row.profiles) ? row.profiles[0] : row.profiles;
        const u = Array.isArray(row.users) ? row.users[0] : row.users;
        await writer.write({
          kind: "roster_row",
          token,
          name: profile?.name ?? null,
          email: u?.email ?? null,
          sis_user_id: u?.sis_user_id ?? null,
          class_section: row.class_section_id !== null ? (classSectionNames.get(row.class_section_id) ?? null) : null,
          lab_section: row.lab_section_id !== null ? (labSectionNames.get(row.lab_section_id) ?? null) : null
        });
        total += 1;
      }

      if (rows.length < STUDENT_PAGE_SIZE) break;
      cursor = rows[rows.length - 1]!.private_profile_id;
    }

    await writer.write({ kind: "end", counts: { rows: total } });
  });
}

registerCommand({
  name: "assessment.export.roster",
  requiredScope: "cli:read",
  stream: true,
  handler: handleRoster
});
