/**
 * Assessment export — streams a privacy-controlled snapshot of rubrics, final
 * grading review scores, autograder test results, hint feedback, and
 * gradebook columns for a class.
 *
 * Architecture (see /docs design discussion):
 *   - One CLI run = one random salt held only by the CLI.
 *   - The CLI fans out parallel calls keyed on assignment_slug. Each call
 *     constructs its own tokenizer using the same salt, so tokens for the
 *     same raw id agree across calls and can be joined on the analyst side.
 *   - First call: assessment.export.preamble emits manifest, students, and
 *     sections (the thin slice this file currently implements).
 *   - Subsequent calls (future tasks): assessment.export.assignment streams
 *     per-assignment rubric, autograder, scores, tests, hints; and
 *     assessment.export.gradebook streams gradebook columns + private cells.
 *
 * Identity modes:
 *   - "raw"    — emit real ids/emails/names. Requires confirm_pii: true.
 *   - "hash"   — HMAC of id with caller-supplied salt; joinable across runs.
 *   - "opaque" — HMAC with caller-generated random salt; intra-run only.
 */

import type { MCPAuthContext } from "../../_shared/MCPAuth.ts";
import { registerCommand } from "../router.ts";
import { CLICommandError } from "../errors.ts";
import { getAdminClient } from "../utils/supabase.ts";
import { resolveClass } from "../utils/resolvers.ts";
import { assertUserCanAccessClass } from "../utils/auth.ts";
import { streamNdjson } from "../utils/ndjson.ts";
import {
  createTokenizer,
  type IdentityMode,
  type Tokenizer
} from "../utils/tokenization.ts";

const SCHEMA_VERSION = 1;
const STUDENT_PAGE_SIZE = 500;

interface PreambleParams {
  class?: string | number;
  identity_mode?: IdentityMode;
  salt?: string;
  /** Required when identity_mode === "raw" — explicit acknowledgement. */
  confirm_pii?: boolean;
  /** UUID generated by the CLI per run. Echoed in the manifest for traceability. */
  dump_id?: string;
}

async function handlePreamble(ctx: MCPAuthContext, rawParams: Record<string, unknown>): Promise<Response> {
  const params = rawParams as unknown as PreambleParams;
  const classIdentifier = params.class;
  const mode: IdentityMode = params.identity_mode ?? "opaque";
  const dumpId = params.dump_id ?? crypto.randomUUID();

  if (!classIdentifier) throw new CLICommandError("class is required");
  if (mode !== "raw" && mode !== "hash" && mode !== "opaque") {
    throw new CLICommandError(`invalid identity_mode: ${String(mode)}`);
  }
  if (mode === "raw" && params.confirm_pii !== true) {
    throw new CLICommandError(
      "identity_mode=raw exposes real student ids, emails, and names. Re-run with confirm_pii: true to acknowledge.",
      400
    );
  }
  if (mode === "hash" || mode === "opaque") {
    if (!params.salt || typeof params.salt !== "string") {
      throw new CLICommandError(`identity_mode=${mode} requires a salt`);
    }
    // Mirror createTokenizer's contract here so a too-short salt surfaces as
    // a 400 validation error instead of a generic 500 from inside the
    // tokenizer constructor.
    if (params.salt.length < 16) {
      throw new CLICommandError(`identity_mode=${mode} requires a salt of at least 16 characters`);
    }
  }

  const supabase = getAdminClient();
  const classData = await resolveClass(supabase, classIdentifier);
  await assertUserCanAccessClass(supabase, ctx.userId, classData.id);

  const tokenizer = mode === "raw" ? null : await createTokenizer(params.salt!);

  return streamNdjson(async (writer) => {
    let subjectCount = 0;
    let sectionCount = 0;

    await writer.write({
      kind: "manifest",
      schema_version: SCHEMA_VERSION,
      dump_id: dumpId,
      identity_mode: mode,
      exported_at: new Date().toISOString(),
      class: { id: classData.id, slug: classData.slug, name: classData.name }
    });

    subjectCount = await streamStudents(supabase, classData.id, mode, tokenizer, writer);
    sectionCount = await streamSections(supabase, classData.id, mode, tokenizer, writer);

    await writer.write({
      kind: "end",
      counts: { subjects: subjectCount, sections: sectionCount }
    });
  });
}

/**
 * Page through students in the class and emit one {kind:"subject"} record per
 * student. Pagination is by user_id ordering, NOT by OFFSET, so a class with
 * 1000 students still completes in O(1) DB cursors regardless of page size.
 */
async function streamStudents(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  let cursor: string | null = null;
  let total = 0;

  while (true) {
    let query = supabase
      .from("user_roles")
      .select("user_id, class_section_id, lab_section_id, private_profile_id, public_profile_id")
      .eq("class_id", classId)
      .eq("disabled", false)
      .eq("role", "student")
      .order("user_id", { ascending: true })
      .limit(STUDENT_PAGE_SIZE);

    if (cursor !== null) query = query.gt("user_id", cursor);

    const { data: rows, error } = await query;
    if (error) throw new CLICommandError(`Failed to load students: ${error.message}`, 500);
    if (!rows || rows.length === 0) break;

    // For raw mode, join users to surface email/name. We do this per-page in
    // a single roundtrip rather than nesting in the user_roles select to keep
    // the query plan simple and avoid PostgREST's nested-select overhead.
    let userInfo: Map<string, { email: string | null; name: string | null }> | null = null;
    if (mode === "raw") {
      const userIds = rows.map((r) => r.user_id);
      const { data: userRows, error: userErr } = await supabase
        .from("users")
        .select("user_id, email, name")
        .in("user_id", userIds);
      if (userErr) throw new CLICommandError(`Failed to load user emails: ${userErr.message}`, 500);
      userInfo = new Map((userRows ?? []).map((u) => [u.user_id, { email: u.email, name: u.name }]));
    }

    for (const row of rows) {
      const subjectRef =
        tokenizer === null
          ? { id: row.user_id }
          : { token: await tokenizer.token("subject", row.user_id) };

      const classSectionRef =
        row.class_section_id === null
          ? null
          : tokenizer === null
            ? { id: row.class_section_id }
            : { token: await tokenizer.token("section_class", row.class_section_id) };

      const labSectionRef =
        row.lab_section_id === null
          ? null
          : tokenizer === null
            ? { id: row.lab_section_id }
            : { token: await tokenizer.token("section_lab", row.lab_section_id) };

      const record: Record<string, unknown> = {
        kind: "subject",
        subject_kind: "student",
        ...subjectRef,
        class_section: classSectionRef,
        lab_section: labSectionRef
      };

      if (mode === "raw") {
        const info = userInfo!.get(row.user_id);
        record.email = info?.email ?? null;
        record.name = info?.name ?? null;
      }

      await writer.write(record);
      total += 1;
    }

    if (rows.length < STUDENT_PAGE_SIZE) break;
    cursor = rows[rows.length - 1]!.user_id;
  }

  return total;
}

/**
 * Class and lab sections in the class. Section names are passed through
 * verbatim — they are usually what instructors want for analysis. The risk
 * (section names can re-identify students in small labs) is documented in
 * the manifest and surfaced to the CLI user; this function does not redact.
 */
async function streamSections(
  supabase: ReturnType<typeof getAdminClient>,
  classId: number,
  mode: IdentityMode,
  tokenizer: Tokenizer | null,
  writer: { write: (record: Record<string, unknown>) => Promise<void> }
): Promise<number> {
  let total = 0;

  const { data: classSections, error: csErr } = await supabase
    .from("class_sections")
    .select("id, name, meeting_times, meeting_location, campus")
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (csErr) throw new CLICommandError(`Failed to load class sections: ${csErr.message}`, 500);

  for (const sec of classSections ?? []) {
    const ref = tokenizer === null ? { id: sec.id } : { token: await tokenizer.token("section_class", sec.id) };
    await writer.write({
      kind: "section",
      section_kind: "class",
      ...ref,
      name: sec.name,
      meeting_times: sec.meeting_times,
      meeting_location: sec.meeting_location,
      campus: sec.campus
    });
    total += 1;
  }

  const { data: labSections, error: lsErr } = await supabase
    .from("lab_sections")
    .select("id, name, meeting_times, meeting_location, campus, day_of_week, start_time, end_time")
    .eq("class_id", classId)
    .order("id", { ascending: true });
  if (lsErr) throw new CLICommandError(`Failed to load lab sections: ${lsErr.message}`, 500);

  for (const sec of labSections ?? []) {
    const ref = tokenizer === null ? { id: sec.id } : { token: await tokenizer.token("section_lab", sec.id) };
    await writer.write({
      kind: "section",
      section_kind: "lab",
      ...ref,
      name: sec.name,
      meeting_times: sec.meeting_times,
      meeting_location: sec.meeting_location,
      campus: sec.campus,
      day_of_week: sec.day_of_week,
      start_time: sec.start_time,
      end_time: sec.end_time
    });
    total += 1;
  }

  return total;
}

registerCommand({
  name: "assessment.export.preamble",
  requiredScope: "cli:read",
  stream: true,
  handler: handlePreamble
});
