-- Create assignment_leaderboard table
-- Stores one row per student per assignment with their autograder score
-- Uses public_profile_id for pseudonymity

CREATE TABLE IF NOT EXISTS public.assignment_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    assignment_id BIGINT NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    -- Use public_profile_id for pseudonymity on the leaderboard
    public_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    -- Autograder score from the active submission
    autograder_score INTEGER NOT NULL DEFAULT 0,
    max_score INTEGER NOT NULL DEFAULT 100,
    -- Submission metadata
    submission_id BIGINT REFERENCES public.submissions(id) ON DELETE SET NULL,
    -- Unique constraint: one entry per student per assignment (using public_profile_id)
    CONSTRAINT unique_student_assignment UNIQUE (assignment_id, public_profile_id),
    CONSTRAINT check_score_non_negative CHECK (autograder_score >= 0),
    CONSTRAINT check_score_bounds CHECK (autograder_score <= max_score),
    CONSTRAINT check_max_score_positive CHECK (max_score > 0)
);

-- Create indexes for efficient queries
CREATE INDEX idx_leaderboard_assignment_score ON public.assignment_leaderboard (assignment_id, autograder_score DESC);
CREATE INDEX idx_leaderboard_class_id ON public.assignment_leaderboard (class_id);
CREATE INDEX idx_leaderboard_public_profile ON public.assignment_leaderboard (public_profile_id);

-- Enable RLS
ALTER TABLE public.assignment_leaderboard ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view leaderboard entries for assignments in their class
CREATE POLICY "Users can view leaderboard in their class"
ON public.assignment_leaderboard
FOR SELECT
USING (
    -- Allow anonymous users to view all leaderboard entries
    auth.uid() IS NULL
    OR
    -- Authenticated users can only view leaderboard for their classes
    EXISTS (
        SELECT 1 FROM public.user_roles ur
        WHERE ur.user_id = auth.uid()
        AND ur.class_id = assignment_leaderboard.class_id
    )
);

-- Grant permissions
GRANT SELECT ON public.assignment_leaderboard TO authenticated;
GRANT SELECT ON public.assignment_leaderboard TO anon;

-- Function to update leaderboard when grader_results change
CREATE OR REPLACE FUNCTION public.update_assignment_leaderboard()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
    v_submission RECORD;
    v_user_role RECORD;
    v_active_submission RECORD;
    v_max_score INTEGER;
BEGIN
    -- Get submission details
    SELECT s.*, a.autograder_points
    INTO v_submission
    FROM public.submissions s
    INNER JOIN public.assignments a ON a.id = s.assignment_id
    WHERE s.id = NEW.submission_id;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    -- Only update leaderboard for active submissions
    IF v_submission.is_active IS NOT TRUE THEN
        RETURN NEW;
    END IF;

    -- Get the user role to find public_profile_id
    -- Handle both individual and group submissions
    IF v_submission.profile_id IS NOT NULL THEN
        -- Individual submission
        SELECT ur.public_profile_id
        INTO v_user_role
        FROM public.user_roles ur
        WHERE ur.private_profile_id = v_submission.profile_id
        AND ur.class_id = v_submission.class_id
        LIMIT 1;

        IF FOUND THEN
            -- Upsert the leaderboard entry
            INSERT INTO public.assignment_leaderboard (
                assignment_id,
                class_id,
                public_profile_id,
                autograder_score,
                max_score,
                submission_id,
                updated_at
            ) VALUES (
                v_submission.assignment_id,
                v_submission.class_id,
                v_user_role.public_profile_id,
                NEW.score,
                COALESCE(NEW.max_score, v_submission.autograder_points, 100),
                NEW.submission_id,
                NOW()
            )
            ON CONFLICT (assignment_id, public_profile_id)
            DO UPDATE SET
                autograder_score = EXCLUDED.autograder_score,
                max_score = EXCLUDED.max_score,
                submission_id = EXCLUDED.submission_id,
                updated_at = NOW();
        END IF;
    ELSIF v_submission.assignment_group_id IS NOT NULL THEN
        -- Group submission - update leaderboard for all group members
        FOR v_user_role IN
            SELECT ur.public_profile_id
            FROM public.assignment_groups_members agm
            INNER JOIN public.user_roles ur ON ur.private_profile_id = agm.profile_id
            WHERE agm.assignment_group_id = v_submission.assignment_group_id
            AND ur.class_id = v_submission.class_id
        LOOP
            INSERT INTO public.assignment_leaderboard (
                assignment_id,
                class_id,
                public_profile_id,
                autograder_score,
                max_score,
                submission_id,
                updated_at
            ) VALUES (
                v_submission.assignment_id,
                v_submission.class_id,
                v_user_role.public_profile_id,
                NEW.score,
                COALESCE(NEW.max_score, v_submission.autograder_points, 100),
                NEW.submission_id,
                NOW()
            )
            ON CONFLICT (assignment_id, public_profile_id)
            DO UPDATE SET
                autograder_score = EXCLUDED.autograder_score,
                max_score = EXCLUDED.max_score,
                submission_id = EXCLUDED.submission_id,
                updated_at = NOW();
        END LOOP;
    END IF;

    RETURN NEW;
END;
$function$;

-- Trigger: Update leaderboard when grader_results are inserted or updated
CREATE TRIGGER trigger_update_leaderboard_on_grader_result
    AFTER INSERT OR UPDATE ON public.grader_results
    FOR EACH ROW
    EXECUTE FUNCTION public.update_assignment_leaderboard();

-- Function to handle submission becoming active/inactive
CREATE OR REPLACE FUNCTION public.update_leaderboard_on_submission_active_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
    v_user_role RECORD;
    v_grader_result RECORD;
BEGIN
    -- Only react if is_active changed
    IF OLD.is_active IS DISTINCT FROM NEW.is_active THEN
        IF NEW.is_active = TRUE THEN
            -- Submission became active - update leaderboard with its score
            SELECT gr.*, a.autograder_points
            INTO v_grader_result
            FROM public.grader_results gr
            INNER JOIN public.assignments a ON a.id = NEW.assignment_id
            WHERE gr.submission_id = NEW.id
            LIMIT 1;

            IF FOUND THEN
                -- Handle individual submissions
                IF NEW.profile_id IS NOT NULL THEN
                    SELECT ur.public_profile_id
                    INTO v_user_role
                    FROM public.user_roles ur
                    WHERE ur.private_profile_id = NEW.profile_id
                    AND ur.class_id = NEW.class_id
                    LIMIT 1;

                    IF FOUND THEN
                        INSERT INTO public.assignment_leaderboard (
                            assignment_id,
                            class_id,
                            public_profile_id,
                            autograder_score,
                            max_score,
                            submission_id,
                            updated_at
                        ) VALUES (
                            NEW.assignment_id,
                            NEW.class_id,
                            v_user_role.public_profile_id,
                            v_grader_result.score,
                            COALESCE(v_grader_result.max_score, v_grader_result.autograder_points, 100),
                            NEW.id,
                            NOW()
                        )
                        ON CONFLICT (assignment_id, public_profile_id)
                        DO UPDATE SET
                            autograder_score = EXCLUDED.autograder_score,
                            max_score = EXCLUDED.max_score,
                            submission_id = EXCLUDED.submission_id,
                            updated_at = NOW();
                    END IF;
                ELSIF NEW.assignment_group_id IS NOT NULL THEN
                    -- Group submission
                    FOR v_user_role IN
                        SELECT ur.public_profile_id
                        FROM public.assignment_groups_members agm
                        INNER JOIN public.user_roles ur ON ur.private_profile_id = agm.profile_id
                        WHERE agm.assignment_group_id = NEW.assignment_group_id
                        AND ur.class_id = NEW.class_id
                    LOOP
                        INSERT INTO public.assignment_leaderboard (
                            assignment_id,
                            class_id,
                            public_profile_id,
                            autograder_score,
                            max_score,
                            submission_id,
                            updated_at
                        ) VALUES (
                            NEW.assignment_id,
                            NEW.class_id,
                            v_user_role.public_profile_id,
                            v_grader_result.score,
                            COALESCE(v_grader_result.max_score, v_grader_result.autograder_points, 100),
                            NEW.id,
                            NOW()
                        )
                        ON CONFLICT (assignment_id, public_profile_id)
                        DO UPDATE SET
                            autograder_score = EXCLUDED.autograder_score,
                            max_score = EXCLUDED.max_score,
                            submission_id = EXCLUDED.submission_id,
                            updated_at = NOW();
                    END LOOP;
                END IF;
            END IF;
        END IF;
        -- Note: When a submission becomes inactive, the old entry remains
        -- The next active submission will update it
    END IF;

    RETURN NEW;
END;
$function$;

-- Trigger: Update leaderboard when submission active status changes
CREATE TRIGGER trigger_update_leaderboard_on_submission_active
    AFTER UPDATE ON public.submissions
    FOR EACH ROW
    EXECUTE FUNCTION public.update_leaderboard_on_submission_active_change();

-- Add comment
COMMENT ON TABLE public.assignment_leaderboard IS 'Stores autograder scores per student per assignment for leaderboard display. Uses public_profile_id for pseudonymity.';

-- Create broadcast trigger for realtime updates
-- Uses the unified course table change broadcaster which sends to staff and students channels
CREATE TRIGGER broadcast_assignment_leaderboard_realtime
    AFTER INSERT OR DELETE OR UPDATE ON public.assignment_leaderboard
    FOR EACH ROW
    EXECUTE FUNCTION broadcast_course_table_change_unified();
