create type "public"."flashcard_actions" as enum ('deck_viewed', 'card_prompt_viewed', 'card_answer_viewed', 'card_marked_got_it', 'card_marked_keep_trying', 'card_returned_to_deck', 'deck_progress_reset_all', 'deck_progress_reset_card');

create table "public"."flashcard_decks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "class_id" bigint not null,
    "creator_id" uuid not null,
    "name" text not null,
    "description" text,
    "source_yml" text,
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."flashcard_decks" enable row level security;

create table "public"."flashcard_interaction_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "student_id" uuid not null,
    "card_id" bigint,
    "deck_id" bigint not null,
    "action" flashcard_actions not null,
    "duration_on_card_ms" bigint not null
);


alter table "public"."flashcard_interaction_logs" enable row level security;

create table "public"."flashcards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "deck_id" bigint not null,
    "title" text not null,
    "prompt" text not null,
    "answer" text not null,
    "order" bigint,
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."flashcards" enable row level security;

create table "public"."student_flashcard_deck_progress" (
    "student_id" uuid not null,
    "card_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "is_mastered" boolean not null default false,
    "last_answered_correctly_at" timestamp with time zone,
    "first_answered_correctly_at" timestamp with time zone,
    "updated_at" timestamp with time zone
);


alter table "public"."student_flashcard_deck_progress" enable row level security;

CREATE UNIQUE INDEX flashcard_decks_id_key ON public.flashcard_decks USING btree (id);

CREATE UNIQUE INDEX flashcard_decks_pkey ON public.flashcard_decks USING btree (id);

CREATE UNIQUE INDEX flashcard_interaction_logs_id_key ON public.flashcard_interaction_logs USING btree (id);

CREATE UNIQUE INDEX flashcard_interaction_logs_pkey ON public.flashcard_interaction_logs USING btree (id);

CREATE UNIQUE INDEX flashcards_id_key ON public.flashcards USING btree (id);

CREATE UNIQUE INDEX flashcards_pkey ON public.flashcards USING btree (id);

CREATE UNIQUE INDEX student_flashcard_deck_progress_pkey ON public.student_flashcard_deck_progress USING btree (student_id, card_id);

alter table "public"."flashcard_decks" add constraint "flashcard_decks_pkey" PRIMARY KEY using index "flashcard_decks_pkey";

alter table "public"."flashcard_interaction_logs" add constraint "flashcard_interaction_logs_pkey" PRIMARY KEY using index "flashcard_interaction_logs_pkey";

alter table "public"."flashcards" add constraint "flashcards_pkey" PRIMARY KEY using index "flashcards_pkey";

alter table "public"."student_flashcard_deck_progress" add constraint "student_flashcard_deck_progress_pkey" PRIMARY KEY using index "student_flashcard_deck_progress_pkey";

alter table "public"."flashcard_decks" add constraint "flashcard_decks_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."flashcard_decks" validate constraint "flashcard_decks_class_id_fkey";

alter table "public"."flashcard_decks" add constraint "flashcard_decks_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."flashcard_decks" validate constraint "flashcard_decks_creator_id_fkey";

alter table "public"."flashcard_decks" add constraint "flashcard_decks_id_key" UNIQUE using index "flashcard_decks_id_key";

alter table "public"."flashcard_interaction_logs" add constraint "flashcard_interaction_logs_card_id_fkey" FOREIGN KEY (card_id) REFERENCES flashcards(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."flashcard_interaction_logs" validate constraint "flashcard_interaction_logs_card_id_fkey";

alter table "public"."flashcard_interaction_logs" add constraint "flashcard_interaction_logs_deck_id_fkey" FOREIGN KEY (deck_id) REFERENCES flashcard_decks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."flashcard_interaction_logs" validate constraint "flashcard_interaction_logs_deck_id_fkey";

alter table "public"."flashcard_interaction_logs" add constraint "flashcard_interaction_logs_id_key" UNIQUE using index "flashcard_interaction_logs_id_key";

alter table "public"."flashcard_interaction_logs" add constraint "flashcard_interaction_logs_student_id_fkey" FOREIGN KEY (student_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."flashcard_interaction_logs" validate constraint "flashcard_interaction_logs_student_id_fkey";

alter table "public"."flashcards" add constraint "flashcards_deck_id_fkey" FOREIGN KEY (deck_id) REFERENCES flashcard_decks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."flashcards" validate constraint "flashcards_deck_id_fkey";

alter table "public"."flashcards" add constraint "flashcards_id_key" UNIQUE using index "flashcards_id_key";

alter table "public"."student_flashcard_deck_progress" add constraint "student_flashcard_deck_progress_card_id_fkey" FOREIGN KEY (card_id) REFERENCES flashcards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_flashcard_deck_progress" validate constraint "student_flashcard_deck_progress_card_id_fkey";

alter table "public"."student_flashcard_deck_progress" add constraint "student_flashcard_deck_progress_student_id_fkey" FOREIGN KEY (student_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_flashcard_deck_progress" validate constraint "student_flashcard_deck_progress_student_id_fkey";

grant delete on table "public"."flashcard_decks" to "anon";

grant insert on table "public"."flashcard_decks" to "anon";

grant references on table "public"."flashcard_decks" to "anon";

grant select on table "public"."flashcard_decks" to "anon";

grant trigger on table "public"."flashcard_decks" to "anon";

grant truncate on table "public"."flashcard_decks" to "anon";

grant update on table "public"."flashcard_decks" to "anon";

grant delete on table "public"."flashcard_decks" to "authenticated";

grant insert on table "public"."flashcard_decks" to "authenticated";

grant references on table "public"."flashcard_decks" to "authenticated";

grant select on table "public"."flashcard_decks" to "authenticated";

grant trigger on table "public"."flashcard_decks" to "authenticated";

grant truncate on table "public"."flashcard_decks" to "authenticated";

grant update on table "public"."flashcard_decks" to "authenticated";

grant delete on table "public"."flashcard_decks" to "service_role";

grant insert on table "public"."flashcard_decks" to "service_role";

grant references on table "public"."flashcard_decks" to "service_role";

grant select on table "public"."flashcard_decks" to "service_role";

grant trigger on table "public"."flashcard_decks" to "service_role";

grant truncate on table "public"."flashcard_decks" to "service_role";

grant update on table "public"."flashcard_decks" to "service_role";

grant delete on table "public"."flashcard_interaction_logs" to "anon";

grant insert on table "public"."flashcard_interaction_logs" to "anon";

grant references on table "public"."flashcard_interaction_logs" to "anon";

grant select on table "public"."flashcard_interaction_logs" to "anon";

grant trigger on table "public"."flashcard_interaction_logs" to "anon";

grant truncate on table "public"."flashcard_interaction_logs" to "anon";

grant update on table "public"."flashcard_interaction_logs" to "anon";

grant delete on table "public"."flashcard_interaction_logs" to "authenticated";

grant insert on table "public"."flashcard_interaction_logs" to "authenticated";

grant references on table "public"."flashcard_interaction_logs" to "authenticated";

grant select on table "public"."flashcard_interaction_logs" to "authenticated";

grant trigger on table "public"."flashcard_interaction_logs" to "authenticated";

grant truncate on table "public"."flashcard_interaction_logs" to "authenticated";

grant update on table "public"."flashcard_interaction_logs" to "authenticated";

grant delete on table "public"."flashcard_interaction_logs" to "service_role";

grant insert on table "public"."flashcard_interaction_logs" to "service_role";

grant references on table "public"."flashcard_interaction_logs" to "service_role";

grant select on table "public"."flashcard_interaction_logs" to "service_role";

grant trigger on table "public"."flashcard_interaction_logs" to "service_role";

grant truncate on table "public"."flashcard_interaction_logs" to "service_role";

grant update on table "public"."flashcard_interaction_logs" to "service_role";

grant delete on table "public"."flashcards" to "anon";

grant insert on table "public"."flashcards" to "anon";

grant references on table "public"."flashcards" to "anon";

grant select on table "public"."flashcards" to "anon";

grant trigger on table "public"."flashcards" to "anon";

grant truncate on table "public"."flashcards" to "anon";

grant update on table "public"."flashcards" to "anon";

grant delete on table "public"."flashcards" to "authenticated";

grant insert on table "public"."flashcards" to "authenticated";

grant references on table "public"."flashcards" to "authenticated";

grant select on table "public"."flashcards" to "authenticated";

grant trigger on table "public"."flashcards" to "authenticated";

grant truncate on table "public"."flashcards" to "authenticated";

grant update on table "public"."flashcards" to "authenticated";

grant delete on table "public"."flashcards" to "service_role";

grant insert on table "public"."flashcards" to "service_role";

grant references on table "public"."flashcards" to "service_role";

grant select on table "public"."flashcards" to "service_role";

grant trigger on table "public"."flashcards" to "service_role";

grant truncate on table "public"."flashcards" to "service_role";

grant update on table "public"."flashcards" to "service_role";

grant delete on table "public"."student_flashcard_deck_progress" to "anon";

grant insert on table "public"."student_flashcard_deck_progress" to "anon";

grant references on table "public"."student_flashcard_deck_progress" to "anon";

grant select on table "public"."student_flashcard_deck_progress" to "anon";

grant trigger on table "public"."student_flashcard_deck_progress" to "anon";

grant truncate on table "public"."student_flashcard_deck_progress" to "anon";

grant update on table "public"."student_flashcard_deck_progress" to "anon";

grant delete on table "public"."student_flashcard_deck_progress" to "authenticated";

grant insert on table "public"."student_flashcard_deck_progress" to "authenticated";

grant references on table "public"."student_flashcard_deck_progress" to "authenticated";

grant select on table "public"."student_flashcard_deck_progress" to "authenticated";

grant trigger on table "public"."student_flashcard_deck_progress" to "authenticated";

grant truncate on table "public"."student_flashcard_deck_progress" to "authenticated";

grant update on table "public"."student_flashcard_deck_progress" to "authenticated";

grant delete on table "public"."student_flashcard_deck_progress" to "service_role";

grant insert on table "public"."student_flashcard_deck_progress" to "service_role";

grant references on table "public"."student_flashcard_deck_progress" to "service_role";

grant select on table "public"."student_flashcard_deck_progress" to "service_role";

grant trigger on table "public"."student_flashcard_deck_progress" to "service_role";

grant truncate on table "public"."student_flashcard_deck_progress" to "service_role";

grant update on table "public"."student_flashcard_deck_progress" to "service_role";


