create type "public"."help_queue_type" as enum ('text', 'video', 'in_person');

create type "public"."help_request_status" as enum ('open', 'in_progress', 'resolved', 'closed');

create type "public"."location_type" as enum ('remote', 'in_person', 'hybrid');

create type "public"."moderation_action_type" as enum ('warning', 'temporary_ban', 'permanent_ban', 'message_deleted', 'message_edited');

create type "public"."student_help_activity_type" as enum ('request_created', 'request_updated', 'message_sent', 'request_resolved', 'video_joined', 'video_left');

drop policy "students view own, instructors and graders view all" on "public"."help_requests";

create table "public"."help_queue_assignments" (
    "id" bigint generated by default as identity not null,
    "started_at" timestamp with time zone not null default now(),
    "help_queue_id" bigint not null,
    "class_id" bigint not null,
    "ended_at" timestamp with time zone,
    "is_active" boolean not null default true,
    "max_concurrent_students" integer not null default 3,
    "ta_profile_id" uuid not null
);


alter table "public"."help_queue_assignments" enable row level security;

create table "public"."help_request_file_references" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "help_request_id" bigint not null,
    "class_id" bigint not null,
    "submission_file_id" bigint,
    "submission_id" bigint,
    "line_number" bigint
);


alter table "public"."help_request_file_references" enable row level security;

create table "public"."help_request_moderation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "help_request_id" bigint not null,
    "message_id" bigint,
    "student_profile_id" uuid not null,
    "moderator_profile_id" uuid not null,
    "class_id" bigint not null,
    "action_type" moderation_action_type not null,
    "reason" text,
    "duration_minutes" bigint,
    "is_permanent" boolean not null default false,
    "expires_at" timestamp with time zone
);


alter table "public"."help_request_moderation" enable row level security;

create table "public"."help_request_templates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "class_id" bigint not null,
    "name" text not null,
    "description" text,
    "template_content" text not null,
    "category" text not null,
    "is_active" boolean not null default true,
    "usage_count" bigint not null default '0'::bigint,
    "created_by_id" uuid not null
);


alter table "public"."help_request_templates" enable row level security;

create table "public"."student_help_activity" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "student_profile_id" uuid not null,
    "class_id" bigint not null,
    "help_request_id" bigint not null,
    "activity_type" student_help_activity_type not null,
    "activity_description" text
);


alter table "public"."student_help_activity" enable row level security;

create table "public"."student_karma_notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "student_profile_id" uuid not null,
    "class_id" bigint not null,
    "karma_score" bigint not null default '0'::bigint,
    "internal_notes" text default ''::text,
    "created_by_id" uuid not null,
    "updated_at" timestamp with time zone not null,
    "last_activity_at" timestamp with time zone
);


alter table "public"."student_karma_notes" enable row level security;

alter table "public"."help_queues" add column "is_active" boolean not null default true;

alter table "public"."help_queues" add column "max_concurrent_requests" integer;

alter table "public"."help_queues" add column "queue_type" help_queue_type not null default 'text'::help_queue_type;

alter table "public"."help_request_messages" add column "reply_to_message_id" bigint;

alter table "public"."help_requests" add column "estimated_duration_minutes" integer;

alter table "public"."help_requests" add column "is_private" boolean not null default false;

alter table "public"."help_requests" add column "location_type" location_type not null default 'remote'::location_type;

alter table "public"."help_requests" add column "priority_level" integer not null default 1;

alter table "public"."help_requests" add column "referenced_submission_id" bigint;

alter table "public"."help_requests" add column "status" help_request_status not null default 'open'::help_request_status;

alter table "public"."help_requests" add column "template_id" bigint;

CREATE UNIQUE INDEX help_queue_assignments_pkey ON public.help_queue_assignments USING btree (id);

CREATE UNIQUE INDEX help_request_file_references_pkey ON public.help_request_file_references USING btree (id);

CREATE UNIQUE INDEX help_request_moderation_pkey ON public.help_request_moderation USING btree (id);

CREATE UNIQUE INDEX help_request_templates_pkey ON public.help_request_templates USING btree (id);

CREATE UNIQUE INDEX student_help_activity_pkey ON public.student_help_activity USING btree (id);

CREATE UNIQUE INDEX student_karma_notes_pkey ON public.student_karma_notes USING btree (id);

alter table "public"."help_queue_assignments" add constraint "help_queue_assignments_pkey" PRIMARY KEY using index "help_queue_assignments_pkey";

alter table "public"."help_request_file_references" add constraint "help_request_file_references_pkey" PRIMARY KEY using index "help_request_file_references_pkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_pkey" PRIMARY KEY using index "help_request_moderation_pkey";

alter table "public"."help_request_templates" add constraint "help_request_templates_pkey" PRIMARY KEY using index "help_request_templates_pkey";

alter table "public"."student_help_activity" add constraint "student_help_activity_pkey" PRIMARY KEY using index "student_help_activity_pkey";

alter table "public"."student_karma_notes" add constraint "student_karma_notes_pkey" PRIMARY KEY using index "student_karma_notes_pkey";

alter table "public"."help_queue_assignments" add constraint "help_queue_assignments_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_queue_assignments" validate constraint "help_queue_assignments_class_id_fkey";

alter table "public"."help_queue_assignments" add constraint "help_queue_assignments_help_queue_id_fkey" FOREIGN KEY (help_queue_id) REFERENCES help_queues(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_queue_assignments" validate constraint "help_queue_assignments_help_queue_id_fkey";

alter table "public"."help_queue_assignments" add constraint "help_queue_assignments_ta_profile_id_fkey" FOREIGN KEY (ta_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_queue_assignments" validate constraint "help_queue_assignments_ta_profile_id_fkey";

alter table "public"."help_request_file_references" add constraint "help_request_file_references_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_file_references" validate constraint "help_request_file_references_class_id_fkey";

alter table "public"."help_request_file_references" add constraint "help_request_file_references_help_request_id_fkey" FOREIGN KEY (help_request_id) REFERENCES help_requests(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_file_references" validate constraint "help_request_file_references_help_request_id_fkey";

alter table "public"."help_request_file_references" add constraint "help_request_file_references_submission_file_id_fkey" FOREIGN KEY (submission_file_id) REFERENCES submission_files(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_request_file_references" validate constraint "help_request_file_references_submission_file_id_fkey";

alter table "public"."help_request_file_references" add constraint "help_request_file_references_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES submissions(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_request_file_references" validate constraint "help_request_file_references_submission_id_fkey";

alter table "public"."help_request_messages" add constraint "help_request_messages_reply_to_message_id_fkey" FOREIGN KEY (reply_to_message_id) REFERENCES help_request_messages(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_request_messages" validate constraint "help_request_messages_reply_to_message_id_fkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_moderation" validate constraint "help_request_moderation_class_id_fkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_help_request_id_fkey" FOREIGN KEY (help_request_id) REFERENCES help_requests(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_moderation" validate constraint "help_request_moderation_help_request_id_fkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_message_id_fkey" FOREIGN KEY (message_id) REFERENCES help_request_messages(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_request_moderation" validate constraint "help_request_moderation_message_id_fkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_moderator_profile_id_fkey" FOREIGN KEY (moderator_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_moderation" validate constraint "help_request_moderation_moderator_profile_id_fkey";

alter table "public"."help_request_moderation" add constraint "help_request_moderation_student_profile_id_fkey" FOREIGN KEY (student_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_moderation" validate constraint "help_request_moderation_student_profile_id_fkey";

alter table "public"."help_request_templates" add constraint "help_request_templates_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."help_request_templates" validate constraint "help_request_templates_class_id_fkey";

alter table "public"."help_request_templates" add constraint "help_request_templates_created_by_id_fkey" FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_request_templates" validate constraint "help_request_templates_created_by_id_fkey";

alter table "public"."help_requests" add constraint "help_requests_referenced_submission_id_fkey" FOREIGN KEY (referenced_submission_id) REFERENCES submissions(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_requests" validate constraint "help_requests_referenced_submission_id_fkey";

alter table "public"."help_requests" add constraint "help_requests_template_id_fkey" FOREIGN KEY (template_id) REFERENCES help_request_templates(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."help_requests" validate constraint "help_requests_template_id_fkey";

alter table "public"."student_help_activity" add constraint "student_help_activity_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_help_activity" validate constraint "student_help_activity_class_id_fkey";

alter table "public"."student_help_activity" add constraint "student_help_activity_help_request_id_fkey" FOREIGN KEY (help_request_id) REFERENCES help_requests(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_help_activity" validate constraint "student_help_activity_help_request_id_fkey";

alter table "public"."student_help_activity" add constraint "student_help_activity_student_profile_id_fkey" FOREIGN KEY (student_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_help_activity" validate constraint "student_help_activity_student_profile_id_fkey";

alter table "public"."student_karma_notes" add constraint "student_karma_notes_class_id_fkey" FOREIGN KEY (class_id) REFERENCES classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_karma_notes" validate constraint "student_karma_notes_class_id_fkey";

alter table "public"."student_karma_notes" add constraint "student_karma_notes_created_by_id_fkey" FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."student_karma_notes" validate constraint "student_karma_notes_created_by_id_fkey";

alter table "public"."student_karma_notes" add constraint "student_karma_notes_student_profile_id_fkey" FOREIGN KEY (student_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_karma_notes" validate constraint "student_karma_notes_student_profile_id_fkey";

grant delete on table "public"."help_queue_assignments" to "anon";

grant insert on table "public"."help_queue_assignments" to "anon";

grant references on table "public"."help_queue_assignments" to "anon";

grant select on table "public"."help_queue_assignments" to "anon";

grant trigger on table "public"."help_queue_assignments" to "anon";

grant truncate on table "public"."help_queue_assignments" to "anon";

grant update on table "public"."help_queue_assignments" to "anon";

grant delete on table "public"."help_queue_assignments" to "authenticated";

grant insert on table "public"."help_queue_assignments" to "authenticated";

grant references on table "public"."help_queue_assignments" to "authenticated";

grant select on table "public"."help_queue_assignments" to "authenticated";

grant trigger on table "public"."help_queue_assignments" to "authenticated";

grant truncate on table "public"."help_queue_assignments" to "authenticated";

grant update on table "public"."help_queue_assignments" to "authenticated";

grant delete on table "public"."help_queue_assignments" to "service_role";

grant insert on table "public"."help_queue_assignments" to "service_role";

grant references on table "public"."help_queue_assignments" to "service_role";

grant select on table "public"."help_queue_assignments" to "service_role";

grant trigger on table "public"."help_queue_assignments" to "service_role";

grant truncate on table "public"."help_queue_assignments" to "service_role";

grant update on table "public"."help_queue_assignments" to "service_role";

grant delete on table "public"."help_request_file_references" to "anon";

grant insert on table "public"."help_request_file_references" to "anon";

grant references on table "public"."help_request_file_references" to "anon";

grant select on table "public"."help_request_file_references" to "anon";

grant trigger on table "public"."help_request_file_references" to "anon";

grant truncate on table "public"."help_request_file_references" to "anon";

grant update on table "public"."help_request_file_references" to "anon";

grant delete on table "public"."help_request_file_references" to "authenticated";

grant insert on table "public"."help_request_file_references" to "authenticated";

grant references on table "public"."help_request_file_references" to "authenticated";

grant select on table "public"."help_request_file_references" to "authenticated";

grant trigger on table "public"."help_request_file_references" to "authenticated";

grant truncate on table "public"."help_request_file_references" to "authenticated";

grant update on table "public"."help_request_file_references" to "authenticated";

grant delete on table "public"."help_request_file_references" to "service_role";

grant insert on table "public"."help_request_file_references" to "service_role";

grant references on table "public"."help_request_file_references" to "service_role";

grant select on table "public"."help_request_file_references" to "service_role";

grant trigger on table "public"."help_request_file_references" to "service_role";

grant truncate on table "public"."help_request_file_references" to "service_role";

grant update on table "public"."help_request_file_references" to "service_role";

grant delete on table "public"."help_request_moderation" to "anon";

grant insert on table "public"."help_request_moderation" to "anon";

grant references on table "public"."help_request_moderation" to "anon";

grant select on table "public"."help_request_moderation" to "anon";

grant trigger on table "public"."help_request_moderation" to "anon";

grant truncate on table "public"."help_request_moderation" to "anon";

grant update on table "public"."help_request_moderation" to "anon";

grant delete on table "public"."help_request_moderation" to "authenticated";

grant insert on table "public"."help_request_moderation" to "authenticated";

grant references on table "public"."help_request_moderation" to "authenticated";

grant select on table "public"."help_request_moderation" to "authenticated";

grant trigger on table "public"."help_request_moderation" to "authenticated";

grant truncate on table "public"."help_request_moderation" to "authenticated";

grant update on table "public"."help_request_moderation" to "authenticated";

grant delete on table "public"."help_request_moderation" to "service_role";

grant insert on table "public"."help_request_moderation" to "service_role";

grant references on table "public"."help_request_moderation" to "service_role";

grant select on table "public"."help_request_moderation" to "service_role";

grant trigger on table "public"."help_request_moderation" to "service_role";

grant truncate on table "public"."help_request_moderation" to "service_role";

grant update on table "public"."help_request_moderation" to "service_role";

grant delete on table "public"."help_request_templates" to "anon";

grant insert on table "public"."help_request_templates" to "anon";

grant references on table "public"."help_request_templates" to "anon";

grant select on table "public"."help_request_templates" to "anon";

grant trigger on table "public"."help_request_templates" to "anon";

grant truncate on table "public"."help_request_templates" to "anon";

grant update on table "public"."help_request_templates" to "anon";

grant delete on table "public"."help_request_templates" to "authenticated";

grant insert on table "public"."help_request_templates" to "authenticated";

grant references on table "public"."help_request_templates" to "authenticated";

grant select on table "public"."help_request_templates" to "authenticated";

grant trigger on table "public"."help_request_templates" to "authenticated";

grant truncate on table "public"."help_request_templates" to "authenticated";

grant update on table "public"."help_request_templates" to "authenticated";

grant delete on table "public"."help_request_templates" to "service_role";

grant insert on table "public"."help_request_templates" to "service_role";

grant references on table "public"."help_request_templates" to "service_role";

grant select on table "public"."help_request_templates" to "service_role";

grant trigger on table "public"."help_request_templates" to "service_role";

grant truncate on table "public"."help_request_templates" to "service_role";

grant update on table "public"."help_request_templates" to "service_role";

grant delete on table "public"."student_help_activity" to "anon";

grant insert on table "public"."student_help_activity" to "anon";

grant references on table "public"."student_help_activity" to "anon";

grant select on table "public"."student_help_activity" to "anon";

grant trigger on table "public"."student_help_activity" to "anon";

grant truncate on table "public"."student_help_activity" to "anon";

grant update on table "public"."student_help_activity" to "anon";

grant delete on table "public"."student_help_activity" to "authenticated";

grant insert on table "public"."student_help_activity" to "authenticated";

grant references on table "public"."student_help_activity" to "authenticated";

grant select on table "public"."student_help_activity" to "authenticated";

grant trigger on table "public"."student_help_activity" to "authenticated";

grant truncate on table "public"."student_help_activity" to "authenticated";

grant update on table "public"."student_help_activity" to "authenticated";

grant delete on table "public"."student_help_activity" to "service_role";

grant insert on table "public"."student_help_activity" to "service_role";

grant references on table "public"."student_help_activity" to "service_role";

grant select on table "public"."student_help_activity" to "service_role";

grant trigger on table "public"."student_help_activity" to "service_role";

grant truncate on table "public"."student_help_activity" to "service_role";

grant update on table "public"."student_help_activity" to "service_role";

grant delete on table "public"."student_karma_notes" to "anon";

grant insert on table "public"."student_karma_notes" to "anon";

grant references on table "public"."student_karma_notes" to "anon";

grant select on table "public"."student_karma_notes" to "anon";

grant trigger on table "public"."student_karma_notes" to "anon";

grant truncate on table "public"."student_karma_notes" to "anon";

grant update on table "public"."student_karma_notes" to "anon";

grant delete on table "public"."student_karma_notes" to "authenticated";

grant insert on table "public"."student_karma_notes" to "authenticated";

grant references on table "public"."student_karma_notes" to "authenticated";

grant select on table "public"."student_karma_notes" to "authenticated";

grant trigger on table "public"."student_karma_notes" to "authenticated";

grant truncate on table "public"."student_karma_notes" to "authenticated";

grant update on table "public"."student_karma_notes" to "authenticated";

grant delete on table "public"."student_karma_notes" to "service_role";

grant insert on table "public"."student_karma_notes" to "service_role";

grant references on table "public"."student_karma_notes" to "service_role";

grant select on table "public"."student_karma_notes" to "service_role";

grant trigger on table "public"."student_karma_notes" to "service_role";

grant truncate on table "public"."student_karma_notes" to "service_role";

grant update on table "public"."student_karma_notes" to "service_role";

create policy "Graders can CRUD self-assignments"
on "public"."help_queue_assignments"
as permissive
for all
to authenticated
using ((authorizeforclassgrader(class_id) AND (( SELECT auth.uid() AS uid) = ta_profile_id)))
with check ((authorizeforclassgrader(class_id) AND (( SELECT auth.uid() AS uid) = ta_profile_id)));


create policy "Instructors can CRUD queues"
on "public"."help_queue_assignments"
as permissive
for all
to authenticated
using (authorizeforclassinstructor(class_id))
with check (authorizeforclassinstructor(class_id));


create policy "Users can view queue assignments for their classes"
on "public"."help_queue_assignments"
as permissive
for select
to authenticated
using (authorizeforclass(class_id));


create policy "Users can CRUD file references in their classes"
on "public"."help_request_file_references"
as permissive
for all
to authenticated
using (authorizeforclass(class_id))
with check (authorizeforclass(class_id));


create policy "Graders can create moderation records"
on "public"."help_request_moderation"
as permissive
for insert
to authenticated
with check ((authorizeforclassgrader(class_id) AND (( SELECT auth.uid() AS uid) = moderator_profile_id)));


create policy "Graders can view moderation records"
on "public"."help_request_moderation"
as permissive
for select
to authenticated
using (authorizeforclassgrader(class_id));


create policy "Instructors can CRUD moderation records"
on "public"."help_request_moderation"
as permissive
for all
to authenticated
using (authorizeforclassinstructor(class_id))
with check (authorizeforclassinstructor(class_id));


create policy "Instructors can CRUD templates"
on "public"."help_request_templates"
as permissive
for all
to authenticated
using (authorizeforclassinstructor(class_id))
with check (authorizeforclassinstructor(class_id));


create policy "Users can view templates for their classes"
on "public"."help_request_templates"
as permissive
for select
to authenticated
using (authorizeforclass(class_id));


create policy "Users can view private help requests they created or are assign"
on "public"."help_requests"
as permissive
for select
to authenticated
using ((((NOT is_private) AND authorizeforclass(class_id)) OR (is_private AND ((( SELECT auth.uid() AS uid) = creator) OR (( SELECT auth.uid() AS uid) = assignee))) OR authorizeforclassgrader(class_id)));


create policy "Instructors can CRUD activity records"
on "public"."student_help_activity"
as permissive
for all
to authenticated
using (authorizeforclassinstructor(class_id))
with check (authorizeforclassinstructor(class_id));


create policy "System can create activity records"
on "public"."student_help_activity"
as permissive
for insert
to authenticated
with check (authorizeforclass(class_id));


create policy "Users can view activity for their classes and own activity"
on "public"."student_help_activity"
as permissive
for select
to authenticated
using ((authorizeforclass(class_id) OR (( SELECT auth.uid() AS uid) = student_profile_id)));


create policy "Instructors and graders can CRUD karma notes"
on "public"."student_karma_notes"
as permissive
for all
to authenticated
using (authorizeforclassgrader(class_id))
with check (authorizeforclassgrader(class_id));



