-- Discord Bot Integration Migration
-- Adds Discord OAuth support, channel management, and message tracking

-- 1. Add Discord fields to users table
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS discord_id text;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS discord_username text;

-- 2. Add Discord fields to classes table
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS discord_server_id text;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS discord_channel_group_id text;

-- RLS helper: ensure only Discord IDs change on classes rows
CREATE OR REPLACE FUNCTION public.only_discord_ids_changed(new_row public.classes)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT COALESCE(
        (
          SELECT bool_and(changed.key = ANY(ARRAY[
            'discord_server_id',
            'discord_channel_group_id',
            'updated_at' -- allow automatic timestamp touches if present
          ]))
          FROM (
            SELECT t.key
            FROM jsonb_each(to_jsonb(new_row)) AS t(key, value)
            WHERE (to_jsonb(old_row)->t.key) IS DISTINCT FROM t.value
          ) AS changed
        ),
        true  -- no differences -> allow
      )
      FROM public.classes old_row
      WHERE old_row.id = new_row.id
    ),
    false -- no matching row found
  );
$$;

-- Allow instructors to update only Discord IDs on their classes
DROP POLICY IF EXISTS classes_instructor_update_discord_ids ON public.classes;
CREATE POLICY classes_instructor_update_discord_ids
  ON public.classes
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.class_id = classes.id
        AND ur.user_id = auth.uid()
        AND ur.role = 'instructor'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.class_id = classes.id
        AND ur.user_id = auth.uid()
        AND ur.role = 'instructor'
    )
    AND public.only_discord_ids_changed(classes)
  );

-- 3. Create enums for Discord resource types
CREATE TYPE public.discord_channel_type AS ENUM (
  'general',
  'assignment', 
  'lab',
  'office_hours',
  'regrades'
);

CREATE TYPE public.discord_resource_type AS ENUM (
  'help_request',
  'regrade_request'
);

-- 4. Create discord_channels table
CREATE TABLE IF NOT EXISTS public.discord_channels (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  class_id bigint NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  discord_channel_id text NOT NULL,
  channel_type public.discord_channel_type NOT NULL,
  resource_id bigint, -- FK to assignments, lab_sections, or help_queues
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(class_id, discord_channel_id),
  UNIQUE(class_id, channel_type, resource_id) -- One channel per resource type per class
);

-- 5. Create discord_messages table for deep linking
CREATE TABLE IF NOT EXISTS public.discord_messages (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  class_id bigint NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  discord_message_id text NOT NULL,
  discord_channel_id text NOT NULL,
  resource_type public.discord_resource_type NOT NULL,
  resource_id bigint NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(class_id, discord_message_id),
  UNIQUE(class_id, resource_type, resource_id) -- One message per resource
);

-- 5b. Create discord_roles table for role tracking
CREATE TABLE IF NOT EXISTS public.discord_roles (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  class_id bigint NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  discord_role_id text NOT NULL,
  role_type text NOT NULL CHECK (role_type IN ('student', 'grader', 'instructor')),
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(class_id, role_type)
);

-- 6. Create indexes
CREATE INDEX IF NOT EXISTS idx_discord_channels_class_id ON public.discord_channels(class_id);
CREATE INDEX IF NOT EXISTS idx_discord_channels_type_resource ON public.discord_channels(channel_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_discord_messages_class_resource ON public.discord_messages(class_id, resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_discord_messages_channel ON public.discord_messages(discord_channel_id);
CREATE INDEX IF NOT EXISTS idx_discord_roles_class_id ON public.discord_roles(class_id);
CREATE INDEX IF NOT EXISTS idx_discord_roles_type ON public.discord_roles(class_id, role_type);

-- 7. Enable RLS
ALTER TABLE public.discord_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_roles ENABLE ROW LEVEL SECURITY;

-- 8. RLS Policies for discord_channels
-- Staff can view channels for their classes
DROP POLICY IF EXISTS discord_channels_staff_select ON public.discord_channels;
CREATE POLICY discord_channels_staff_select
  ON public.discord_channels
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.class_id = discord_channels.class_id
        AND ur.user_id = auth.uid()
        AND ur.role IN ('instructor', 'grader')
    )
  );

-- Service role can do everything
DROP POLICY IF EXISTS discord_channels_service_role_all ON public.discord_channels;
CREATE POLICY discord_channels_service_role_all
  ON public.discord_channels
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 9. RLS Policies for discord_messages
-- Staff can view messages for their classes
DROP POLICY IF EXISTS discord_messages_staff_select ON public.discord_messages;
CREATE POLICY discord_messages_staff_select
  ON public.discord_messages
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.class_id = discord_messages.class_id
        AND ur.user_id = auth.uid()
        AND ur.role IN ('instructor', 'grader')
    )
  );

-- Service role can do everything
DROP POLICY IF EXISTS discord_messages_service_role_all ON public.discord_messages;
CREATE POLICY discord_messages_service_role_all
  ON public.discord_messages
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 9b. RLS Policies for discord_roles
-- Staff can view roles for their classes
DROP POLICY IF EXISTS discord_roles_staff_select ON public.discord_roles;
CREATE POLICY discord_roles_staff_select
  ON public.discord_roles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.class_id = discord_roles.class_id
        AND ur.user_id = auth.uid()
        AND ur.role IN ('instructor', 'grader')
    )
  );

-- Service role can do everything
DROP POLICY IF EXISTS discord_roles_service_role_all ON public.discord_roles;
CREATE POLICY discord_roles_service_role_all
  ON public.discord_roles
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 10. Create PGMQ queues for Discord async operations
DO $$
BEGIN
  PERFORM pgmq.create('discord_async_calls');
EXCEPTION WHEN OTHERS THEN
  -- queue likely exists; ignore
  NULL;
END $$;

DO $$
BEGIN
  PERFORM pgmq.create('discord_async_calls_dlq');
EXCEPTION WHEN OTHERS THEN
  -- queue likely exists; ignore
  NULL;
END $$;

-- 11. Grant permissions on PGMQ queues
GRANT INSERT ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT SELECT ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT DELETE ON TABLE "pgmq"."q_discord_async_calls" TO "service_role";
GRANT INSERT ON TABLE "pgmq"."q_discord_async_calls" TO "service_role";
GRANT SELECT ON TABLE "pgmq"."q_discord_async_calls" TO "service_role";
GRANT UPDATE ON TABLE "pgmq"."q_discord_async_calls" TO "service_role";
GRANT DELETE ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT REFERENCES ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT TRIGGER ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT TRUNCATE ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";
GRANT UPDATE ON TABLE "pgmq"."a_discord_async_calls" TO "service_role";

GRANT INSERT ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT SELECT ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT DELETE ON TABLE "pgmq"."q_discord_async_calls_dlq" TO "service_role";
GRANT INSERT ON TABLE "pgmq"."q_discord_async_calls_dlq" TO "service_role";
GRANT SELECT ON TABLE "pgmq"."q_discord_async_calls_dlq" TO "service_role";
GRANT UPDATE ON TABLE "pgmq"."q_discord_async_calls_dlq" TO "service_role";
GRANT DELETE ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT REFERENCES ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT TRIGGER ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT TRUNCATE ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";
GRANT UPDATE ON TABLE "pgmq"."a_discord_async_calls_dlq" TO "service_role";

-- 12. Create table to track DLQ messages (similar to github async worker)
CREATE TABLE IF NOT EXISTS public.discord_async_worker_dlq_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  original_msg_id bigint,
  method text NOT NULL,
  envelope jsonb NOT NULL,
  error_message text,
  error_type text,
  retry_count integer NOT NULL,
  last_error_context jsonb,
  class_id bigint REFERENCES public.classes(id) ON DELETE SET NULL,
  debug_id text,
  log_id bigint
);

-- Add indexes for efficient querying
CREATE INDEX IF NOT EXISTS discord_async_worker_dlq_messages_created_at_idx 
  ON public.discord_async_worker_dlq_messages(created_at DESC);

CREATE INDEX IF NOT EXISTS discord_async_worker_dlq_messages_class_id_idx 
  ON public.discord_async_worker_dlq_messages(class_id);

CREATE INDEX IF NOT EXISTS discord_async_worker_dlq_messages_method_idx 
  ON public.discord_async_worker_dlq_messages(method);

-- Enable RLS
ALTER TABLE public.discord_async_worker_dlq_messages ENABLE ROW LEVEL SECURITY;

-- Tighten grants; RLS will also apply
REVOKE ALL ON TABLE public.discord_async_worker_dlq_messages FROM anon, authenticated;
GRANT INSERT, SELECT ON TABLE public.discord_async_worker_dlq_messages TO service_role;

-- RLS policy for service_role only
DROP POLICY IF EXISTS discord_async_worker_dlq_messages_service_role_select ON public.discord_async_worker_dlq_messages;
CREATE POLICY discord_async_worker_dlq_messages_service_role_select
  ON public.discord_async_worker_dlq_messages
  FOR SELECT
  TO service_role
  USING (true);

DROP POLICY IF EXISTS discord_async_worker_dlq_messages_service_role_insert ON public.discord_async_worker_dlq_messages;
CREATE POLICY discord_async_worker_dlq_messages_service_role_insert
  ON public.discord_async_worker_dlq_messages
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- 13. Add trigger to auto-populate Discord fields from identity data
-- This mirrors how we handle GitHub identity data in update_github_profile
-- Discord identity data structure:
-- {
--   "iss": "https://discord.com/api",
--   "sub": "689831728977674240",
--   "name": "jon.bell#0",
--   "provider_id": "689831728977674240",
--   "custom_claims": { "global_name": "Jonathan Bell" },
--   ...
-- }
CREATE OR REPLACE FUNCTION public.update_discord_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    IF NEW.provider <> 'discord' THEN
      RETURN NEW;
    END IF;

    UPDATE public.users
    SET
      discord_username = json_extract_path_text(to_json(NEW.identity_data), 'name'),
      discord_id = NEW.provider_id
    WHERE user_id = NEW.user_id;
    RETURN NEW;
END;
$function$;

-- Create trigger for Discord identity changes (similar to GitHub)
DROP TRIGGER IF EXISTS update_discord_profile_trigger ON auth.identities;
CREATE TRIGGER update_discord_profile_trigger
AFTER INSERT OR UPDATE ON auth.identities
FOR EACH ROW
EXECUTE FUNCTION public.update_discord_profile();

-- Backfill discord_id and discord_username from existing auth.identities rows
UPDATE public.users u
SET 
  discord_id = i.provider_id,
  discord_username = json_extract_path_text(to_json(i.identity_data), 'name')
FROM auth.identities i
WHERE i.user_id = u.user_id
  AND i.provider = 'discord'
  AND (u.discord_id IS NULL OR u.discord_username IS NULL);

-- 14. Background invoker and cron schedule for the Discord async worker
-- Based on github-async-worker pattern: spawn 2 workers per minute
CREATE OR REPLACE FUNCTION public.invoke_discord_async_worker_background_task()
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  i integer;
BEGIN
  -- Spawn exactly 2 workers (matching github-async-worker pattern)
  FOR i IN 1..2 LOOP
    PERFORM public.call_edge_function_internal(
      '/functions/v1/discord-async-worker',
      'POST',
      '{"Content-type":"application/json","x-supabase-webhook-source":"discord-async-worker"}'::jsonb,
      '{}'::jsonb,
      3000,
      null, null, null, null, null
    );
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.invoke_discord_async_worker_background_task() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.invoke_discord_async_worker_background_task() TO service_role;

-- Idempotent cron schedule: drop if exists, then create
SELECT cron.unschedule('invoke-discord-async-worker-every-minute')
WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'invoke-discord-async-worker-every-minute');

SELECT cron.schedule(
  'invoke-discord-async-worker-every-minute',
  '* * * * *',
  $$SELECT public.invoke_discord_async_worker_background_task();$$
);

-- 15. Add comments for documentation
COMMENT ON TABLE public.discord_channels IS 'Tracks Discord channels created for classes, assignments, labs, and queues';
COMMENT ON TABLE public.discord_messages IS 'Tracks Discord messages sent for help requests and regrade requests, used for deep linking';
COMMENT ON TABLE public.discord_roles IS 'Tracks Discord roles created for classes (Student, Grader, Instructor)';
COMMENT ON COLUMN public.users.discord_id IS 'Discord user ID from OAuth (auto-populated from identity data)';
COMMENT ON COLUMN public.users.discord_username IS 'Discord username from OAuth (auto-populated from identity data)';
COMMENT ON COLUMN public.classes.discord_server_id IS 'Discord server (guild) ID for the class';
COMMENT ON COLUMN public.classes.discord_channel_group_id IS 'Discord channel category/group ID for organizing class channels';
COMMENT ON COLUMN public.discord_roles.role_type IS 'Type of role: student, grader, or instructor';
COMMENT ON FUNCTION public.invoke_discord_async_worker_background_task() IS 'Spawns Discord async worker edge functions to process queued Discord API calls';
