-- Per-guild circuit breaker and a reconciler for stuck Discord membership work.
--
-- WHY PER-GUILD, AND WHY IT MATTERS MORE HERE THAN PER-ORG DOES FOR GITHUB
--
-- The GitHub worker authenticates as a per-org installation: an org whose installation is broken
-- burns its own rate limit and nobody else's, so its circuit breaker is mostly a courtesy to that
-- org. Discord is the opposite. One bot token serves every course on the platform, and Discord's
-- primary rate limit (50 requests/second) is charged against that token, not against the guild. So a
-- single misconfigured guild -- the bot dropped from the server, its channel-view permission
-- revoked, a stale discord_server_id -- turns every enrolled student into a 403/50001 and spends the
-- whole platform's Discord budget discovering the same fact. That is not hypothetical: 557 of the
-- 594 dead-letter rows on 2026-08-11 were one guild's 403, repeated once per enrolled student.
--
-- Hence a breaker keyed on the guild. Once a guild has produced a storm of permission errors, work
-- for THAT guild is deferred and every other course keeps its share of the token.
--
-- Contents:
--   1. discord_circuit_breakers  -- breaker state, keyed (scope, key); scope is 'guild' today.
--   2. discord_async_errors      -- the per-guild error log the threshold check counts.
--   3. get_discord_circuit / open_discord_circuit / record_discord_async_error /
--      check_discord_error_threshold -- the four RPCs the worker calls, mirroring the GitHub set.
--   4. get_discord_circuit_breaker_statuses -- the gauge the metrics endpoint exports.
--   5. reconcile_stuck_discord_memberships  -- re-enqueue membership work the hourly sync lost.
--   6. invoke_discord_reconciler_background_task + a pg_cron schedule every 15 minutes.

-- ============================================================================
-- 1. Breaker state
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.discord_circuit_breakers (
  -- 'guild' today. Kept as a column rather than baked into the key so a future method-scoped
  -- breaker ('guild_method', like GitHub's 'org_method') needs no migration of this table.
  scope text NOT NULL,
  key text NOT NULL,
  state text NOT NULL DEFAULT 'closed', -- 'open' | 'closed'
  open_until timestamptz,
  last_reason text,
  trip_count integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (scope, key)
);

COMMENT ON TABLE public.discord_circuit_breakers IS
  'Per-guild Discord circuit breaker state. Open means the worker defers that guild''s operations, which protects the single shared bot token''s rate limit from one misconfigured server.';

ALTER TABLE public.discord_circuit_breakers ENABLE ROW LEVEL SECURITY;

-- No authenticated access at all, unlike discord_channels and friends. last_reason carries raw
-- Discord error text and the key is a guild snowflake; neither is anything the app renders, so
-- there is no reason for a browser-held key to reach this table.
REVOKE ALL ON TABLE public.discord_circuit_breakers FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.discord_circuit_breakers TO service_role;

DROP POLICY IF EXISTS "discord_circuit_breakers_service_role_all" ON public.discord_circuit_breakers;
CREATE POLICY "discord_circuit_breakers_service_role_all"
ON public.discord_circuit_breakers
AS permissive
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ============================================================================
-- 2. The error log the threshold reads
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.discord_async_errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- github_async_errors calls this column `org`; the Discord equivalent of an org is the guild.
  guild_id text NOT NULL,
  method text NOT NULL,
  error_data jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.discord_async_errors IS
  'Discord async worker failures that count toward the per-guild circuit breaker (bot permission and configuration errors). Trimmed to 7 days by cleanup_discord_async_errors().';

-- The threshold check is always "this guild, this window", so the composite index is the one that
-- matters; the created_at index serves the daily cleanup.
CREATE INDEX IF NOT EXISTS idx_discord_async_errors_guild_created_at
  ON public.discord_async_errors (guild_id, created_at);
CREATE INDEX IF NOT EXISTS idx_discord_async_errors_created_at
  ON public.discord_async_errors (created_at);

ALTER TABLE public.discord_async_errors ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.discord_async_errors FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.discord_async_errors TO service_role;

DROP POLICY IF EXISTS "discord_async_errors_service_role_all" ON public.discord_async_errors;
CREATE POLICY "discord_async_errors_service_role_all"
ON public.discord_async_errors
AS permissive
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ============================================================================
-- 3. The RPCs the worker calls
-- ============================================================================

-- Read a breaker. Returns no row when the guild has never tripped, which the caller reads as closed.
CREATE OR REPLACE FUNCTION public.get_discord_circuit(
  p_scope text,
  p_key text
) RETURNS TABLE (state text, open_until timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT cb.state, cb.open_until
  FROM public.discord_circuit_breakers cb
  WHERE cb.scope = p_scope AND cb.key = p_key;
$$;

-- anon and authenticated are named explicitly, not left to a PUBLIC-only revoke: Supabase grants
-- EXECUTE to both as their own ACL entries at CREATE time, so revoking PUBLIC removes nothing.
REVOKE ALL ON FUNCTION public.get_discord_circuit(text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_discord_circuit(text, text) TO service_role;

-- Open (or extend) a breaker, and return the guild's trip count.
--
-- Escalation is deliberately gentler than the GitHub version's 24-hour third strike. A Discord
-- permission storm is fixed by a server admin flipping one setting, and an over-long window means a
-- course that has been repaired waits hours for its roles -- while the cost of reopening early is
-- only one more storm's worth of deferrals.
CREATE OR REPLACE FUNCTION public.open_discord_circuit(
  p_scope text,
  p_key text,
  p_event text, -- 'permission_storm' | 'rate_limit' | anything else (uses p_retry_after_seconds)
  p_retry_after_seconds integer DEFAULT NULL,
  p_reason text DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row public.discord_circuit_breakers%rowtype;
  v_base_seconds integer;
  v_trip_count integer;
  v_lock_key bigint;
BEGIN
  -- Serialize per (scope, key). Four envelopes are processed in parallel per worker and two workers
  -- run per minute, so without this the first trip for a guild is a lost-update race between
  -- concurrent INSERTs and the trip count silently stops incrementing.
  v_lock_key := ('x' || substr(md5(p_scope || '|' || p_key), 1, 16))::bit(64)::bigint;
  PERFORM pg_advisory_xact_lock(v_lock_key);

  SELECT * INTO v_row
  FROM public.discord_circuit_breakers
  WHERE scope = p_scope AND key = p_key
  FOR UPDATE;

  IF p_event = 'permission_storm' THEN
    v_base_seconds := COALESCE(p_retry_after_seconds, 1800); -- 30m: needs a Discord admin to act
  ELSIF p_event = 'rate_limit' THEN
    v_base_seconds := COALESCE(p_retry_after_seconds, 60);
  ELSE
    v_base_seconds := COALESCE(p_retry_after_seconds, 300);
  END IF;

  IF NOT FOUND THEN
    INSERT INTO public.discord_circuit_breakers (scope, key, state, open_until, last_reason, trip_count, updated_at)
    VALUES (p_scope, p_key, 'open', now() + make_interval(secs => v_base_seconds), p_reason, 1, now());
    RETURN 1;
  END IF;

  IF v_row.state = 'open' AND (v_row.open_until IS NULL OR v_row.open_until > now()) THEN
    -- Already open: this is the same storm, not a new trip. The window is never shortened, so a
    -- later short event (a 60s rate limit) cannot cut a 30-minute permission window short.
    UPDATE public.discord_circuit_breakers
    SET open_until = GREATEST(COALESCE(v_row.open_until, now()), now() + make_interval(secs => v_base_seconds)),
        last_reason = COALESCE(p_reason, v_row.last_reason),
        updated_at = now()
    WHERE scope = p_scope AND key = p_key;
    RETURN v_row.trip_count;
  END IF;

  -- Closed, or open with an expired window: a new trip. Repeat offenders back off further, capped at
  -- six hours so a guild is always retried within one working day.
  v_trip_count := v_row.trip_count + 1;
  v_base_seconds := LEAST(21600, (v_base_seconds * power(2, LEAST(v_trip_count - 1, 4)))::integer);

  UPDATE public.discord_circuit_breakers
  SET state = 'open',
      open_until = now() + make_interval(secs => v_base_seconds),
      last_reason = COALESCE(p_reason, v_row.last_reason),
      trip_count = v_trip_count,
      updated_at = now()
  WHERE scope = p_scope AND key = p_key;

  RETURN v_trip_count;
END;
$$;

REVOKE ALL ON FUNCTION public.open_discord_circuit(text, text, text, integer, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.open_discord_circuit(text, text, text, integer, text) TO service_role;

-- Log one failure against a guild.
CREATE OR REPLACE FUNCTION public.record_discord_async_error(
  p_guild_id text,
  p_method text,
  p_error_data jsonb
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.discord_async_errors (guild_id, method, error_data)
  VALUES (p_guild_id, p_method, p_error_data);
END;
$$;

REVOKE ALL ON FUNCTION public.record_discord_async_error(text, text, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_discord_async_error(text, text, jsonb) TO service_role;

-- How many failures this guild has logged inside the window.
--
-- The GitHub twin takes a p_threshold argument and ignores it -- the caller compares the returned
-- count itself -- so it is not carried over here. The comparison stays in the worker, where the
-- threshold is next to the code that acts on it.
CREATE OR REPLACE FUNCTION public.check_discord_error_threshold(
  p_guild_id text,
  p_window_minutes integer DEFAULT 5
) RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT count(*)::integer
  FROM public.discord_async_errors
  WHERE guild_id = p_guild_id
    AND created_at >= now() - make_interval(mins => p_window_minutes);
$$;

REVOKE ALL ON FUNCTION public.check_discord_error_threshold(text, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_discord_error_threshold(text, integer) TO service_role;

-- Bounded growth, matching cleanup_github_async_errors. The breaker only ever reads a few minutes of
-- history; everything older is kept just long enough to explain a page after the fact.
CREATE OR REPLACE FUNCTION public.cleanup_discord_async_errors()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  DELETE FROM public.discord_async_errors
  WHERE created_at < now() - interval '7 days';
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_discord_async_errors() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_discord_async_errors() TO service_role;

SELECT cron.unschedule('cleanup-discord-async-errors-daily')
WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'cleanup-discord-async-errors-daily');

SELECT cron.schedule(
  'cleanup-discord-async-errors-daily',
  '20 2 * * *', -- 02:20 UTC, twenty minutes after the GitHub equivalent so they do not overlap
  $$SELECT public.cleanup_discord_async_errors();$$
);

-- ============================================================================
-- 4. The gauge the metrics endpoint exports
-- ============================================================================

-- Deliberately a separate function from get_circuit_breaker_statuses() rather than a UNION inside
-- it: that one is the GitHub breaker's gauge, alerts are written against its label set, and the two
-- breakers have different remediations (a GitHub installation vs a Discord server admin).
CREATE OR REPLACE FUNCTION public.get_discord_circuit_breaker_statuses()
RETURNS TABLE (
  scope text,
  key text,
  is_open boolean,
  state text,
  open_until timestamptz,
  trip_count integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    cb.scope,
    cb.key,
    (cb.state = 'open' AND (cb.open_until IS NULL OR cb.open_until >= now())) AS is_open,
    cb.state,
    cb.open_until,
    cb.trip_count
  FROM public.discord_circuit_breakers cb
  ORDER BY cb.scope, cb.key;
$$;

REVOKE ALL ON FUNCTION public.get_discord_circuit_breaker_statuses() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_discord_circuit_breaker_statuses() TO service_role;

-- ============================================================================
-- 5. Reconciler: re-enqueue membership work that was lost
-- ============================================================================

-- The safety net for Discord membership work that no longer has anything behind it.
--
-- The hourly batch role sync is the only thing that observes membership, and its whole sweep is a
-- single queue message. If that message is dropped -- an isolate killed mid-run, an envelope
-- dead-lettered, a rate-limit requeue that outlives its retry ceiling -- nothing re-observes those
-- users and their status rows simply stop being updated. Nothing in the product notices, because a
-- stale not_joined row looks exactly like a fresh one.
--
-- So this deliberately keys on STALENESS, not on state. A candidate whose row was refreshed within
-- the window is being handled and is left alone; that is what keeps this from duplicating the hourly
-- sync's Discord calls four times an hour, which would be worse than the failure it repairs. The
-- default window is three missed passes.
--
-- Not re-enqueued:
--   * in_guild        -- already done.
--   * cannot_invite   -- terminal until a Discord admin acts, exactly as a repository with a
--                        creation_error is terminal for reconcile_stuck_repo_creations(). The >12h
--                        Sentry alert in the discord-reconciler edge function is what covers these.
--   * guilds with an open circuit breaker -- we are already backing that guild off on purpose.
--   * users with an add_member_role already queued -- the work is in flight.
--   * classes whose Discord role for the user's role type is missing -- enqueue_discord_role_sync()
--     returns silently in that case, so counting them would report work that never happened.
--     request_discord_reinvite() repairs those; this function only reports honestly.
CREATE OR REPLACE FUNCTION public.reconcile_stuck_discord_memberships(
  p_stale_minutes integer DEFAULT 180,
  p_limit integer DEFAULT 200
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  r record;
  v_count integer := 0;
BEGIN
  FOR r IN
    WITH queued AS (
      -- One pass over the queue instead of an EXISTS per candidate. pgmq's q_* tables are indexed on
      -- msg_id and vt only, so a per-row probe would be one sequential scan per candidate over the
      -- highest-churn table in the database.
      SELECT DISTINCT
        q.message -> 'args' ->> 'guild_id' AS guild_id,
        q.message -> 'args' ->> 'user_id' AS discord_user_id
      FROM pgmq.q_discord_async_calls q
      WHERE q.message ->> 'method' = 'add_member_role'
    )
    SELECT ur.user_id, ur.class_id, ur.role, dms.id AS status_id
    FROM public.user_roles ur
    JOIN public.classes c ON c.id = ur.class_id
    JOIN public.users u ON u.user_id = ur.user_id
    LEFT JOIN public.discord_membership_status dms
      ON dms.class_id = ur.class_id
     AND dms.user_id = ur.user_id
     AND dms.guild_id = c.discord_server_id
    WHERE ur.disabled = false
      AND u.discord_id IS NOT NULL
      AND c.discord_server_id IS NOT NULL
      -- Same active-class scoping as get_discord_role_sync_candidates(). A class that has ended is
      -- not stuck, it is finished, and its students are reached by the manual retry button instead.
      AND public.is_class_active(c.archived, c.end_date)
      AND (dms.id IS NULL OR dms.state = 'not_joined')
      -- With no status row at all there is no observation to age, so user_roles.updated_at stands in
      -- for "not brand new": an enrollment created a minute ago already has an add_member_role in
      -- flight from its own trigger, and the queue check below cannot see that message once a worker
      -- has read it. user_roles has no created_at column, and its updated_at is stamped by a BEFORE
      -- UPDATE trigger, so an unrelated edit (a section move) postpones this user by one window --
      -- the cheap error, since the edit itself re-enqueues their role sync.
      AND COALESCE(dms.last_observed_at, ur.updated_at) < now() - make_interval(mins => p_stale_minutes)
      -- Do not fight a human. request_discord_reinvite() stamps this, and a reconciler pass that
      -- re-enqueued on top of it would double the Discord work for the students an instructor is
      -- already retrying.
      AND (dms.last_retry_requested_at IS NULL
           OR dms.last_retry_requested_at < now() - make_interval(mins => p_stale_minutes))
      AND EXISTS (
        SELECT 1 FROM public.discord_roles dr
        WHERE dr.class_id = ur.class_id AND dr.role_type = ur.role::text
      )
      AND NOT EXISTS (
        SELECT 1 FROM queued qd
        WHERE qd.guild_id = c.discord_server_id AND qd.discord_user_id = u.discord_id
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.discord_circuit_breakers cb
        WHERE cb.scope = 'guild'
          AND cb.key = c.discord_server_id
          AND cb.state = 'open'
          AND (cb.open_until IS NULL OR cb.open_until > now())
      )
    -- Oldest observation first, so a bounded pass makes progress on the worst cases rather than
    -- re-picking the same arbitrary set each time.
    ORDER BY COALESCE(dms.last_observed_at, ur.updated_at) ASC
    LIMIT GREATEST(p_limit, 0)
  LOOP
    BEGIN
      PERFORM public.enqueue_discord_role_sync(r.user_id, r.class_id, r.role, 'add');

      IF r.status_id IS NOT NULL THEN
        UPDATE public.discord_membership_status
        SET last_retry_requested_at = now()
        WHERE id = r.status_id;
      END IF;

      v_count := v_count + 1;
    EXCEPTION
      WHEN others THEN
        -- One bad candidate must not abort the pass; the next run picks it up again.
        RAISE WARNING 'reconcile_stuck_discord_memberships: failed for user % in class %: %',
          r.user_id, r.class_id, sqlerrm;
    END;
  END LOOP;

  RETURN v_count;
END;
$$;

COMMENT ON FUNCTION public.reconcile_stuck_discord_memberships(integer, integer) IS
  'Re-enqueue Discord membership checks for active-class users whose membership status has gone unobserved for p_stale_minutes, skipping terminal (cannot_invite) rows, guilds with an open circuit breaker, and work already queued. Returns how many were enqueued.';

REVOKE ALL ON FUNCTION public.reconcile_stuck_discord_memberships(integer, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reconcile_stuck_discord_memberships(integer, integer) TO service_role;

-- ============================================================================
-- 6. Cron: invoke the reconciler edge function every 15 minutes
-- ============================================================================

-- The edge function calls reconcile_stuck_discord_memberships() and emits the >12h Sentry alerts,
-- which plpgsql cannot do. Same shape as invoke_github_repo_reconciler_background_task().
CREATE OR REPLACE FUNCTION public.invoke_discord_reconciler_background_task()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.call_edge_function_internal(
    '/functions/v1/discord-reconciler',
    'POST',
    '{"Content-type":"application/json","x-supabase-webhook-source":"discord-reconciler"}'::jsonb,
    '{}'::jsonb,
    5000,
    null, null, null, null, null
  );
END;
$$;

REVOKE ALL ON FUNCTION public.invoke_discord_reconciler_background_task() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.invoke_discord_reconciler_background_task() TO service_role;

DO $cron$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'discord-reconciler') THEN
      PERFORM cron.unschedule('discord-reconciler');
    END IF;
    PERFORM cron.schedule(
      'discord-reconciler',
      -- Offset from the hourly batch role sync (minute 0) so a reconciler pass never reads the
      -- status rows the sync is in the middle of rewriting.
      '7-52/15 * * * *',
      $$SELECT public.invoke_discord_reconciler_background_task();$$
    );
    RAISE NOTICE 'Discord reconciler cron scheduled every 15 minutes';
  END IF;
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Skipping discord-reconciler cron schedule: insufficient privilege';
END;
$cron$;
