-- LTI 1.3 Integration
--
-- Pawtograder acts as an LTI 1.3 Tool. This migration adds the data model for:
--   * Registered LMS platforms and deployments (lti_platforms, lti_deployments)
--   * Our tool's signing keypairs (lti_tool_keys) -- JWKS published at /api/lti/jwks
--   * Course linkage captured at launch (lti_context_links) with NRPS/AGS endpoints
--   * Assignment <-> AGS line item mapping (lti_line_items)
--   * LTI identity <-> Pawtograder user mapping (lti_users)
--   * Single-use OIDC nonces for replay protection (lti_nonces)
--
-- Authorization model:
--   * Platform/key tables are platform-admin managed (authorize_for_admin()).
--   * Per-course tables are readable by instructors of the class and fully
--     managed by the service role (the Next.js LTI endpoints run with service role).
--   * Roster sync reuses the existing public.sis_sync_enrollment(...) RPC.
--
-- All LTI HTTP/crypto logic lives in Next.js (lib/lti + app/api/lti). See
-- docs/lti-1.3-integration.md.

-------------------------------------------------------------------------------
-- 1. Platforms
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_platforms" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "name" text NOT NULL,
    "issuer" text NOT NULL,            -- platform iss claim, e.g. https://canvas.instructure.com
    "client_id" text NOT NULL,         -- our tool's client_id on the platform (= id_token aud)
    "auth_login_url" text NOT NULL,    -- OIDC authentication endpoint (we redirect here on login)
    "token_url" text NOT NULL,         -- OAuth2 token endpoint (client_credentials for NRPS/AGS)
    "jwks_url" text NOT NULL,          -- platform JWKS (we verify id_token signatures against this)
    "enabled" boolean DEFAULT true NOT NULL,
    -- A platform may expose the same issuer for multiple client_ids (rare); the
    -- (issuer, client_id) pair is the unique key per LTI 1.3 core.
    CONSTRAINT "lti_platforms_issuer_client_unique" UNIQUE ("issuer", "client_id")
);

ALTER TABLE "public"."lti_platforms" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."lti_platforms" TO "service_role";

CREATE POLICY "Admins manage lti_platforms" ON "public"."lti_platforms"
    FOR ALL USING (authorize_for_admin()) WITH CHECK (authorize_for_admin());
CREATE POLICY "Service role manages lti_platforms" ON "public"."lti_platforms"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-------------------------------------------------------------------------------
-- 2. Deployments  (an install of our tool within a platform account/course)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_deployments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "platform_id" bigint NOT NULL REFERENCES "public"."lti_platforms"("id") ON DELETE CASCADE,
    "deployment_id" text NOT NULL,     -- https://purl.imsglobal.org/spec/lti/claim/deployment_id
    "name" text,
    CONSTRAINT "lti_deployments_unique" UNIQUE ("platform_id", "deployment_id")
);

ALTER TABLE "public"."lti_deployments" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_deployments" TO "authenticated";
GRANT ALL ON TABLE "public"."lti_deployments" TO "service_role";

CREATE POLICY "Admins manage lti_deployments" ON "public"."lti_deployments"
    FOR ALL USING (authorize_for_admin()) WITH CHECK (authorize_for_admin());
CREATE POLICY "Service role manages lti_deployments" ON "public"."lti_deployments"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-------------------------------------------------------------------------------
-- 3. Tool signing keys  (our keypairs; public half published as JWKS)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_tool_keys" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "kid" text NOT NULL UNIQUE,                 -- key id, surfaced in JWKS + JWT header
    "alg" text NOT NULL DEFAULT 'RS256',
    "public_jwk" jsonb NOT NULL,                -- published at /api/lti/jwks
    "private_key_pem_encrypted" text NOT NULL,  -- AES-GCM(base64) under LTI_KEY_ENCRYPTION_SECRET
    "retired_at" timestamp with time zone       -- when set, still published for verification but not used to sign
);

ALTER TABLE "public"."lti_tool_keys" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_tool_keys" TO "service_role";
-- Private keys never leave the server role. Authenticated users get nothing here;
-- the public JWKS is served by an endpoint using the service role.

CREATE POLICY "Service role manages lti_tool_keys" ON "public"."lti_tool_keys"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-------------------------------------------------------------------------------
-- 4. Context links  (LMS course/section -> Pawtograder class)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_context_links" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "platform_id" bigint NOT NULL REFERENCES "public"."lti_platforms"("id") ON DELETE CASCADE,
    "deployment_id" text NOT NULL,
    "context_id" text NOT NULL,                 -- LTI context (course) id on the platform
    "context_label" text,
    "context_title" text,
    "class_id" bigint REFERENCES "public"."classes"("id") ON DELETE CASCADE,
    -- Service endpoints discovered from launch claims:
    "nrps_url" text,                            -- context_memberships_url (NRPS)
    "ags_lineitems_url" text,                   -- AGS lineitems collection endpoint
    "ags_scopes" text[] DEFAULT '{}'::text[],   -- granted AGS scopes from the launch
    "roster_sync_enabled" boolean DEFAULT false NOT NULL,
    "grade_sync_enabled" boolean DEFAULT false NOT NULL,
    "last_roster_sync_at" timestamp with time zone,
    "last_roster_sync_status" text,
    "last_roster_sync_message" text,
    CONSTRAINT "lti_context_links_unique" UNIQUE ("platform_id", "deployment_id", "context_id"),
    -- Tie each context link to a real deployment (launch upserts the deployment
    -- first), preventing orphaned/mismatched (platform_id, deployment_id) pairs.
    CONSTRAINT "lti_context_links_deployment_fkey"
      FOREIGN KEY ("platform_id", "deployment_id")
      REFERENCES "public"."lti_deployments" ("platform_id", "deployment_id") ON DELETE CASCADE
);

ALTER TABLE "public"."lti_context_links" ENABLE ROW LEVEL SECURITY;
-- The server reads nrps_url / ags_lineitems_url from this table and uses them as
-- outbound request targets with a bearer service token. Instructors must NOT be
-- able to repoint those (SSRF / token exfiltration), so grant them only the two
-- sync toggles; service_role (the launch/sync endpoints) manages the rest.
GRANT SELECT ON TABLE "public"."lti_context_links" TO "authenticated";
GRANT UPDATE ("roster_sync_enabled", "grade_sync_enabled") ON TABLE "public"."lti_context_links" TO "authenticated";
GRANT ALL ON TABLE "public"."lti_context_links" TO "service_role";

CREATE POLICY "Instructors read lti_context_links" ON "public"."lti_context_links"
    FOR SELECT USING (
        class_id IS NOT NULL AND public.authorizeforclassinstructor(class_id)
    );
CREATE POLICY "Instructors toggle lti_context_links sync" ON "public"."lti_context_links"
    FOR UPDATE USING (
        class_id IS NOT NULL AND public.authorizeforclassinstructor(class_id)
    ) WITH CHECK (
        class_id IS NOT NULL AND public.authorizeforclassinstructor(class_id)
    );
CREATE POLICY "Admins manage lti_context_links" ON "public"."lti_context_links"
    FOR ALL USING (authorize_for_admin()) WITH CHECK (authorize_for_admin());
CREATE POLICY "Service role manages lti_context_links" ON "public"."lti_context_links"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS "lti_context_links_class_id_idx" ON "public"."lti_context_links" ("class_id");

-------------------------------------------------------------------------------
-- 5. Line items  (Pawtograder assignment/column <-> AGS line item)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_line_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "context_link_id" bigint NOT NULL REFERENCES "public"."lti_context_links"("id") ON DELETE CASCADE,
    "class_id" bigint NOT NULL REFERENCES "public"."classes"("id") ON DELETE CASCADE,
    "assignment_id" bigint REFERENCES "public"."assignments"("id") ON DELETE CASCADE,
    "gradebook_column_id" bigint REFERENCES "public"."gradebook_columns"("id") ON DELETE CASCADE,
    "line_item_url" text NOT NULL,             -- AGS line item resource URL on the platform
    "label" text,
    "score_maximum" numeric,
    "last_pushed_at" timestamp with time zone,
    CONSTRAINT "lti_line_items_target_chk" CHECK (
        assignment_id IS NOT NULL OR gradebook_column_id IS NOT NULL
    ),
    CONSTRAINT "lti_line_items_assignment_unique" UNIQUE ("context_link_id", "assignment_id"),
    CONSTRAINT "lti_line_items_column_unique" UNIQUE ("context_link_id", "gradebook_column_id")
);

ALTER TABLE "public"."lti_line_items" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_line_items" TO "authenticated";
GRANT ALL ON TABLE "public"."lti_line_items" TO "service_role";

CREATE POLICY "Instructors read lti_line_items" ON "public"."lti_line_items"
    FOR SELECT USING (public.authorizeforclassinstructor(class_id));
CREATE POLICY "Admins manage lti_line_items" ON "public"."lti_line_items"
    FOR ALL USING (authorize_for_admin()) WITH CHECK (authorize_for_admin());
CREATE POLICY "Service role manages lti_line_items" ON "public"."lti_line_items"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS "lti_line_items_class_id_idx" ON "public"."lti_line_items" ("class_id");

-------------------------------------------------------------------------------
-- 6. LTI users  (platform identity <-> Pawtograder user)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "platform_id" bigint NOT NULL REFERENCES "public"."lti_platforms"("id") ON DELETE CASCADE,
    "sub" text NOT NULL,                        -- LTI subject (stable per-platform user id)
    "user_id" uuid REFERENCES "public"."users"("user_id") ON DELETE SET NULL,
    "lis_person_sourcedid" text,               -- institutional/SIS id when provided
    "email" text,
    "name" text,
    CONSTRAINT "lti_users_unique" UNIQUE ("platform_id", "sub")
);

ALTER TABLE "public"."lti_users" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_users" TO "service_role";
GRANT SELECT ON TABLE "public"."lti_users" TO "authenticated";

CREATE POLICY "Admins read lti_users" ON "public"."lti_users"
    FOR SELECT USING (authorize_for_admin());
CREATE POLICY "Service role manages lti_users" ON "public"."lti_users"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS "lti_users_user_id_idx" ON "public"."lti_users" ("user_id");

-------------------------------------------------------------------------------
-- 7. Nonces  (single-use, OIDC replay protection)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_nonces" (
    "nonce" text PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "expires_at" timestamp with time zone NOT NULL
);

ALTER TABLE "public"."lti_nonces" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_nonces" TO "service_role";
CREATE POLICY "Service role manages lti_nonces" ON "public"."lti_nonces"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS "lti_nonces_expires_at_idx" ON "public"."lti_nonces" ("expires_at");

-- Consume a nonce atomically: returns true if it was unused (and stores it),
-- false if it was already present (replay). TTL-prunes expired nonces.
CREATE OR REPLACE FUNCTION public.lti_consume_nonce(p_nonce text, p_ttl_seconds integer DEFAULT 600)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    v_rows bigint := 0;
BEGIN
    DELETE FROM public.lti_nonces WHERE expires_at < now();
    INSERT INTO public.lti_nonces (nonce, expires_at)
    VALUES (p_nonce, now() + make_interval(secs => p_ttl_seconds))
    ON CONFLICT (nonce) DO NOTHING;
    -- ROW_COUNT is bigint; capture it explicitly and derive the boolean.
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN v_rows > 0;
END;
$$;

REVOKE ALL ON FUNCTION public.lti_consume_nonce(text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lti_consume_nonce(text, integer) TO service_role;

-------------------------------------------------------------------------------
-- 8. New columns on existing tables
-------------------------------------------------------------------------------
-- Link class sections to an LTI context (used to scope NRPS section mapping).
ALTER TABLE "public"."class_sections"
    ADD COLUMN IF NOT EXISTS "lti_context_id" text;

-------------------------------------------------------------------------------
-- 9. Admin RPCs for platform registration
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_upsert_lti_platform(
    p_id bigint,
    p_name text,
    p_issuer text,
    p_client_id text,
    p_auth_login_url text,
    p_token_url text,
    p_jwks_url text,
    p_enabled boolean DEFAULT true
)
RETURNS public.lti_platforms
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    v_row public.lti_platforms;
BEGIN
    IF NOT public.authorize_for_admin() THEN
        RAISE EXCEPTION 'Access denied: admin role required';
    END IF;

    IF p_id IS NULL THEN
        INSERT INTO public.lti_platforms (name, issuer, client_id, auth_login_url, token_url, jwks_url, enabled)
        VALUES (p_name, p_issuer, p_client_id, p_auth_login_url, p_token_url, p_jwks_url, COALESCE(p_enabled, true))
        RETURNING * INTO v_row;
    ELSE
        UPDATE public.lti_platforms
        SET name = p_name, issuer = p_issuer, client_id = p_client_id,
            auth_login_url = p_auth_login_url, token_url = p_token_url,
            jwks_url = p_jwks_url, enabled = COALESCE(p_enabled, true), updated_at = now()
        WHERE id = p_id
        RETURNING * INTO v_row;
    END IF;

    RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_upsert_lti_platform(bigint, text, text, text, text, text, text, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_upsert_lti_platform(bigint, text, text, text, text, text, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_lti_platform(bigint, text, text, text, text, text, text, boolean) TO service_role;

CREATE OR REPLACE FUNCTION public.admin_delete_lti_platform(p_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
BEGIN
    IF NOT public.authorize_for_admin() THEN
        RAISE EXCEPTION 'Access denied: admin role required';
    END IF;
    DELETE FROM public.lti_platforms WHERE id = p_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_delete_lti_platform(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_delete_lti_platform(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_lti_platform(bigint) TO service_role;

-------------------------------------------------------------------------------
-- 10. Roster sync trigger (pg_cron -> Next.js /api/lti/sync-roster)
--
-- Mirrors the SIS hourly cron. The Next.js endpoint authenticates the call with
-- the LTI_CRON_SHARED_SECRET header. URL + secret are read from DB settings:
--   ALTER DATABASE postgres SET app.settings.app_url = 'https://app...';
--   ALTER DATABASE postgres SET app.settings.lti_cron_secret = '...';
-- If unset, the function no-ops so the migration is safe in all environments.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trigger_lti_roster_sync()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    v_url text := current_setting('app.settings.app_url', true);
    v_secret text := current_setting('app.settings.lti_cron_secret', true);
BEGIN
    IF v_url IS NULL OR v_url = '' THEN
        RAISE NOTICE 'LTI roster sync skipped: app.settings.app_url not configured';
        RETURN;
    END IF;

    -- Fire-and-forget POST; the endpoint enumerates roster_sync_enabled contexts.
    PERFORM net.http_post(
        url := v_url || '/api/lti/sync-roster',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-lti-cron-secret', COALESCE(v_secret, '')
        ),
        body := '{"all": true}'::jsonb
    );
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'LTI roster sync trigger failed: %', SQLERRM;
END;
$$;

REVOKE ALL ON FUNCTION public.trigger_lti_roster_sync() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.trigger_lti_roster_sync() TO service_role;
GRANT EXECUTE ON FUNCTION public.trigger_lti_roster_sync() TO postgres;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        -- Run at :45 past the hour to avoid colliding with the SIS job (:15).
        PERFORM cron.schedule(
            'lti-roster-sync',
            '45 * * * *',
            'SELECT public.trigger_lti_roster_sync();'
        );
        RAISE NOTICE 'LTI roster sync cron scheduled hourly at :45';
    ELSE
        RAISE NOTICE 'pg_cron not available; skipping LTI roster sync schedule';
    END IF;
END;
$$;

-------------------------------------------------------------------------------
-- 11. Touch updated_at triggers
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lti_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path TO '' AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER "lti_platforms_touch" BEFORE UPDATE ON "public"."lti_platforms"
    FOR EACH ROW EXECUTE FUNCTION public.lti_touch_updated_at();
CREATE TRIGGER "lti_context_links_touch" BEFORE UPDATE ON "public"."lti_context_links"
    FOR EACH ROW EXECUTE FUNCTION public.lti_touch_updated_at();
CREATE TRIGGER "lti_line_items_touch" BEFORE UPDATE ON "public"."lti_line_items"
    FOR EACH ROW EXECUTE FUNCTION public.lti_touch_updated_at();
CREATE TRIGGER "lti_users_touch" BEFORE UPDATE ON "public"."lti_users"
    FOR EACH ROW EXECUTE FUNCTION public.lti_touch_updated_at();
