-- Discord role sync: stop retrying non-retriable failures, and scope recurring
-- per-class work to classes that are actually running.
--
-- Background: the hourly batch role sync enqueued an add_member_role operation for
-- every enrolled user in every class with a Discord server, including users who had
-- never joined the server. For those users the operation could never succeed: the
-- member lookup 404s, the invite fallback 403s ("Missing Access"), and after 5
-- retries the message dead-lettered -- only to be re-enqueued the next hour. Two
-- permanent conditions were being retried as if they were transient.
--
-- This migration adds:
--   1. is_class_active() -- the predicate recurring per-class work should scope on.
--   2. discord_membership_status -- one row per (class, user) recording the terminal
--      outcome of a membership check, so it is recorded once instead of retried, and
--      is visible to instructors on the roster.
--   3. get_discord_role_sync_candidates() -- the batch sync's candidate query, scoped
--      to active classes.
--   4. record_discord_membership_status() -- worker-side upsert of that outcome.
--   5. get_discord_membership_status_for_class() -- the instructor-facing read.
--   6. A reschedule of discord-discussion-stats-update so its URL is resolved from
--      the vault at run time rather than baked in when the migration ran.

-- ============================================================================
-- 1. Active-class predicate
-- ============================================================================

-- A class is "active" when it has not been archived and its end date has not passed.
-- Archived alone is not a sufficient filter: in practice most classes that have ended
-- are never archived, so scoping on archived leaves nearly all inactive classes in
-- scope for recurring work.
--
-- The 30-day grace period keeps sync running through the grading and grade-appeal
-- windows that outlive the last class meeting.
CREATE OR REPLACE FUNCTION public.is_class_active(p_archived boolean, p_end_date date)
RETURNS boolean
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = ''
AS $$
  SELECT COALESCE(p_archived, false) = false
     AND (p_end_date IS NULL OR p_end_date >= CURRENT_DATE - INTERVAL '30 days');
$$;

COMMENT ON FUNCTION public.is_class_active(boolean, date) IS
  'True when a class is still running (not archived, end_date not more than 30 days past). Use this to scope recurring per-class work; archived = false alone is not sufficient.';

GRANT EXECUTE ON FUNCTION public.is_class_active(boolean, date) TO authenticated, service_role;

-- ============================================================================
-- 2. Discord membership status
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'discord_membership_state') THEN
    CREATE TYPE public.discord_membership_state AS ENUM (
      -- The user is in the guild; roles can be synced normally.
      'in_guild',
      -- The user has not joined the guild. Resolves only when the user acts, so there
      -- is nothing to retry. Normal and self-resolving.
      'not_joined',
      -- The user has not joined and the bot cannot create an invite for them, usually
      -- because it lacks permission to list the guild's channels. Resolves only when
      -- a Discord admin acts.
      'cannot_invite'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.discord_membership_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id bigint NOT NULL REFERENCES public.classes (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users (user_id) ON DELETE CASCADE,
  guild_id text NOT NULL,
  state public.discord_membership_state NOT NULL,
  -- The Discord API error code behind a cannot_invite state (e.g. 50001 Missing
  -- Access), for distinguishing a permissions problem from a transient one.
  discord_error_code integer,
  detail text,
  -- How many consecutive checks have observed this state. Bounded work: this counts
  -- observations of a recorded fact rather than retries of a failing operation.
  observed_count integer NOT NULL DEFAULT 1,
  first_observed_at timestamptz NOT NULL DEFAULT now(),
  last_observed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT discord_membership_status_unique UNIQUE (class_id, user_id, guild_id)
);

COMMENT ON TABLE public.discord_membership_status IS
  'Terminal outcome of the most recent Discord guild membership check per (class, user). Written by the batch role sync instead of re-enqueueing operations that cannot succeed; read by the instructor roster.';

CREATE INDEX IF NOT EXISTS idx_discord_membership_status_class_state
  ON public.discord_membership_status (class_id, state);

ALTER TABLE public.discord_membership_status ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "discord_membership_status_service_role_all" ON public.discord_membership_status;
CREATE POLICY "discord_membership_status_service_role_all"
ON public.discord_membership_status
AS permissive
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "discord_membership_status_staff_select" ON public.discord_membership_status;
CREATE POLICY "discord_membership_status_staff_select"
ON public.discord_membership_status
AS permissive
FOR SELECT
TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.user_roles ur
  WHERE ur.class_id = discord_membership_status.class_id
    AND ur.user_id = auth.uid()
    -- A staff member whose enrollment has been disabled must lose access. `detail` can
    -- carry an outstanding invite URL, and authorizeforclassgrader() excludes disabled
    -- roles, so a policy that ignored the flag would be the looser of the two paths.
    AND ur.disabled = false
    AND ur.role = ANY (ARRAY['instructor'::public.app_role, 'grader'::public.app_role])
));

DROP POLICY IF EXISTS "discord_membership_status_user_select" ON public.discord_membership_status;
CREATE POLICY "discord_membership_status_user_select"
ON public.discord_membership_status
AS permissive
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- ============================================================================
-- 3. Candidate query for the batch role sync, scoped to active classes
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_discord_role_sync_candidates()
RETURNS TABLE (
  user_id uuid,
  class_id bigint,
  -- The enum, not text: the worker feeds this straight back into
  -- enqueue_discord_role_sync(), which takes an app_role.
  role public.app_role,
  discord_id text,
  discord_server_id text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    ur.user_id,
    c.id AS class_id,
    ur.role,
    u.discord_id,
    c.discord_server_id
  FROM public.user_roles ur
  JOIN public.classes c ON c.id = ur.class_id
  JOIN public.users u ON u.user_id = ur.user_id
  WHERE ur.disabled = false
    AND u.discord_id IS NOT NULL
    AND c.discord_server_id IS NOT NULL
    AND public.is_class_active(c.archived, c.end_date);
$$;

COMMENT ON FUNCTION public.get_discord_role_sync_candidates() IS
  'User-role records eligible for Discord role sync, scoped to active classes. Replaces the unscoped query the batch worker used to run against all 650 classes.';

REVOKE ALL ON FUNCTION public.get_discord_role_sync_candidates() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_discord_role_sync_candidates() TO service_role;

-- ============================================================================
-- 4. Worker-side record of a terminal membership outcome
-- ============================================================================

CREATE OR REPLACE FUNCTION public.record_discord_membership_status(
  p_class_id bigint,
  p_user_id uuid,
  p_guild_id text,
  p_state public.discord_membership_state,
  p_discord_error_code integer DEFAULT NULL,
  p_detail text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.discord_membership_status AS dms (
    class_id, user_id, guild_id, state, discord_error_code, detail
  )
  VALUES (p_class_id, p_user_id, p_guild_id, p_state, p_discord_error_code, p_detail)
  ON CONFLICT (class_id, user_id, guild_id) DO UPDATE
  SET state = excluded.state,
      discord_error_code = excluded.discord_error_code,
      detail = excluded.detail,
      last_observed_at = now(),
      -- Reset the count when the state changes so observed_count always describes
      -- the current state rather than the history of the row.
      observed_count = CASE WHEN dms.state = excluded.state THEN dms.observed_count + 1 ELSE 1 END,
      first_observed_at = CASE WHEN dms.state = excluded.state THEN dms.first_observed_at ELSE now() END;
END;
$$;

REVOKE ALL ON FUNCTION public.record_discord_membership_status(bigint, uuid, text, public.discord_membership_state, integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_discord_membership_status(bigint, uuid, text, public.discord_membership_state, integer, text) TO service_role;

-- ============================================================================
-- 5. Instructor-facing read
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_discord_membership_status_for_class(p_class_id bigint)
RETURNS TABLE (
  user_id uuid,
  name text,
  sortable_name text,
  email text,
  discord_username text,
  state public.discord_membership_state,
  discord_error_code integer,
  detail text,
  last_observed_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.authorizeforclassgrader(p_class_id::bigint) THEN
    RAISE EXCEPTION 'Access denied: must be a grader or instructor for this class';
  END IF;

  RETURN QUERY
  SELECT
    dms.user_id,
    p.name,
    p.sortable_name,
    u.email,
    u.discord_username,
    dms.state,
    dms.discord_error_code,
    dms.detail,
    dms.last_observed_at
  FROM public.discord_membership_status dms
  JOIN public.users u ON u.user_id = dms.user_id
  -- Restricted to the class's *current* server. The status table is keyed on guild_id, so
  -- changing discord_server_id leaves the old guild's rows behind; without this join an
  -- instructor would keep seeing failures from a server the class no longer uses, and two
  -- rows for one student would race to define their state.
  JOIN public.classes c ON c.id = dms.class_id AND c.discord_server_id = dms.guild_id
  -- An active enrollment is required, not merely preferred. get_discord_role_sync_candidates()
  -- skips disabled roles, so once a student drops, their last recorded status is never refreshed
  -- again -- a LEFT JOIN would list them as still needing Discord access forever, and with a null
  -- profile the roster would fall back to showing their email. LATERAL with LIMIT 1 so a user
  -- holding more than one active role in the class cannot duplicate their row.
  JOIN LATERAL (
    SELECT ur.private_profile_id
    FROM public.user_roles ur
    WHERE ur.user_id = dms.user_id
      AND ur.class_id = dms.class_id
      AND ur.disabled = false
    LIMIT 1
  ) ur ON true
  LEFT JOIN public.profiles p ON p.id = ur.private_profile_id
  WHERE dms.class_id = p_class_id
  -- The enum is ordered by how much attention the state needs, so DESC puts cannot_invite
  -- first. in_guild rows are returned too: the roster has to tell "checked, and they are in"
  -- apart from "never checked", and only the presence of a row distinguishes them.
  ORDER BY dms.state DESC, p.sortable_name NULLS LAST;
END;
$$;

COMMENT ON FUNCTION public.get_discord_membership_status_for_class(bigint) IS
  'Where each checked student in a class stands with its Discord server, and why. Drives the roster-page surface for what used to be an invisible queue failure.';

REVOKE ALL ON FUNCTION public.get_discord_membership_status_for_class(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_discord_membership_status_for_class(bigint) TO authenticated, service_role;

-- ============================================================================
-- 6. Resolve the discussion-stats cron URL at run time
-- ============================================================================

-- The original schedule interpolated the vault's supabase_project_url into the cron
-- command with format(), freezing whatever value the vault held when the migration
-- ran. On production that was the local development default
-- (http://host.docker.internal:54321), so the job has never reached the function --
-- and because net.http_post only queues the request, every run still reported
-- success. Calling through call_edge_function_internal reads the vault at run time
-- and raises when the secret is missing, so a misconfiguration shows up as a failed
-- cron run instead of a silent one.

CREATE OR REPLACE FUNCTION public.invoke_discord_discussion_stats_update()
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  PERFORM public.call_edge_function_internal(
    '/functions/v1/discord-discussion-stats-update',
    'POST',
    '{"Content-Type":"application/json"}'::jsonb,
    '{}'::jsonb,
    5000,
    null, null, null, null, null
  );
END;
$$;

REVOKE ALL ON FUNCTION public.invoke_discord_discussion_stats_update() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.invoke_discord_discussion_stats_update() TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('discord-discussion-stats-update')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'discord-discussion-stats-update');

    PERFORM cron.schedule(
      'discord-discussion-stats-update',
      '30 * * * *',
      $sql$SELECT public.invoke_discord_discussion_stats_update();$sql$
    );
  END IF;
END $$;
