-- Migration for instructor emailer templates with flexible RPC-based recipient querying
-- This creates a flexible system for:
-- 1. Admin-defined email templates with RPC mappings
-- 2. RPCs for querying specific recipient groups (students with errors, lab leaders, etc.)
-- 3. Template variable system for rich email personalization

-- Create table for email templates (global templates managed by admins)
CREATE TABLE IF NOT EXISTS "public"."email_templates" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "name" text NOT NULL,
    "description" text,
    "subject_template" text NOT NULL,
    "body_template" text NOT NULL,
    "rpc_function_name" text NOT NULL,
    "rpc_description" text,
    "available_variables" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "variable_descriptions" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "is_active" boolean NOT NULL DEFAULT true,
    "requires_assignment" boolean NOT NULL DEFAULT false,
    "requires_lab_section" boolean NOT NULL DEFAULT false,
    "scope" text NOT NULL DEFAULT 'course' CHECK (scope IN ('global', 'course')),
    "class_id" bigint REFERENCES "public"."classes"("id") ON DELETE CASCADE,
    "created_by" uuid REFERENCES "auth"."users"("id"),
    CONSTRAINT "email_templates_scope_class_id_check" CHECK (
        (scope = 'global' AND class_id IS NULL) OR 
        (scope = 'course' AND class_id IS NOT NULL)
    )
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS "idx_email_templates_class_id" ON "public"."email_templates"("class_id");
CREATE INDEX IF NOT EXISTS "idx_email_templates_rpc_function_name" ON "public"."email_templates"("rpc_function_name");
CREATE INDEX IF NOT EXISTS "idx_email_templates_is_active" ON "public"."email_templates"("is_active");

-- Enable RLS
ALTER TABLE "public"."email_templates" ENABLE ROW LEVEL SECURITY;

-- RLS policies for email_templates
-- Admins can manage global templates
CREATE POLICY "Admins can manage global templates"
ON "public"."email_templates"
AS PERMISSIVE
FOR ALL
TO authenticated
USING (
    (scope = 'global' AND EXISTS (SELECT 1 FROM auth.users WHERE id = auth.uid() AND raw_user_meta_data->>'is_admin' = 'true'))
    OR
    (scope = 'course' AND authorizeforclassinstructor(class_id))
)
WITH CHECK (
    (scope = 'global' AND EXISTS (SELECT 1 FROM auth.users WHERE id = auth.uid() AND raw_user_meta_data->>'is_admin' = 'true'))
    OR
    (scope = 'course' AND authorizeforclassinstructor(class_id))
);

-- Instructors can view all active templates (global + their course)
CREATE POLICY "Instructors can view active templates"
ON "public"."email_templates"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
    is_active = true AND (
        scope = 'global' 
        OR 
        authorizeforclassinstructor(class_id)
        OR
        authorizeforclassgrader(class_id)
    )
);

-- ============================================================================
-- RPC: Get students with submissions matching specific autograder test errors
-- This allows instructors to email students whose submissions have specific 
-- failing tests (e.g., matching a pattern like 'error', 'failed', etc.)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_get_students_with_test_errors(
    p_class_id bigint,
    p_assignment_id bigint,
    p_test_name_pattern text DEFAULT NULL,
    p_min_score numeric DEFAULT NULL,
    p_max_score numeric DEFAULT NULL
)
RETURNS TABLE (
    user_id uuid,
    email text,
    private_profile_id uuid,
    student_name text,
    assignment_title text,
    test_name text,
    test_score numeric,
    test_max_score numeric,
    submission_id bigint,
    submission_created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Check authorization
    IF NOT authorizeforclassinstructor(p_class_id) AND NOT authorizeforclassgrader(p_class_id) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    RETURN QUERY
    SELECT DISTINCT
        u.user_id,
        u.email,
        ur.private_profile_id,
        p.name as student_name,
        a.title as assignment_title,
        grt.name as test_name,
        grt.score as test_score,
        grt.max_score as test_max_score,
        s.id as submission_id,
        s.created_at as submission_created_at
    FROM submissions s
    JOIN assignments a ON s.assignment_id = a.id
    JOIN grader_results gr ON gr.submission_id = s.id
    JOIN grader_result_tests grt ON grt.grader_result_id = gr.id
    LEFT JOIN profiles p ON (s.profile_id = p.id OR EXISTS (
        SELECT 1 FROM assignment_groups_members agm 
        WHERE agm.assignment_group_id = s.assignment_group_id 
        AND agm.profile_id = p.id
    ))
    JOIN user_roles ur ON ur.private_profile_id = p.id AND ur.class_id = p_class_id
    JOIN users u ON u.user_id = ur.user_id
    WHERE s.class_id = p_class_id
    AND s.assignment_id = p_assignment_id
    AND s.is_active = true
    AND p.is_private_profile = true
    AND (p_test_name_pattern IS NULL OR grt.name ~* p_test_name_pattern)
    AND (p_min_score IS NULL OR grt.score >= p_min_score)
    AND (p_max_score IS NULL OR grt.score <= p_max_score)
    ORDER BY p.name, grt.name;
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION public.emailer_get_students_with_test_errors TO authenticated;

-- ============================================================================
-- RPC: Get students with zero or failing scores on specific tests
-- Specifically targets "error" patterns in test names or scores
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_get_students_with_failing_tests(
    p_class_id bigint,
    p_assignment_id bigint,
    p_include_zero_scores boolean DEFAULT true,
    p_include_error_tests boolean DEFAULT true
)
RETURNS TABLE (
    user_id uuid,
    email text,
    private_profile_id uuid,
    student_name text,
    assignment_title text,
    failing_test_count bigint,
    total_test_count bigint,
    submission_id bigint,
    class_section_name text,
    lab_section_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Check authorization
    IF NOT authorizeforclassinstructor(p_class_id) AND NOT authorizeforclassgrader(p_class_id) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    RETURN QUERY
    SELECT DISTINCT
        u.user_id,
        u.email,
        ur.private_profile_id,
        p.name as student_name,
        a.title as assignment_title,
        COUNT(*) FILTER (WHERE 
            (p_include_zero_scores AND grt.score = 0) OR 
            (p_include_error_tests AND (grt.name ~* 'error|fail|exception' OR grt.score < 0))
        ) as failing_test_count,
        COUNT(*) as total_test_count,
        s.id as submission_id,
        cs.name as class_section_name,
        ls.name as lab_section_name
    FROM submissions s
    JOIN assignments a ON s.assignment_id = a.id
    JOIN grader_results gr ON gr.submission_id = s.id
    JOIN grader_result_tests grt ON grt.grader_result_id = gr.id
    LEFT JOIN profiles p ON (s.profile_id = p.id OR EXISTS (
        SELECT 1 FROM assignment_groups_members agm 
        WHERE agm.assignment_group_id = s.assignment_group_id 
        AND agm.profile_id = p.id
    ))
    JOIN user_roles ur ON ur.private_profile_id = p.id AND ur.class_id = p_class_id
    JOIN users u ON u.user_id = ur.user_id
    LEFT JOIN class_sections cs ON cs.id = ur.class_section_id
    LEFT JOIN lab_sections ls ON ls.id = ur.lab_section_id
    WHERE s.class_id = p_class_id
    AND s.assignment_id = p_assignment_id
    AND s.is_active = true
    AND p.is_private_profile = true
    GROUP BY u.user_id, u.email, ur.private_profile_id, p.name, a.title, s.id, cs.name, ls.name
    HAVING COUNT(*) FILTER (WHERE 
        (p_include_zero_scores AND grt.score = 0) OR 
        (p_include_error_tests AND (grt.name ~* 'error|fail|exception' OR grt.score < 0))
    ) > 0
    ORDER BY p.name;
END;
$$;

GRANT EXECUTE ON FUNCTION public.emailer_get_students_with_failing_tests TO authenticated;

-- ============================================================================
-- RPC: Get lab section leaders with missing lab grades for their sections
-- Returns lab leaders who have students without grades for lab assignments
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_get_lab_leaders_with_missing_grades(
    p_class_id bigint,
    p_assignment_id bigint DEFAULT NULL
)
RETURNS TABLE (
    user_id uuid,
    email text,
    private_profile_id uuid,
    leader_name text,
    lab_section_id bigint,
    lab_section_name text,
    assignment_title text,
    students_missing_grades bigint,
    total_students bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Check authorization
    IF NOT authorizeforclassinstructor(p_class_id) AND NOT authorizeforclassgrader(p_class_id) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    RETURN QUERY
    WITH lab_assignments AS (
        SELECT a.id, a.title
        FROM assignments a
        WHERE a.class_id = p_class_id
        AND a.archived_at IS NULL
        AND (a.minutes_due_after_lab IS NOT NULL OR a.slug LIKE 'lab%')
        AND (p_assignment_id IS NULL OR a.id = p_assignment_id)
    ),
    students_in_sections AS (
        SELECT 
            ur.lab_section_id,
            ur.private_profile_id as student_profile_id,
            ur.user_id as student_user_id
        FROM user_roles ur
        WHERE ur.class_id = p_class_id
        AND ur.role = 'student'
        AND ur.disabled = false
        AND ur.lab_section_id IS NOT NULL
    ),
    student_grades AS (
        SELECT DISTINCT
            sis.lab_section_id,
            la.id as assignment_id,
            la.title as assignment_title,
            sis.student_profile_id,
            CASE WHEN sr.id IS NOT NULL AND sr.released = true THEN true ELSE false END as has_released_grade
        FROM students_in_sections sis
        CROSS JOIN lab_assignments la
        LEFT JOIN submissions s ON (
            s.assignment_id = la.id 
            AND s.is_active = true
            AND (
                s.profile_id = sis.student_profile_id
                OR EXISTS (
                    SELECT 1 FROM assignment_groups_members agm
                    WHERE agm.assignment_group_id = s.assignment_group_id
                    AND agm.profile_id = sis.student_profile_id
                )
            )
        )
        LEFT JOIN submission_reviews sr ON sr.submission_id = s.id
    ),
    section_stats AS (
        SELECT 
            sg.lab_section_id,
            sg.assignment_id,
            sg.assignment_title,
            COUNT(*) as total_students,
            COUNT(*) FILTER (WHERE NOT sg.has_released_grade) as missing_grades
        FROM student_grades sg
        GROUP BY sg.lab_section_id, sg.assignment_id, sg.assignment_title
    )
    SELECT DISTINCT
        u.user_id,
        u.email,
        lsl.profile_id as private_profile_id,
        p.name as leader_name,
        ls.id as lab_section_id,
        ls.name as lab_section_name,
        ss.assignment_title,
        ss.missing_grades as students_missing_grades,
        ss.total_students
    FROM lab_section_leaders lsl
    JOIN lab_sections ls ON ls.id = lsl.lab_section_id
    JOIN profiles p ON p.id = lsl.profile_id
    JOIN user_roles ur ON ur.private_profile_id = lsl.profile_id AND ur.class_id = p_class_id
    JOIN users u ON u.user_id = ur.user_id
    JOIN section_stats ss ON ss.lab_section_id = ls.id
    WHERE ls.class_id = p_class_id
    AND ss.missing_grades > 0
    ORDER BY p.name, ls.name, ss.assignment_title;
END;
$$;

GRANT EXECUTE ON FUNCTION public.emailer_get_lab_leaders_with_missing_grades TO authenticated;

-- ============================================================================
-- RPC: Get students without submissions for an assignment
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_get_students_without_submissions(
    p_class_id bigint,
    p_assignment_id bigint
)
RETURNS TABLE (
    user_id uuid,
    email text,
    private_profile_id uuid,
    student_name text,
    assignment_title text,
    assignment_due_date timestamptz,
    class_section_name text,
    lab_section_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Check authorization
    IF NOT authorizeforclassinstructor(p_class_id) AND NOT authorizeforclassgrader(p_class_id) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    RETURN QUERY
    SELECT 
        u.user_id,
        u.email,
        ur.private_profile_id,
        p.name as student_name,
        a.title as assignment_title,
        a.due_date as assignment_due_date,
        cs.name as class_section_name,
        ls.name as lab_section_name
    FROM user_roles ur
    JOIN users u ON u.user_id = ur.user_id
    JOIN profiles p ON p.id = ur.private_profile_id
    JOIN assignments a ON a.id = p_assignment_id
    LEFT JOIN class_sections cs ON cs.id = ur.class_section_id
    LEFT JOIN lab_sections ls ON ls.id = ur.lab_section_id
    WHERE ur.class_id = p_class_id
    AND ur.role = 'student'
    AND ur.disabled = false
    AND p.is_private_profile = true
    AND NOT EXISTS (
        SELECT 1 FROM submissions s
        WHERE s.assignment_id = p_assignment_id
        AND s.is_active = true
        AND (
            s.profile_id = ur.private_profile_id
            OR EXISTS (
                SELECT 1 FROM assignment_groups_members agm
                WHERE agm.assignment_group_id = s.assignment_group_id
                AND agm.profile_id = ur.private_profile_id
            )
        )
    )
    ORDER BY p.name;
END;
$$;

GRANT EXECUTE ON FUNCTION public.emailer_get_students_without_submissions TO authenticated;

-- ============================================================================
-- RPC: Get students with low scores on an assignment
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_get_students_with_low_scores(
    p_class_id bigint,
    p_assignment_id bigint,
    p_max_score_threshold numeric DEFAULT 50
)
RETURNS TABLE (
    user_id uuid,
    email text,
    private_profile_id uuid,
    student_name text,
    assignment_title text,
    total_score numeric,
    autograder_score numeric,
    submission_id bigint,
    class_section_name text,
    lab_section_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Check authorization
    IF NOT authorizeforclassinstructor(p_class_id) AND NOT authorizeforclassgrader(p_class_id) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    RETURN QUERY
    SELECT DISTINCT
        u.user_id,
        u.email,
        ur.private_profile_id,
        p.name as student_name,
        a.title as assignment_title,
        COALESCE(sr.total_score, 0) + COALESCE(sr.tweak, 0) as total_score,
        COALESCE(gr.score, 0) as autograder_score,
        s.id as submission_id,
        cs.name as class_section_name,
        ls.name as lab_section_name
    FROM submissions s
    JOIN assignments a ON s.assignment_id = a.id
    LEFT JOIN profiles p ON (s.profile_id = p.id OR EXISTS (
        SELECT 1 FROM assignment_groups_members agm 
        WHERE agm.assignment_group_id = s.assignment_group_id 
        AND agm.profile_id = p.id
    ))
    JOIN user_roles ur ON ur.private_profile_id = p.id AND ur.class_id = p_class_id
    JOIN users u ON u.user_id = ur.user_id
    LEFT JOIN class_sections cs ON cs.id = ur.class_section_id
    LEFT JOIN lab_sections ls ON ls.id = ur.lab_section_id
    LEFT JOIN submission_reviews sr ON sr.id = s.grading_review_id
    LEFT JOIN grader_results gr ON gr.submission_id = s.id
    WHERE s.class_id = p_class_id
    AND s.assignment_id = p_assignment_id
    AND s.is_active = true
    AND p.is_private_profile = true
    AND (COALESCE(sr.total_score, 0) + COALESCE(sr.tweak, 0) + COALESCE(gr.score, 0)) <= p_max_score_threshold
    ORDER BY total_score ASC, p.name;
END;
$$;

GRANT EXECUTE ON FUNCTION public.emailer_get_students_with_low_scores TO authenticated;

-- ============================================================================
-- RPC: Generic function to list available emailer RPCs
-- This helps the UI discover what RPCs are available
-- ============================================================================
CREATE OR REPLACE FUNCTION public.emailer_list_available_rpcs()
RETURNS TABLE (
    rpc_name text,
    description text,
    requires_assignment boolean,
    requires_lab_section boolean,
    available_variables jsonb,
    parameter_schema jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT * FROM (
        VALUES
        (
            'emailer_get_students_with_test_errors'::text,
            'Get students with submissions matching specific autograder test patterns'::text,
            true::boolean,
            false::boolean,
            '["student_name", "email", "assignment_title", "test_name", "test_score", "test_max_score", "submission_id"]'::jsonb,
            '{"p_test_name_pattern": {"type": "text", "description": "Regex pattern to match test names"}, "p_min_score": {"type": "numeric", "description": "Minimum score filter"}, "p_max_score": {"type": "numeric", "description": "Maximum score filter"}}'::jsonb
        ),
        (
            'emailer_get_students_with_failing_tests'::text,
            'Get students with zero or failing test scores'::text,
            true::boolean,
            false::boolean,
            '["student_name", "email", "assignment_title", "failing_test_count", "total_test_count", "submission_id", "class_section_name", "lab_section_name"]'::jsonb,
            '{"p_include_zero_scores": {"type": "boolean", "description": "Include tests with score of 0"}, "p_include_error_tests": {"type": "boolean", "description": "Include tests with error/fail in name"}}'::jsonb
        ),
        (
            'emailer_get_lab_leaders_with_missing_grades'::text,
            'Get lab section leaders whose students are missing grades'::text,
            false::boolean,
            true::boolean,
            '["leader_name", "email", "lab_section_name", "assignment_title", "students_missing_grades", "total_students"]'::jsonb,
            '{"p_assignment_id": {"type": "bigint", "description": "Optional: filter to specific assignment"}}'::jsonb
        ),
        (
            'emailer_get_students_without_submissions'::text,
            'Get students who have not submitted an assignment'::text,
            true::boolean,
            false::boolean,
            '["student_name", "email", "assignment_title", "assignment_due_date", "class_section_name", "lab_section_name"]'::jsonb,
            '{}'::jsonb
        ),
        (
            'emailer_get_students_with_low_scores'::text,
            'Get students with scores below a threshold'::text,
            true::boolean,
            false::boolean,
            '["student_name", "email", "assignment_title", "total_score", "autograder_score", "submission_id", "class_section_name", "lab_section_name"]'::jsonb,
            '{"p_max_score_threshold": {"type": "numeric", "description": "Maximum score threshold (default: 50)"}}'::jsonb
        )
    ) AS t(rpc_name, description, requires_assignment, requires_lab_section, available_variables, parameter_schema);
END;
$$;

GRANT EXECUTE ON FUNCTION public.emailer_list_available_rpcs TO authenticated;

-- ============================================================================
-- Insert default global email templates
-- ============================================================================
INSERT INTO "public"."email_templates" (
    "name",
    "description", 
    "subject_template",
    "body_template",
    "rpc_function_name",
    "rpc_description",
    "available_variables",
    "variable_descriptions",
    "is_active",
    "requires_assignment",
    "requires_lab_section",
    "scope"
) VALUES 
(
    'Students with Failing Tests',
    'Email students whose submissions have failing or erroring autograder tests',
    '[{course_name}] Your {assignment_title} submission needs attention',
    E'Hi {student_name},\n\nWe noticed that your submission for **{assignment_title}** has {failing_test_count} failing test(s) out of {total_test_count} total tests.\n\nPlease review your submission and consider making corrections before the deadline.\n\nBest regards,\n{course_name} Staff',
    'emailer_get_students_with_failing_tests',
    'Query students with zero or failing test scores',
    '["student_name", "email", "assignment_title", "failing_test_count", "total_test_count", "submission_id", "class_section_name", "lab_section_name", "course_name"]',
    '{"student_name": "The student''s name", "email": "Student email address", "assignment_title": "Title of the assignment", "failing_test_count": "Number of failing tests", "total_test_count": "Total number of tests", "submission_id": "ID of the submission", "class_section_name": "Student''s class section", "lab_section_name": "Student''s lab section", "course_name": "Name of the course"}',
    true,
    true,
    false,
    'global'
),
(
    'Lab Leaders - Missing Grades',
    'Email lab section leaders about students in their sections who are missing grades',
    '[{course_name}] Students missing grades in {lab_section_name}',
    E'Hi {leader_name},\n\nThis is a reminder that {students_missing_grades} student(s) in your lab section **{lab_section_name}** are still missing grades for **{assignment_title}**.\n\nTotal students in section: {total_students}\nStudents missing grades: {students_missing_grades}\n\nPlease ensure all grades are entered and released.\n\nBest regards,\n{course_name} Staff',
    'emailer_get_lab_leaders_with_missing_grades',
    'Query lab leaders with students missing grades',
    '["leader_name", "email", "lab_section_name", "assignment_title", "students_missing_grades", "total_students", "course_name"]',
    '{"leader_name": "Name of the lab section leader", "email": "Leader''s email address", "lab_section_name": "Name of the lab section", "assignment_title": "Title of the assignment (if filtered)", "students_missing_grades": "Count of students without released grades", "total_students": "Total students in the section", "course_name": "Name of the course"}',
    true,
    false,
    true,
    'global'
),
(
    'Students Without Submissions',
    'Email students who have not yet submitted an assignment',
    '[{course_name}] Reminder: {assignment_title} not yet submitted',
    E'Hi {student_name},\n\nWe noticed that you have not yet submitted **{assignment_title}**.\n\nThe assignment is due on {assignment_due_date}. Please make sure to submit your work before the deadline.\n\nIf you are having any difficulties, please reach out to the course staff.\n\nBest regards,\n{course_name} Staff',
    'emailer_get_students_without_submissions',
    'Query students who have not submitted',
    '["student_name", "email", "assignment_title", "assignment_due_date", "class_section_name", "lab_section_name", "course_name"]',
    '{"student_name": "The student''s name", "email": "Student email address", "assignment_title": "Title of the assignment", "assignment_due_date": "Due date of the assignment", "class_section_name": "Student''s class section", "lab_section_name": "Student''s lab section", "course_name": "Name of the course"}',
    true,
    true,
    false,
    'global'
),
(
    'Students with Low Scores',
    'Email students whose scores are below a certain threshold',
    '[{course_name}] Regarding your {assignment_title} grade',
    E'Hi {student_name},\n\nWe wanted to reach out regarding your submission for **{assignment_title}**.\n\nYour current score is {total_score} (autograder: {autograder_score}).\n\nIf you would like to discuss your grade or get help improving your understanding, please reach out to the course staff or visit office hours.\n\nBest regards,\n{course_name} Staff',
    'emailer_get_students_with_low_scores',
    'Query students with scores below threshold',
    '["student_name", "email", "assignment_title", "total_score", "autograder_score", "submission_id", "class_section_name", "lab_section_name", "course_name"]',
    '{"student_name": "The student''s name", "email": "Student email address", "assignment_title": "Title of the assignment", "total_score": "Total score (including tweak)", "autograder_score": "Autograder score component", "submission_id": "ID of the submission", "class_section_name": "Student''s class section", "lab_section_name": "Student''s lab section", "course_name": "Name of the course"}',
    true,
    true,
    false,
    'global'
),
(
    'Custom Test Pattern Match',
    'Email students whose submissions have tests matching a specific pattern (e.g., specific error types)',
    '[{course_name}] {assignment_title} - Test Results',
    E'Hi {student_name},\n\nYour submission for **{assignment_title}** has test results that we wanted to bring to your attention.\n\nTest: {test_name}\nScore: {test_score} / {test_max_score}\n\nPlease review your submission if needed.\n\nBest regards,\n{course_name} Staff',
    'emailer_get_students_with_test_errors',
    'Query students matching specific test name patterns',
    '["student_name", "email", "assignment_title", "test_name", "test_score", "test_max_score", "submission_id", "course_name"]',
    '{"student_name": "The student''s name", "email": "Student email address", "assignment_title": "Title of the assignment", "test_name": "Name of the matching test", "test_score": "Score on the test", "test_max_score": "Maximum possible score", "submission_id": "ID of the submission", "course_name": "Name of the course"}',
    true,
    true,
    false,
    'global'
);

-- Add comment for documentation
COMMENT ON TABLE "public"."email_templates" IS 'Stores email templates for the instructor emailer system. Templates can be global (admin-managed) or course-specific.';
COMMENT ON FUNCTION public.emailer_get_students_with_test_errors IS 'RPC for emailer: Returns students whose submissions have tests matching a pattern or score range';
COMMENT ON FUNCTION public.emailer_get_students_with_failing_tests IS 'RPC for emailer: Returns students with zero or failing test scores';
COMMENT ON FUNCTION public.emailer_get_lab_leaders_with_missing_grades IS 'RPC for emailer: Returns lab leaders whose students are missing grades';
COMMENT ON FUNCTION public.emailer_get_students_without_submissions IS 'RPC for emailer: Returns students who have not submitted an assignment';
COMMENT ON FUNCTION public.emailer_get_students_with_low_scores IS 'RPC for emailer: Returns students with scores below a threshold';
COMMENT ON FUNCTION public.emailer_list_available_rpcs IS 'Lists all available emailer RPCs with their metadata';
