-- Empty submission detection
-- - Store per-handout-version file hashes for expected submission files
-- - Mark new submissions as empty if they match any handout version

-- 1) New column on submissions
ALTER TABLE IF EXISTS public.submissions
  ADD COLUMN IF NOT EXISTS is_empty_submission boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.submissions.is_empty_submission IS
  'True if this submission matches the handout (starter) files for the assignment (any recorded handout version).';

-- 2) Store handout (template repo) file hashes per assignment + commit SHA
CREATE TABLE IF NOT EXISTS public.assignment_handout_file_hashes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  assignment_id bigint NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  sha text NOT NULL,
  -- sha256 over sorted (path, file_hash) pairs for quick matching
  combined_hash text NOT NULL,
  -- jsonb object: { "path/to/file": "<sha256-hex>", ... }
  file_hashes jsonb NOT NULL DEFAULT '{}'::jsonb,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE
);

ALTER TABLE public.assignment_handout_file_hashes ENABLE ROW LEVEL SECURITY;

-- One record per (assignment_id, sha)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assignment_handout_file_hashes_assignment_id_sha_key'
  ) THEN
    ALTER TABLE public.assignment_handout_file_hashes
      ADD CONSTRAINT assignment_handout_file_hashes_assignment_id_sha_key UNIQUE (assignment_id, sha);
  END IF;
END $$;

-- Fast lookup by assignment + combined_hash
CREATE INDEX IF NOT EXISTS idx_assignment_handout_file_hashes_assignment_id_combined_hash
  ON public.assignment_handout_file_hashes (assignment_id, combined_hash);

CREATE INDEX IF NOT EXISTS idx_assignment_handout_file_hashes_class_id
  ON public.assignment_handout_file_hashes (class_id);

COMMENT ON TABLE public.assignment_handout_file_hashes IS
  'Stores hashes of expected submission files for each handout (template repo) commit SHA, per assignment. Used to detect empty submissions.';

-- Allow instructors (and graders) to read these hashes for their class (optional but useful for debugging/admin UI)
DROP POLICY IF EXISTS "instructors read" ON public.assignment_handout_file_hashes;
CREATE POLICY "instructors read"
  ON public.assignment_handout_file_hashes
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (public.authorizeforclassinstructor(class_id) OR public.authorizeforclassgrader(class_id));

