-- Resync identity/serial sequences in `public` that have fallen behind their column's max value.
--
-- Symptom that motivated this: every push to a handout repo raised
--   duplicate key value violates unique constraint "assignment_handout_commit_pkey"
--   Key (id)=(173) already exists.
-- from the `assignment_handout_commits` upsert in `github-repo-webhook`. The upsert conflict
-- target is (assignment_id, sha), so the collision was on the PRIMARY KEY (id): the identity
-- sequence was handing out values that already existed. That happens when rows are inserted with
-- explicit ids (a data import/restore, or a seed) — `generated by default as identity` permits it
-- and does not advance the sequence. Every subsequent insert then fails until the sequence catches
-- up past max(id), and because the webhook treated the failure as fatal, GitHub redelivered the
-- same push indefinitely.
--
-- The fix is applied to every sequence-backed column in `public`, not just the one table, because
-- the desync comes from how data got loaded rather than from anything specific to handout commits.
-- Sequences are only ever moved FORWARD (to max(id)); one already ahead of its column is left
-- alone, so this is a no-op on a healthy database and is safe to re-run.
DO $$
DECLARE
  rec RECORD;
  max_id BIGINT;
  seq_last BIGINT;
  seq_is_called BOOLEAN;
  seq_consumed BIGINT;
  resynced INT := 0;
BEGIN
  FOR rec IN
    SELECT
      seq_ns.nspname AS seq_schema,
      seq.relname    AS seq_name,
      tbl_ns.nspname AS tbl_schema,
      tbl.relname    AS tbl_name,
      col.attname    AS col_name
    FROM pg_class seq
    JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
    JOIN pg_depend dep
      ON dep.objid = seq.oid
     AND dep.classid = 'pg_class'::regclass
     AND dep.refclassid = 'pg_class'::regclass
     -- 'a' = serial/owned-by, 'i' = generated ... as identity
     AND dep.deptype IN ('a', 'i')
    JOIN pg_class tbl ON tbl.oid = dep.refobjid AND tbl.relkind IN ('r', 'p')
    JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
    JOIN pg_attribute col ON col.attrelid = tbl.oid AND col.attnum = dep.refobjsubid
    WHERE seq.relkind = 'S'
      AND tbl_ns.nspname = 'public'
      AND NOT col.attisdropped
  LOOP
    EXECUTE format('SELECT COALESCE(max(%I), 0) FROM %I.%I', rec.col_name, rec.tbl_schema, rec.tbl_name)
      INTO max_id;
    EXECUTE format('SELECT last_value, is_called FROM %I.%I', rec.seq_schema, rec.seq_name)
      INTO seq_last, seq_is_called;

    -- Compare against the highest value the sequence has already handed out, not last_value:
    -- an uncalled sequence (is_called = false, the state of one that has never been nextval'd)
    -- returns last_value itself on the next call. Without this, a table holding exactly one
    -- explicitly-inserted row at id = last_value looks in sync while the next insert still
    -- collides with it.
    seq_consumed := CASE WHEN seq_is_called THEN seq_last ELSE seq_last - 1 END;

    IF max_id > seq_consumed THEN
      PERFORM setval(format('%I.%I', rec.seq_schema, rec.seq_name)::regclass, max_id, true);
      resynced := resynced + 1;
      RAISE NOTICE 'Resynced sequence %.% for %.%.%: last handed out % -> %',
        rec.seq_schema, rec.seq_name, rec.tbl_schema, rec.tbl_name, rec.col_name, seq_consumed, max_id;
    END IF;
  END LOOP;

  RAISE NOTICE 'Sequence resync complete: % sequence(s) advanced', resynced;
END$$;
