-- Exam Grading + OCR System
-- Adds exam-mode assignments: template (PDF/markdown) with a 3-level question
-- structure + bounding-box regions, scanned-exam batches that are OCR'd and matched
-- to students via an async pgmq worker, and per-student submissions whose raw pages
-- are submission_files and whose OCR result is one submission_artifacts JSON blob.
--
-- Conventions used here:
--   * RLS = inline EXISTS on public.user_privileges (no authorizeforclass* helpers).
--   * Async processing = pgmq queue + cron invoker + edge function (like github-async-worker).
--   * Deliberate, minimal indexes (rely on the user_privileges PK for the RLS path).

-- ---------------------------------------------------------------------------
-- 1) Queue + DLQ
-- ---------------------------------------------------------------------------
do $$ begin
  perform pgmq.create('exam_processing');
exception when others then null;
end $$;

do $$ begin
  perform pgmq.create('exam_processing_dlq');
exception when others then null;
end $$;

-- ---------------------------------------------------------------------------
-- 2) Tables
-- ---------------------------------------------------------------------------

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  template_source_type text not null default 'pdf' check (template_source_type in ('pdf','markdown')),
  template_pdf_path text,
  template_markdown text,
  num_pages integer not null default 0,
  status text not null default 'draft' check (status in ('draft','ready')),
  created_by uuid default auth.uid(),
  constraint exams_assignment_id_unique unique (assignment_id)
);

create table if not exists public.exam_template_pages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  page_number integer not null,
  image_path text not null,
  width integer not null,
  height integer not null
);

create table if not exists public.exam_questions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  parent_id bigint references public.exam_questions(id) on delete cascade,
  level smallint not null check (level between 1 and 3),
  ordinal numeric not null default 0,
  label text,
  prompt text,
  answer_type text check (answer_type in
    ('multiple_choice','free_text','numeric','true_false','short_answer')),
  choices jsonb,
  points numeric
);

create table if not exists public.exam_question_regions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  exam_question_id bigint references public.exam_questions(id) on delete cascade,
  kind text not null default 'answer' check (kind in ('answer','student_id','name')),
  page_number integer not null,
  x numeric not null,
  y numeric not null,
  width numeric not null,
  height numeric not null,
  -- identity regions (name / student_id) are not tied to a question
  constraint exam_region_identity_has_no_question
    check (kind = 'answer' or exam_question_id is null)
);

create table if not exists public.exam_scan_batches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  uploaded_by uuid default auth.uid(),
  original_pdf_path text,
  total_pages integer not null default 0,
  pages_per_exam integer not null default 1,
  status text not null default 'uploaded'
    check (status in ('uploaded','ocr','matching','review','finalizing','completed','error')),
  error text
);

create table if not exists public.exam_scanned_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  batch_id bigint not null references public.exam_scan_batches(id) on delete cascade,
  exam_index integer not null,
  detected_name text,
  detected_sis_id text,
  matched_profile_id uuid references public.profiles(id) on delete set null,
  match_confidence numeric,
  match_status text not null default 'unmatched'
    check (match_status in ('unmatched','suggested','confirmed','skipped')),
  extracted jsonb,
  submission_id bigint references public.submissions(id) on delete set null,
  -- Single completion marker for this scanned submission's finalize. Set (transactionally
  -- at the end of finalize) only once the submission, its page files, and the exam artifact
  -- are all written. NULL = not finalized (never started OR crashed mid-finalize), which is
  -- exactly the set enqueue_exam_finalize re-enqueues and maybeCompleteBatch waits on.
  finalized_at timestamptz
);

create table if not exists public.exam_scan_pages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null references public.classes(id) on delete cascade,
  exam_id bigint not null references public.exams(id) on delete cascade,
  batch_id bigint not null references public.exam_scan_batches(id) on delete cascade,
  page_index integer not null,
  image_path text not null,
  width integer not null,
  height integer not null,
  ocr_text text,
  ocr_data jsonb,
  scanned_submission_id bigint references public.exam_scanned_submissions(id) on delete set null
);

-- DLQ tracking table (mirrors async_worker_dlq_messages)
create table if not exists public.exam_async_worker_dlq_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  original_msg_id bigint,
  method text,
  envelope jsonb,
  error_message text,
  error_type text,
  retry_count integer not null default 0,
  last_error_context jsonb,
  class_id bigint,
  debug_id text
);

-- ---------------------------------------------------------------------------
-- 3) Indexes (deliberate, minimal — real access paths only)
-- ---------------------------------------------------------------------------
-- One template page per (exam, page_number): unique so re-rasterizing/re-importing can't
-- silently create duplicate pages.
create unique index if not exists exam_template_pages_exam_idx on public.exam_template_pages (exam_id, page_number);
create index if not exists exam_questions_exam_idx on public.exam_questions (exam_id);
create index if not exists exam_questions_parent_idx on public.exam_questions (parent_id);
create index if not exists exam_question_regions_exam_idx on public.exam_question_regions (exam_id);
create index if not exists exam_question_regions_question_idx
  on public.exam_question_regions (exam_question_id) where exam_question_id is not null;
-- One scan page per (batch, page_index): unique so a re-upload can't duplicate pages.
create unique index if not exists exam_scan_pages_batch_idx on public.exam_scan_pages (batch_id, page_index);
create index if not exists exam_scanned_submissions_batch_idx on public.exam_scanned_submissions (batch_id);
create index if not exists exam_scanned_submissions_submission_idx
  on public.exam_scanned_submissions (submission_id) where submission_id is not null;
-- At most one exam_v1 artifact per submission. This is the finalize completion marker;
-- the partial unique index makes finalize's artifact insert race-safe (a concurrent
-- second finalize for the same submission hits a unique violation and is retried into a
-- no-op) and keeps maybeCompleteBatch's artifact count equal to the finalized-submission
-- count. Scoped to exam_v1 so it never constrains other submission_artifacts rows.
create unique index if not exists submission_artifacts_one_exam_v1_per_submission
  on public.submission_artifacts (submission_id)
  where (data->>'format') = 'exam_v1';

-- ---------------------------------------------------------------------------
-- 4) RLS — inline user_privileges checks (no helper functions)
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
  staff_tables text[] := array[
    'exams','exam_template_pages','exam_questions','exam_question_regions',
    'exam_scan_batches','exam_scan_pages','exam_scanned_submissions'
  ];
begin
  foreach t in array staff_tables loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('revoke all on table public.%I from anon;', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated, service_role;', t);
  end loop;
end $$;

-- SELECT for all staff (instructor or grader)
do $$
declare
  t text;
  staff_tables text[] := array[
    'exams','exam_template_pages','exam_questions','exam_question_regions',
    'exam_scan_batches','exam_scan_pages','exam_scanned_submissions'
  ];
begin
  foreach t in array staff_tables loop
    execute format('drop policy if exists %I on public.%I;', t || '_staff_select', t);
    execute format($f$
      create policy %I on public.%I for select to authenticated
      using (exists (
        select 1 from public.user_privileges up
        where up.user_id = auth.uid() and up.class_id = %I.class_id
          and up.role in ('instructor','grader')
      ));
    $f$, t || '_staff_select', t, t);
  end loop;
end $$;

-- WRITE: template/question/region = instructor only; scan/batch/scanned = staff
do $$
declare
  t text;
  instructor_tables text[] := array['exams','exam_template_pages','exam_questions','exam_question_regions'];
  staff_write_tables text[] := array['exam_scan_batches','exam_scan_pages','exam_scanned_submissions'];
begin
  foreach t in array instructor_tables loop
    execute format('drop policy if exists %I on public.%I;', t || '_instructor_write', t);
    execute format($f$
      create policy %I on public.%I for all to authenticated
      using (exists (
        select 1 from public.user_privileges up
        where up.user_id = auth.uid() and up.class_id = %I.class_id and up.role = 'instructor'
      ))
      with check (exists (
        select 1 from public.user_privileges up
        where up.user_id = auth.uid() and up.class_id = %I.class_id and up.role = 'instructor'
      ));
    $f$, t || '_instructor_write', t, t, t);
  end loop;
  foreach t in array staff_write_tables loop
    execute format('drop policy if exists %I on public.%I;', t || '_staff_write', t);
    execute format($f$
      create policy %I on public.%I for all to authenticated
      using (exists (
        select 1 from public.user_privileges up
        where up.user_id = auth.uid() and up.class_id = %I.class_id
          and up.role in ('instructor','grader')
      ))
      with check (exists (
        select 1 from public.user_privileges up
        where up.user_id = auth.uid() and up.class_id = %I.class_id
          and up.role in ('instructor','grader')
      ));
    $f$, t || '_staff_write', t, t, t);
  end loop;
end $$;

alter table public.exam_async_worker_dlq_messages enable row level security;
revoke all on table public.exam_async_worker_dlq_messages from anon, authenticated;
grant select, insert on table public.exam_async_worker_dlq_messages to service_role;
drop policy if exists exam_dlq_srv on public.exam_async_worker_dlq_messages;
create policy exam_dlq_srv on public.exam_async_worker_dlq_messages for all to service_role using (true) with check (true);

-- ---------------------------------------------------------------------------
-- 5) Storage buckets + policies
--    Path: classes/{class_id}/exams/{exam_id}/...   (class_id at segment 2)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public) values ('exam-templates','exam-templates',false)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('exam-scans','exam-scans',false)
on conflict (id) do nothing;

do $$
declare
  b text;
  buckets text[] := array['exam-templates','exam-scans'];
begin
  foreach b in array buckets loop
    -- staff read
    execute format('drop policy if exists %I on storage.objects;', b || '_staff_read');
    execute format($f$
      create policy %I on storage.objects for select to authenticated
      using (
        bucket_id = %L
        and exists (
          select 1 from public.user_privileges up
          where up.user_id = auth.uid()
            and up.class_id = (storage.foldername(name))[2]::bigint
            and up.role in ('instructor','grader')
        )
      );
    $f$, b || '_staff_read', b);
    -- staff write (insert/update/delete)
    execute format('drop policy if exists %I on storage.objects;', b || '_staff_write');
    execute format($f$
      create policy %I on storage.objects for all to authenticated
      using (
        bucket_id = %L
        and exists (
          select 1 from public.user_privileges up
          where up.user_id = auth.uid()
            and up.class_id = (storage.foldername(name))[2]::bigint
            and up.role in ('instructor','grader')
        )
      )
      with check (
        bucket_id = %L
        and exists (
          select 1 from public.user_privileges up
          where up.user_id = auth.uid()
            and up.class_id = (storage.foldername(name))[2]::bigint
            and up.role in ('instructor','grader')
        )
      );
    $f$, b || '_staff_write', b, b);
  end loop;
exception when insufficient_privilege then
  -- Some environments disallow CREATE POLICY on storage.objects (ownership varies);
  -- apply the equivalent policies via the dashboard. Local dev allows it.
  raise notice 'Skipped storage.objects policy creation (insufficient privilege).';
end $$;

-- ---------------------------------------------------------------------------
-- 6) Data RPCs
-- ---------------------------------------------------------------------------

-- Create / upsert the exam row for an assignment (instructor only)
create or replace function public.exam_create(
  p_assignment_id bigint,
  p_source_type text default 'pdf',
  p_num_pages integer default 0,
  p_template_pdf_path text default null,
  p_template_markdown text default null
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_class_id bigint;
  v_exam_id bigint;
begin
  select class_id into v_class_id from public.assignments where id = p_assignment_id;
  if v_class_id is null then
    raise exception 'Assignment % not found', p_assignment_id;
  end if;
  if auth.uid() is not null and not exists (
    select 1 from public.user_privileges up
    where up.user_id = auth.uid() and up.class_id = v_class_id and up.role = 'instructor'
  ) then
    raise exception 'Access denied: instructors only';
  end if;

  insert into public.exams (class_id, assignment_id, template_source_type, num_pages,
                            template_pdf_path, template_markdown)
  values (v_class_id, p_assignment_id, p_source_type, coalesce(p_num_pages,0),
          p_template_pdf_path, p_template_markdown)
  on conflict (assignment_id) do update
    set template_source_type = excluded.template_source_type,
        num_pages = excluded.num_pages,
        template_pdf_path = coalesce(excluded.template_pdf_path, exams.template_pdf_path),
        template_markdown = coalesce(excluded.template_markdown, exams.template_markdown)
  returning id into v_exam_id;

  return v_exam_id;
end;
$$;
revoke all on function public.exam_create(bigint, text, integer, text, text) from public;
grant execute on function public.exam_create(bigint, text, integer, text, text) to authenticated, service_role;

-- Replace the full question tree + regions transactionally.
-- p_questions: [{ client_id, parent_client_id, level, ordinal, label, prompt, answer_type, choices, points }]
-- p_regions:   [{ question_client_id|null, kind, page_number, x, y, width, height }]
create or replace function public.exam_upsert_questions_and_regions(
  p_exam_id bigint,
  p_questions jsonb,
  p_regions jsonb
) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_class_id bigint;
  q jsonb;
  r jsonb;
  v_lvl int;
  v_new_id bigint;
  v_parent_id bigint;
begin
  select class_id into v_class_id from public.exams where id = p_exam_id;
  if v_class_id is null then
    raise exception 'Exam % not found', p_exam_id;
  end if;
  if auth.uid() is not null and not exists (
    select 1 from public.user_privileges up
    where up.user_id = auth.uid() and up.class_id = v_class_id and up.role = 'instructor'
  ) then
    raise exception 'Access denied: instructors only';
  end if;

  -- wipe existing structure (regions cascade from questions, but identity regions do not)
  delete from public.exam_question_regions where exam_id = p_exam_id;
  delete from public.exam_questions where exam_id = p_exam_id;

  -- pg_temp-qualified (the function runs with search_path = '')
  create temporary table pg_temp._exam_qmap (client_id text primary key, new_id bigint) on commit drop;

  -- insert questions level-by-level so parents exist before children
  for v_lvl in 1..3 loop
    for q in select value from jsonb_array_elements(coalesce(p_questions, '[]'::jsonb))
             where (value->>'level')::int = v_lvl
             order by coalesce((value->>'ordinal')::numeric, 0)
    loop
      v_parent_id := null;
      if q->>'parent_client_id' is not null then
        select new_id into v_parent_id from pg_temp._exam_qmap where client_id = q->>'parent_client_id';
      end if;
      insert into public.exam_questions
        (class_id, exam_id, parent_id, level, ordinal, label, prompt, answer_type, choices, points)
      values
        (v_class_id, p_exam_id, v_parent_id, v_lvl,
         coalesce((q->>'ordinal')::numeric, 0), q->>'label', q->>'prompt',
         q->>'answer_type', q->'choices',
         nullif(q->>'points','')::numeric)
      returning id into v_new_id;
      insert into pg_temp._exam_qmap(client_id, new_id) values (q->>'client_id', v_new_id);
    end loop;
  end loop;

  -- regions
  for r in select value from jsonb_array_elements(coalesce(p_regions, '[]'::jsonb))
  loop
    v_new_id := null;
    if r->>'question_client_id' is not null then
      select new_id into v_new_id from pg_temp._exam_qmap where client_id = r->>'question_client_id';
    end if;
    insert into public.exam_question_regions
      (class_id, exam_id, exam_question_id, kind, page_number, x, y, width, height)
    values
      (v_class_id, p_exam_id, v_new_id, coalesce(r->>'kind','answer'),
       (r->>'page_number')::int, (r->>'x')::numeric, (r->>'y')::numeric,
       (r->>'width')::numeric, (r->>'height')::numeric);
  end loop;
end;
$$;
revoke all on function public.exam_upsert_questions_and_regions(bigint, jsonb, jsonb) from public;
grant execute on function public.exam_upsert_questions_and_regions(bigint, jsonb, jsonb) to authenticated, service_role;

-- Scaffold / link rubric_parts -> rubric_criteria -> rubric_checks from the exam's
-- 3-level question tree, writing the back-reference {exam_question_id} into each
-- component's data jsonb. Idempotent (matches on data->>'exam_question_id').
create or replace function public.exam_sync_rubric_from_questions(
  p_exam_id bigint,
  p_rubric_id bigint
) returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_class_id bigint;
  v_assignment_id bigint;
  r1 record;  -- level 1 (part)
  r2 record;  -- level 2 (criteria)
  r3 record;  -- level 3 (check)
  v_part_id bigint;
  v_crit_id bigint;
begin
  select class_id, assignment_id into v_class_id, v_assignment_id
    from public.exams where id = p_exam_id;
  if v_class_id is null then
    raise exception 'Exam % not found', p_exam_id;
  end if;
  if auth.uid() is not null and not exists (
    select 1 from public.user_privileges up
    where up.user_id = auth.uid() and up.class_id = v_class_id and up.role = 'instructor'
  ) then
    raise exception 'Access denied: instructors only';
  end if;

  -- level 1 -> rubric_parts
  for r1 in select * from public.exam_questions where exam_id = p_exam_id and level = 1 order by ordinal loop
    select id into v_part_id from public.rubric_parts
      where rubric_id = p_rubric_id and (data->>'exam_question_id')::bigint = r1.id limit 1;
    if v_part_id is null then
      insert into public.rubric_parts (class_id, assignment_id, rubric_id, name, description, ordinal, data)
      values (v_class_id, v_assignment_id, p_rubric_id, coalesce(r1.label, 'Part'), r1.prompt, r1.ordinal,
              jsonb_build_object('exam_question_id', r1.id))
      returning id into v_part_id;
    else
      update public.rubric_parts set name = coalesce(r1.label, name), description = r1.prompt, ordinal = r1.ordinal
        where id = v_part_id;
    end if;

    -- level 2 -> rubric_criteria (children of r1)
    for r2 in select * from public.exam_questions
              where exam_id = p_exam_id and level = 2 and parent_id = r1.id order by ordinal loop
      select id into v_crit_id from public.rubric_criteria
        where rubric_id = p_rubric_id and (data->>'exam_question_id')::bigint = r2.id limit 1;
      if v_crit_id is null then
        insert into public.rubric_criteria
          (class_id, assignment_id, rubric_id, rubric_part_id, name, description, total_points, is_additive, ordinal, data)
        values (v_class_id, v_assignment_id, p_rubric_id, v_part_id, coalesce(r2.label,'Criteria'), r2.prompt,
                coalesce(r2.points, 0), true, r2.ordinal, jsonb_build_object('exam_question_id', r2.id))
        returning id into v_crit_id;
      else
        update public.rubric_criteria set rubric_part_id = v_part_id, name = coalesce(r2.label, name),
          description = r2.prompt, total_points = coalesce(r2.points, total_points), ordinal = r2.ordinal
          where id = v_crit_id;
      end if;

      -- level 3 -> rubric_checks (children of r2)
      for r3 in select * from public.exam_questions
                where exam_id = p_exam_id and level = 3 and parent_id = r2.id order by ordinal loop
        if not exists (
          select 1 from public.rubric_checks
          where rubric_criteria_id = v_crit_id and (data->>'exam_question_id')::bigint = r3.id
        ) then
          insert into public.rubric_checks
            (class_id, assignment_id, rubric_id, rubric_criteria_id, name, description, ordinal, points, is_annotation, is_comment_required, data)
          values (v_class_id, v_assignment_id, p_rubric_id, v_crit_id, coalesce(r3.label,'Check'), r3.prompt, r3.ordinal,
                  coalesce(r3.points, 0), false, false, jsonb_build_object('exam_question_id', r3.id));
        end if;
      end loop;
    end loop;
  end loop;
end;
$$;
revoke all on function public.exam_sync_rubric_from_questions(bigint, bigint) from public;
grant execute on function public.exam_sync_rubric_from_questions(bigint, bigint) to authenticated, service_role;

-- Create the submission for a confirmed scanned exam. Fires the existing
-- submissions_after_insert_hook (auto-creates the grading submission_review).
-- Called by the worker (service role) during finalize.
create or replace function public.exam_create_submission(p_scanned_submission_id bigint)
returns bigint
language plpgsql
security definer
-- Inserting into public.submissions fires the submission trigger chain (channels,
-- metrics, after-insert hook). Some of those triggers reference tables unqualified and
-- have no search_path of their own, so they inherit this function's. An empty search_path
-- makes them fail with "relation submissions does not exist" — keep public on the path.
set search_path = public, pg_temp
as $$
declare
  v_class_id bigint;
  v_assignment_id bigint;
  v_profile_id uuid;
  v_match_status text;
  v_existing bigint;
  v_submission_id bigint;
begin
  select ss.class_id, e.assignment_id, ss.matched_profile_id, ss.match_status, ss.submission_id
    into v_class_id, v_assignment_id, v_profile_id, v_match_status, v_existing
  from public.exam_scanned_submissions ss
  join public.exams e on e.id = ss.exam_id
  where ss.id = p_scanned_submission_id;

  if v_class_id is null then
    raise exception 'Scanned submission % not found', p_scanned_submission_id;
  end if;
  if v_existing is not null then
    return v_existing; -- idempotent
  end if;
  if v_match_status <> 'confirmed' or v_profile_id is null then
    raise exception 'Scanned submission % is not a confirmed match', p_scanned_submission_id;
  end if;

  insert into public.submissions
    (assignment_id, profile_id, class_id, sha, repository, run_attempt, run_number, is_active)
  values
    (v_assignment_id, v_profile_id, v_class_id, 'exam',
     'exam-scan/' || p_scanned_submission_id::text, 0, 1, true)
  returning id into v_submission_id;

  update public.exam_scanned_submissions set submission_id = v_submission_id
    where id = p_scanned_submission_id;

  return v_submission_id;
end;
$$;
revoke all on function public.exam_create_submission(bigint) from public;
grant execute on function public.exam_create_submission(bigint) to service_role;

-- ---------------------------------------------------------------------------
-- 7) Enqueue RPCs (staff) + worker invoker + cron
-- ---------------------------------------------------------------------------

create or replace function public.enqueue_exam_process_batch(p_batch_id bigint)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_class_id bigint;
  v_count integer := 0;
  rec record;
begin
  select class_id into v_class_id from public.exam_scan_batches where id = p_batch_id;
  if v_class_id is null then
    raise exception 'Batch % not found', p_batch_id;
  end if;
  if auth.uid() is not null and not exists (
    select 1 from public.user_privileges up
    where up.user_id = auth.uid() and up.class_id = v_class_id and up.role in ('instructor','grader')
  ) then
    raise exception 'Access denied: staff only';
  end if;

  update public.exam_scan_batches set status = 'ocr', error = null where id = p_batch_id;

  -- one OCR job per scan page
  for rec in select id from public.exam_scan_pages where batch_id = p_batch_id order by page_index loop
    perform pgmq_public.send('exam_processing', jsonb_build_object(
      'method', 'process_page', 'class_id', v_class_id, 'batch_id', p_batch_id,
      'args', jsonb_build_object('scan_page_id', rec.id)));
    v_count := v_count + 1;
  end loop;

  -- one match job for the batch (groups pages into scanned submissions, reads identity)
  perform pgmq_public.send('exam_processing', jsonb_build_object(
    'method', 'match', 'class_id', v_class_id, 'batch_id', p_batch_id,
    'args', jsonb_build_object('batch_id', p_batch_id)));

  -- best-effort immediate kick; the cron invoker drains the queue regardless
  begin
    perform public.call_edge_function_internal(
      '/functions/v1/exam-async-worker', 'POST',
      '{"Content-type":"application/json","x-supabase-webhook-source":"exam-async-worker"}'::jsonb,
      '{}'::jsonb, 3000, null, null, null, null, null);
  exception when others then null;
  end;

  return v_count;
end;
$$;
revoke all on function public.enqueue_exam_process_batch(bigint) from public;
grant execute on function public.enqueue_exam_process_batch(bigint) to authenticated, service_role;

create or replace function public.enqueue_exam_finalize(p_batch_id bigint)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_class_id bigint;
  v_count integer := 0;
  rec record;
begin
  select class_id into v_class_id from public.exam_scan_batches where id = p_batch_id;
  if v_class_id is null then
    raise exception 'Batch % not found', p_batch_id;
  end if;
  if auth.uid() is not null and not exists (
    select 1 from public.user_privileges up
    where up.user_id = auth.uid() and up.class_id = v_class_id and up.role in ('instructor','grader')
  ) then
    raise exception 'Access denied: staff only';
  end if;

  -- Re-enqueue every confirmed submission that is not yet finalized. finalized_at is the
  -- crash-safety signal: a submission whose finalize crashed before completing (finalized_at
  -- still NULL, whether or not a partial submission/artifact exists) is picked back up here,
  -- as is one that never started.
  for rec in select ss.id from public.exam_scanned_submissions ss
             where ss.batch_id = p_batch_id and ss.match_status = 'confirmed'
               and ss.finalized_at is null loop
    perform pgmq_public.send('exam_processing', jsonb_build_object(
      'method', 'finalize', 'class_id', v_class_id, 'batch_id', p_batch_id,
      'args', jsonb_build_object('scanned_submission_id', rec.id)));
    v_count := v_count + 1;
  end loop;

  -- Only flip into 'finalizing' when there is actually work; otherwise leave the batch's
  -- status untouched (e.g. an already-'completed' batch stays completed) so a redundant
  -- finalize click can't strand it.
  if v_count > 0 then
    update public.exam_scan_batches set status = 'finalizing', error = null where id = p_batch_id;

    -- best-effort immediate kick; the cron invoker drains the queue regardless
    begin
      perform public.call_edge_function_internal(
        '/functions/v1/exam-async-worker', 'POST',
        '{"Content-type":"application/json","x-supabase-webhook-source":"exam-async-worker"}'::jsonb,
        '{}'::jsonb, 3000, null, null, null, null, null);
    exception when others then null;
    end;
  end if;

  return v_count;
end;
$$;
revoke all on function public.enqueue_exam_finalize(bigint) from public;
grant execute on function public.enqueue_exam_finalize(bigint) to authenticated, service_role;

-- Background invoker (drains the exam_processing queue via the edge worker)
create or replace function public.invoke_exam_async_worker_background_task()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  message_count integer;
  worker_count integer;
  i integer;
begin
  select count(*)::integer into message_count from pgmq_public.read('exam_processing', 0, 20);
  if message_count = 0 then
    return;
  elsif message_count >= 10 then
    worker_count := 5;
  else
    worker_count := 2;
  end if;
  for i in 1..worker_count loop
    perform public.call_edge_function_internal(
      '/functions/v1/exam-async-worker', 'POST',
      '{"Content-type":"application/json","x-supabase-webhook-source":"exam-async-worker"}'::jsonb,
      '{}'::jsonb, 3000, null, null, null, null, null);
  end loop;
end;
$$;
revoke all on function public.invoke_exam_async_worker_background_task() from public;
grant execute on function public.invoke_exam_async_worker_background_task() to service_role;

select cron.unschedule('invoke-exam-async-worker-every-minute')
where exists (select 1 from cron.job where jobname = 'invoke-exam-async-worker-every-minute');
select cron.schedule(
  'invoke-exam-async-worker-every-minute',
  '* * * * *',
  $$select public.invoke_exam_async_worker_background_task();$$
);
