-- Class-level grading automation profiles + per-assignment defaults/reminders
-- Implements:
-- 1) "Auto assign at deadline" defaults via reusable class profiles
-- 2) Late grading reminders at deadline + recurring interval
-- 3) Instructor-configurable CC + reply-to for reminder emails

CREATE TABLE IF NOT EXISTS public.grading_assignment_default_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  auto_assign_at_deadline boolean NOT NULL DEFAULT false,
  auto_assign_assignee_pool text NOT NULL DEFAULT 'graders',
  auto_assign_review_due_hours integer NOT NULL DEFAULT 72,
  late_grading_reminders_enabled boolean NOT NULL DEFAULT false,
  late_grading_reminder_interval_hours integer,
  late_grading_reply_to text,
  late_grading_cc_emails jsonb NOT NULL DEFAULT jsonb_build_object('emails', jsonb_build_array()),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT grading_assignment_default_profiles_assignee_pool_check CHECK (
    auto_assign_assignee_pool IN ('graders', 'instructors', 'instructors_and_graders')
  ),
  CONSTRAINT grading_assignment_default_profiles_due_hours_check CHECK (auto_assign_review_due_hours >= 0),
  CONSTRAINT grading_assignment_default_profiles_reminder_interval_check CHECK (
    (NOT late_grading_reminders_enabled)
    OR (late_grading_reminder_interval_hours IS NOT NULL AND late_grading_reminder_interval_hours > 0)
  ),
  CONSTRAINT grading_assignment_default_profiles_cc_emails_check CHECK (
    jsonb_typeof(late_grading_cc_emails) = 'object'
    AND late_grading_cc_emails ? 'emails'
    AND jsonb_typeof(late_grading_cc_emails->'emails') = 'array'
  ),
  CONSTRAINT grading_assignment_default_profiles_class_name_unique UNIQUE (class_id, name),
  CONSTRAINT grading_assignment_default_profiles_id_class_unique UNIQUE (id, class_id)
);

ALTER TABLE public.grading_assignment_default_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Class staff can view grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Class staff can view grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (authorizeforclassinstructor(class_id) OR authorizeforclassgrader(class_id));

DROP POLICY IF EXISTS "Instructors can insert grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can insert grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (authorizeforclassinstructor(class_id));

DROP POLICY IF EXISTS "Instructors can update grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can update grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (authorizeforclassinstructor(class_id))
WITH CHECK (authorizeforclassinstructor(class_id));

DROP POLICY IF EXISTS "Instructors can delete grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can delete grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (authorizeforclassinstructor(class_id));

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'set_updated_at'
  ) THEN
    DROP TRIGGER IF EXISTS set_updated_at_on_grading_assignment_default_profiles ON public.grading_assignment_default_profiles;
    CREATE TRIGGER set_updated_at_on_grading_assignment_default_profiles
    BEFORE UPDATE ON public.grading_assignment_default_profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

ALTER TABLE public.assignments
  ADD COLUMN IF NOT EXISTS grading_default_profile_id bigint,
  ADD COLUMN IF NOT EXISTS auto_assign_at_deadline boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_assign_assignee_pool text NOT NULL DEFAULT 'graders',
  ADD COLUMN IF NOT EXISTS auto_assign_review_due_hours integer NOT NULL DEFAULT 72,
  ADD COLUMN IF NOT EXISTS late_grading_reminders_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS late_grading_reminder_interval_hours integer,
  ADD COLUMN IF NOT EXISTS late_grading_reply_to text,
  ADD COLUMN IF NOT EXISTS late_grading_cc_emails jsonb NOT NULL DEFAULT jsonb_build_object('emails', jsonb_build_array());

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assignments_grading_default_profile_id_fkey'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_grading_default_profile_id_fkey
      FOREIGN KEY (grading_default_profile_id, class_id)
      REFERENCES public.grading_assignment_default_profiles(id, class_id)
      ON DELETE SET NULL (grading_default_profile_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_auto_assign_assignee_pool_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_auto_assign_assignee_pool_check
      CHECK (auto_assign_assignee_pool IN ('graders', 'instructors', 'instructors_and_graders'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_auto_assign_review_due_hours_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_auto_assign_review_due_hours_check
      CHECK (auto_assign_review_due_hours >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_late_grading_reminder_interval_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_late_grading_reminder_interval_check
      CHECK (
        (NOT late_grading_reminders_enabled)
        OR (late_grading_reminder_interval_hours IS NOT NULL AND late_grading_reminder_interval_hours > 0)
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_late_grading_cc_emails_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_late_grading_cc_emails_check
      CHECK (
        jsonb_typeof(late_grading_cc_emails) = 'object'
        AND late_grading_cc_emails ? 'emails'
        AND jsonb_typeof(late_grading_cc_emails->'emails') = 'array'
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.assignment_grading_automation_state (
  assignment_id bigint PRIMARY KEY REFERENCES public.assignments(id) ON DELETE CASCADE,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  auto_assigned_at timestamptz,
  last_reminder_sent_at timestamptz,
  last_reminder_recipient_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.assignment_grading_automation_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages assignment grading automation state" ON public.assignment_grading_automation_state;
CREATE POLICY "Service role manages assignment grading automation state"
ON public.assignment_grading_automation_state
AS PERMISSIVE
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_assignment_grading_automation_state_class_id
  ON public.assignment_grading_automation_state (class_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'set_updated_at'
  ) THEN
    DROP TRIGGER IF EXISTS set_updated_at_on_assignment_grading_automation_state ON public.assignment_grading_automation_state;
    CREATE TRIGGER set_updated_at_on_assignment_grading_automation_state
    BEFORE UPDATE ON public.assignment_grading_automation_state
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.auto_assign_grading_reviews_for_assignment(
  p_assignment_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment public.assignments%ROWTYPE;
  v_staff_ids uuid[];
  v_staff_count integer := 0;
  v_idx integer := 1;
  v_assignee uuid;
  v_actor_user_id uuid;
  v_review_due_date timestamptz;
  v_submission record;
  v_draft_assignments jsonb := '[]'::jsonb;
  v_result jsonb;
BEGIN
  SELECT *
  INTO v_assignment
  FROM public.assignments
  WHERE id = p_assignment_id
    AND archived_at IS NULL;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  IF NOT v_assignment.auto_assign_at_deadline THEN
    RETURN 0;
  END IF;

  IF v_assignment.grading_rubric_id IS NULL THEN
    RAISE WARNING 'auto_assign skipped for assignment %: missing grading_rubric_id', v_assignment.id;
    RETURN -1;
  END IF;

  -- bulk_assign_reviews requires an instructor auth context.
  SELECT ur.user_id
  INTO v_actor_user_id
  FROM public.user_roles ur
  WHERE ur.class_id = v_assignment.class_id
    AND ur.role = 'instructor'
    AND ur.disabled = false
  ORDER BY ur.created_at
  LIMIT 1;

  IF v_actor_user_id IS NULL THEN
    RAISE WARNING 'auto_assign skipped for assignment %: no active instructor', v_assignment.id;
    RETURN -1;
  END IF;

  PERFORM set_config('request.jwt.claim.sub', v_actor_user_id::text, true);

  SELECT array_agg(ur.private_profile_id ORDER BY ur.private_profile_id)
  INTO v_staff_ids
  FROM public.user_roles ur
  WHERE ur.class_id = v_assignment.class_id
    AND ur.disabled = false
    AND ur.private_profile_id IS NOT NULL
    AND (
      (v_assignment.auto_assign_assignee_pool = 'graders' AND ur.role = 'grader')
      OR (v_assignment.auto_assign_assignee_pool = 'instructors' AND ur.role = 'instructor')
      OR (
        v_assignment.auto_assign_assignee_pool = 'instructors_and_graders'
        AND ur.role IN ('grader', 'instructor')
      )
    );

  v_staff_count := COALESCE(array_length(v_staff_ids, 1), 0);
  IF v_staff_count = 0 THEN
    RAISE WARNING 'auto_assign skipped for assignment %: empty assignee pool (%).', v_assignment.id, v_assignment.auto_assign_assignee_pool;
    RETURN -1;
  END IF;

  v_review_due_date := v_assignment.due_date + make_interval(hours => GREATEST(v_assignment.auto_assign_review_due_hours, 0));

  FOR v_submission IN
    SELECT s.id
    FROM public.submissions s
    WHERE s.assignment_id = v_assignment.id
      AND s.class_id = v_assignment.class_id
      AND s.is_active = true
      AND NOT EXISTS (
        SELECT 1
        FROM public.review_assignments ra
        WHERE ra.assignment_id = v_assignment.id
          AND ra.rubric_id = v_assignment.grading_rubric_id
          AND ra.submission_id = s.id
      )
    ORDER BY s.id
  LOOP
    v_assignee := v_staff_ids[((v_idx - 1) % v_staff_count) + 1];
    v_draft_assignments := v_draft_assignments || jsonb_build_array(
      jsonb_build_object(
        'assignee_profile_id', v_assignee,
        'submission_id', v_submission.id,
        'rubric_part_id', NULL
      )
    );
    v_idx := v_idx + 1;
  END LOOP;

  IF jsonb_array_length(v_draft_assignments) = 0 THEN
    RETURN 0;
  END IF;

  SELECT public.bulk_assign_reviews(
    v_assignment.class_id,
    v_assignment.id,
    v_assignment.grading_rubric_id,
    v_draft_assignments,
    v_review_due_date
  )
  INTO v_result;

  IF COALESCE((v_result->>'success')::boolean, false) IS DISTINCT FROM true THEN
    RAISE WARNING 'bulk_assign_reviews failed for assignment %: %', v_assignment.id, v_result;
    RETURN -1;
  END IF;

  RETURN COALESCE((v_result->>'assignments_created')::integer, 0)
    + COALESCE((v_result->>'assignments_updated')::integer, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.queue_late_grading_reminders_for_assignment(
  p_assignment_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment public.assignments%ROWTYPE;
  v_batch_id bigint;
  v_subject text;
  v_email_count integer := 0;
BEGIN
  SELECT *
  INTO v_assignment
  FROM public.assignments
  WHERE id = p_assignment_id
    AND archived_at IS NULL;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  IF NOT v_assignment.late_grading_reminders_enabled THEN
    RETURN 0;
  END IF;

  IF v_assignment.late_grading_reminder_interval_hours IS NULL
     OR v_assignment.late_grading_reminder_interval_hours <= 0 THEN
    RETURN 0;
  END IF;

  v_subject := format('Late grading reminder: %s', v_assignment.title);

  INSERT INTO public.email_batches (subject, body, class_id, cc_emails, reply_to)
  VALUES (
    v_subject,
    '',
    v_assignment.class_id,
    v_assignment.late_grading_cc_emails,
    v_assignment.late_grading_reply_to
  )
  RETURNING id INTO v_batch_id;

  WITH reminder_recipients AS (
    SELECT
      ur.user_id,
      COUNT(*)::integer AS incomplete_count
    FROM public.review_assignments ra
    JOIN public.user_roles ur
      ON ur.private_profile_id = ra.assignee_profile_id
     AND ur.class_id = ra.class_id
    WHERE ra.assignment_id = v_assignment.id
      AND ra.completed_at IS NULL
      AND COALESCE(ra.due_date, v_assignment.due_date) <= now()
      AND (v_assignment.grading_rubric_id IS NULL OR ra.rubric_id = v_assignment.grading_rubric_id)
      AND ur.disabled = false
      AND ur.role IN ('grader', 'instructor')
    GROUP BY ur.user_id
  ),
  inserted AS (
    INSERT INTO public.emails (
      user_id,
      batch_id,
      class_id,
      subject,
      body,
      cc_emails,
      reply_to
    )
    SELECT
      rr.user_id,
      v_batch_id,
      v_assignment.class_id,
      v_subject,
      format(
        'You currently have %s incomplete grading assignment%s for "%s". Please visit the assignment reviews page to finish grading.',
        rr.incomplete_count,
        CASE WHEN rr.incomplete_count = 1 THEN '' ELSE 's' END,
        v_assignment.title
      ),
      v_assignment.late_grading_cc_emails,
      v_assignment.late_grading_reply_to
    FROM reminder_recipients rr
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_email_count FROM inserted;

  IF v_email_count = 0 THEN
    DELETE FROM public.email_batches WHERE id = v_batch_id;
  END IF;

  RETURN v_email_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.run_assignment_grading_automation()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment record;
  v_state record;
  v_auto_assigned_count integer;
  v_reminder_count integer;
BEGIN
  FOR v_assignment IN
    SELECT
      a.id,
      a.class_id,
      a.auto_assign_at_deadline,
      a.late_grading_reminders_enabled,
      a.late_grading_reminder_interval_hours,
      a.due_date,
      s.auto_assigned_at,
      s.last_reminder_sent_at
    FROM public.assignments a
    LEFT JOIN public.assignment_grading_automation_state s ON s.assignment_id = a.id
    WHERE a.archived_at IS NULL
      AND a.due_date <= now()
      AND (a.auto_assign_at_deadline OR a.late_grading_reminders_enabled)
  LOOP
    INSERT INTO public.assignment_grading_automation_state (assignment_id, class_id)
    VALUES (v_assignment.id, v_assignment.class_id)
    ON CONFLICT (assignment_id) DO NOTHING;

    SELECT s.auto_assigned_at, s.last_reminder_sent_at
    INTO v_state
    FROM public.assignment_grading_automation_state s
    WHERE s.assignment_id = v_assignment.id
    FOR UPDATE;

    IF v_assignment.auto_assign_at_deadline AND v_state.auto_assigned_at IS NULL THEN
      v_auto_assigned_count := public.auto_assign_grading_reviews_for_assignment(v_assignment.id);
      IF v_auto_assigned_count >= 0 THEN
        UPDATE public.assignment_grading_automation_state
        SET auto_assigned_at = now(),
            updated_at = now()
        WHERE assignment_id = v_assignment.id;
      END IF;

      RAISE LOG 'Auto-assigned grading for assignment %, created/updated=%', v_assignment.id, v_auto_assigned_count;
    END IF;

    IF v_assignment.late_grading_reminders_enabled
       AND COALESCE(v_assignment.late_grading_reminder_interval_hours, 0) > 0
       AND (
         v_state.last_reminder_sent_at IS NULL
         OR v_state.last_reminder_sent_at
              + make_interval(hours => v_assignment.late_grading_reminder_interval_hours) <= now()
       ) THEN
      v_reminder_count := public.queue_late_grading_reminders_for_assignment(v_assignment.id);
      UPDATE public.assignment_grading_automation_state
      SET last_reminder_sent_at = now(),
          last_reminder_recipient_count = v_reminder_count,
          updated_at = now()
      WHERE assignment_id = v_assignment.id;

      RAISE LOG 'Queued late grading reminders for assignment %, recipients=%', v_assignment.id, v_reminder_count;
    END IF;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.auto_assign_grading_reviews_for_assignment(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_assign_grading_reviews_for_assignment(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.queue_late_grading_reminders_for_assignment(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.queue_late_grading_reminders_for_assignment(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.run_assignment_grading_automation() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.run_assignment_grading_automation() TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    BEGIN
      IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'run-assignment-grading-automation-every-5-minutes') THEN
        PERFORM cron.unschedule('run-assignment-grading-automation-every-5-minutes');
      END IF;

      PERFORM cron.schedule(
        'run-assignment-grading-automation-every-5-minutes',
        '*/5 * * * *',
        $cron$SELECT public.run_assignment_grading_automation();$cron$
      );
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Unable to schedule grading automation cron job: %', SQLERRM;
    END;
  ELSE
    RAISE NOTICE 'pg_cron extension not available - grading automation schedule not created';
  END IF;
END $$;
