-- Partial indexes backing the metrics_workflow_* RPCs
-- (20260529190000_workflow_metrics_rpcs.sql).
--
-- All three of those RPCs filter public.workflow_runs on completed_at or
-- in_progress_at against NOW() - INTERVAL, and neither column is indexed today,
-- so each one seq-scans the whole table on every refresh. That is the same
-- pathology as the metrics edge function before 76ca0bb8 (77.7% of all database
-- execution time), just at 1/32 the call rate — and the dedicated metrics leader
-- shipping in chart 0.3.18 is what starts calling them for real.
--
-- Partial (WHERE ... IS NOT NULL) because a workflow_runs row spends its whole
-- queued/running life with these columns NULL, and every query filters on a
-- non-NULL value. The partial index is smaller and skips the rows that can never
-- match.
--
-- ---------------------------------------------------------------------------
-- WHY NOT CREATE INDEX CONCURRENTLY
-- ---------------------------------------------------------------------------
-- charts/pawtograder/images/migrations/migrate.sh applies every migration under
-- `psql --single-transaction`. CREATE INDEX CONCURRENTLY cannot run inside a
-- transaction block: it errors, aborts the migration Job, and fails
-- `helm upgrade --wait-for-jobs` — taking the whole deploy down rather than just
-- this statement. So this is a PLAIN CREATE INDEX, which takes an ACCESS
-- EXCLUSIVE lock on public.workflow_runs (a hot autograder path) for the
-- duration of the build. Deploy accordingly: off-peak, not near a deadline.
--
-- IF NOT EXISTS is load-bearing, not decoration. If the build time is long
-- enough to matter, the operator should create these BY HAND with CREATE INDEX
-- CONCURRENTLY before deploying; this migration then finds them already present,
-- becomes a no-op, and still records itself in the migration ledger so the
-- schema does not read as drifted.

CREATE INDEX IF NOT EXISTS idx_workflow_runs_completed_at   ON public.workflow_runs (completed_at DESC)   WHERE completed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_workflow_runs_in_progress_at ON public.workflow_runs (in_progress_at DESC) WHERE in_progress_at IS NOT NULL;
