-- Class-level grading automation profiles + per-assignment defaults/reminders
-- Implements:
-- 1) "Auto assign at deadline" defaults via reusable class profiles
--    (staff rotation / lab leaders / group mentors / optional subset of graders)
-- 2) Late grading reminders at deadline + recurring interval
-- 3) Instructor-configurable CC + reply-to for reminder emails

-- Postgres does not allow subqueries directly in CHECK constraints, but it does
-- allow CHECKs to call functions whose bodies contain subqueries. Wrap the
-- "array of strings" predicate so both the profile and assignment tables can
-- reuse it.
CREATE OR REPLACE FUNCTION public.jsonb_is_string_array(p jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    jsonb_typeof(p) = 'array'
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(p) AS elt
      WHERE jsonb_typeof(elt) IS DISTINCT FROM 'string'
    );
$$;

CREATE TABLE IF NOT EXISTS public.grading_assignment_default_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  auto_assign_at_deadline boolean NOT NULL DEFAULT false,
  auto_assign_assignee_pool text NOT NULL DEFAULT 'graders',
  auto_assign_review_due_hours integer NOT NULL DEFAULT 72,
  auto_assign_grader_subset_private_profile_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  late_grading_reminders_enabled boolean NOT NULL DEFAULT false,
  late_grading_reminder_interval_hours integer,
  late_grading_reply_to text,
  late_grading_cc_emails jsonb NOT NULL DEFAULT jsonb_build_object('emails', jsonb_build_array()),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT grading_assignment_default_profiles_assignee_pool_check CHECK (
    auto_assign_assignee_pool IN (
      'graders',
      'instructors',
      'instructors_and_graders',
      'lab_leaders',
      'group_mentors'
    )
  ),
  CONSTRAINT grading_assignment_default_profiles_grader_subset_ids_check CHECK (
    public.jsonb_is_string_array(auto_assign_grader_subset_private_profile_ids)
  ),
  CONSTRAINT grading_assignment_default_profiles_due_hours_check CHECK (auto_assign_review_due_hours >= 0),
  CONSTRAINT grading_assignment_default_profiles_reminder_interval_check CHECK (
    (NOT late_grading_reminders_enabled)
    OR (late_grading_reminder_interval_hours IS NOT NULL AND late_grading_reminder_interval_hours > 0)
  ),
  CONSTRAINT grading_assignment_default_profiles_cc_emails_check CHECK (
    jsonb_typeof(late_grading_cc_emails) = 'object'
    AND late_grading_cc_emails ? 'emails'
    AND jsonb_typeof(late_grading_cc_emails->'emails') = 'array'
  ),
  CONSTRAINT grading_assignment_default_profiles_class_name_unique UNIQUE (class_id, name),
  CONSTRAINT grading_assignment_default_profiles_id_class_unique UNIQUE (id, class_id)
);

ALTER TABLE public.grading_assignment_default_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Class staff can view grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Class staff can view grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (authorizeforclassinstructor(class_id) OR authorizeforclassgrader(class_id));

DROP POLICY IF EXISTS "Instructors can insert grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can insert grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (authorizeforclassinstructor(class_id));

DROP POLICY IF EXISTS "Instructors can update grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can update grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (authorizeforclassinstructor(class_id))
WITH CHECK (authorizeforclassinstructor(class_id));

DROP POLICY IF EXISTS "Instructors can delete grading default profiles" ON public.grading_assignment_default_profiles;
CREATE POLICY "Instructors can delete grading default profiles"
ON public.grading_assignment_default_profiles
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (authorizeforclassinstructor(class_id));

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'set_updated_at'
  ) THEN
    DROP TRIGGER IF EXISTS set_updated_at_on_grading_assignment_default_profiles ON public.grading_assignment_default_profiles;
    CREATE TRIGGER set_updated_at_on_grading_assignment_default_profiles
    BEFORE UPDATE ON public.grading_assignment_default_profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

ALTER TABLE public.assignments
  ADD COLUMN IF NOT EXISTS grading_default_profile_id bigint,
  ADD COLUMN IF NOT EXISTS auto_assign_at_deadline boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_assign_assignee_pool text NOT NULL DEFAULT 'graders',
  ADD COLUMN IF NOT EXISTS auto_assign_review_due_hours integer NOT NULL DEFAULT 72,
  ADD COLUMN IF NOT EXISTS auto_assign_grader_subset_private_profile_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS late_grading_reminders_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS late_grading_reminder_interval_hours integer,
  ADD COLUMN IF NOT EXISTS late_grading_reply_to text,
  ADD COLUMN IF NOT EXISTS late_grading_cc_emails jsonb NOT NULL DEFAULT jsonb_build_object('emails', jsonb_build_array());

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'assignments_grading_default_profile_id_fkey'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_grading_default_profile_id_fkey
      FOREIGN KEY (grading_default_profile_id, class_id)
      REFERENCES public.grading_assignment_default_profiles(id, class_id)
      ON DELETE SET NULL (grading_default_profile_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_auto_assign_assignee_pool_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_auto_assign_assignee_pool_check
      CHECK (
        auto_assign_assignee_pool IN (
          'graders',
          'instructors',
          'instructors_and_graders',
          'lab_leaders',
          'group_mentors'
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_auto_assign_grader_subset_ids_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_auto_assign_grader_subset_ids_check CHECK (
        public.jsonb_is_string_array(auto_assign_grader_subset_private_profile_ids)
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_auto_assign_review_due_hours_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_auto_assign_review_due_hours_check
      CHECK (auto_assign_review_due_hours >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_late_grading_reminder_interval_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_late_grading_reminder_interval_check
      CHECK (
        (NOT late_grading_reminders_enabled)
        OR (late_grading_reminder_interval_hours IS NOT NULL AND late_grading_reminder_interval_hours > 0)
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'assignments_late_grading_cc_emails_check'
  ) THEN
    ALTER TABLE public.assignments
      ADD CONSTRAINT assignments_late_grading_cc_emails_check
      CHECK (
        jsonb_typeof(late_grading_cc_emails) = 'object'
        AND late_grading_cc_emails ? 'emails'
        AND jsonb_typeof(late_grading_cc_emails->'emails') = 'array'
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.assignment_grading_automation_state (
  assignment_id bigint PRIMARY KEY REFERENCES public.assignments(id) ON DELETE CASCADE,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  auto_assigned_at timestamptz,
  last_reminder_sent_at timestamptz,
  last_reminder_recipient_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.assignment_grading_automation_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages assignment grading automation state" ON public.assignment_grading_automation_state;
CREATE POLICY "Service role manages assignment grading automation state"
ON public.assignment_grading_automation_state
AS PERMISSIVE
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_assignment_grading_automation_state_class_id
  ON public.assignment_grading_automation_state (class_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'set_updated_at'
  ) THEN
    DROP TRIGGER IF EXISTS set_updated_at_on_assignment_grading_automation_state ON public.assignment_grading_automation_state;
    CREATE TRIGGER set_updated_at_on_assignment_grading_automation_state
    BEFORE UPDATE ON public.assignment_grading_automation_state
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.auto_assign_grading_reviews_for_assignment(
  p_assignment_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment public.assignments%ROWTYPE;
  v_staff_ids uuid[];
  v_staff_count integer := 0;
  v_idx integer := 1;
  v_assignee uuid;
  v_actor_user_id uuid;
  v_review_due_date timestamptz;
  v_submission record;
  v_draft_assignments jsonb := '[]'::jsonb;
  v_result jsonb;
  v_member_profiles uuid[];
  v_student_profiles uuid[];
  v_lab_section_id bigint;
  v_leader_id uuid;
  v_mentor_id uuid;
BEGIN
  SELECT *
  INTO v_assignment
  FROM public.assignments
  WHERE id = p_assignment_id
    AND archived_at IS NULL;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  IF NOT v_assignment.auto_assign_at_deadline THEN
    RETURN 0;
  END IF;

  IF v_assignment.grading_rubric_id IS NULL THEN
    RAISE WARNING 'auto_assign skipped for assignment %: missing grading_rubric_id', v_assignment.id;
    RETURN -1;
  END IF;

  -- bulk_assign_reviews requires an instructor auth context.
  SELECT ur.user_id
  INTO v_actor_user_id
  FROM public.user_roles ur
  WHERE ur.class_id = v_assignment.class_id
    AND ur.role = 'instructor'
    AND ur.disabled = false
  ORDER BY ur.created_at
  LIMIT 1;

  IF v_actor_user_id IS NULL THEN
    RAISE WARNING 'auto_assign skipped for assignment %: no active instructor', v_assignment.id;
    RETURN -1;
  END IF;

  PERFORM set_config('request.jwt.claim.sub', v_actor_user_id::text, true);

  v_review_due_date :=
    v_assignment.due_date + make_interval(hours => GREATEST(v_assignment.auto_assign_review_due_hours, 0));

  IF v_assignment.auto_assign_assignee_pool IN ('graders', 'instructors', 'instructors_and_graders') THEN
    SELECT array_agg(ur.private_profile_id ORDER BY ur.private_profile_id)
    INTO v_staff_ids
    FROM public.user_roles ur
    WHERE ur.class_id = v_assignment.class_id
      AND ur.disabled = false
      AND ur.private_profile_id IS NOT NULL
      AND (
        (
          v_assignment.auto_assign_assignee_pool = 'graders'
          AND ur.role = 'grader'
        )
        OR (
          v_assignment.auto_assign_assignee_pool = 'instructors'
          AND ur.role = 'instructor'
        )
        OR (
          v_assignment.auto_assign_assignee_pool = 'instructors_and_graders'
          AND ur.role IN ('grader', 'instructor')
        )
      )
      AND (
        v_assignment.auto_assign_assignee_pool <> 'graders'
        OR COALESCE(jsonb_array_length(v_assignment.auto_assign_grader_subset_private_profile_ids), 0) = 0
        OR EXISTS (
          SELECT 1
          FROM jsonb_array_elements_text(v_assignment.auto_assign_grader_subset_private_profile_ids) AS subset_id(txt)
          WHERE subset_id.txt IS NOT NULL
            AND btrim(subset_id.txt) <> ''
            AND subset_id.txt ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            AND subset_id.txt::uuid = ur.private_profile_id
        )
      );

    v_staff_count := COALESCE(array_length(v_staff_ids, 1), 0);
    IF v_staff_count = 0 THEN
      RAISE WARNING 'auto_assign skipped for assignment %: empty assignee pool (%).', v_assignment.id, v_assignment.auto_assign_assignee_pool;
      RETURN -1;
    END IF;

    FOR v_submission IN
      SELECT s.id AS sid, s.profile_id AS pid, s.assignment_group_id AS agid
      FROM public.submissions s
      WHERE s.assignment_id = v_assignment.id
        AND s.class_id = v_assignment.class_id
        AND s.is_active = true
        AND NOT EXISTS (
          SELECT 1
          FROM public.review_assignments ra
          WHERE ra.assignment_id = v_assignment.id
            AND ra.rubric_id = v_assignment.grading_rubric_id
            AND ra.submission_id = s.id
        )
      ORDER BY s.id
    LOOP
      v_assignee := v_staff_ids[((v_idx - 1) % v_staff_count) + 1];
      v_draft_assignments := v_draft_assignments || jsonb_build_array(
        jsonb_build_object(
          'assignee_profile_id', v_assignee,
          'submission_id', v_submission.sid,
          'rubric_part_id', NULL
        )
      );
      v_idx := v_idx + 1;
    END LOOP;
  ELSIF v_assignment.auto_assign_assignee_pool = 'lab_leaders' THEN
    FOR v_submission IN
      SELECT s.id AS sid, s.profile_id AS pid, s.assignment_group_id AS agid
      FROM public.submissions s
      WHERE s.assignment_id = v_assignment.id
        AND s.class_id = v_assignment.class_id
        AND s.is_active = true
        AND NOT EXISTS (
          SELECT 1
          FROM public.review_assignments ra
          WHERE ra.assignment_id = v_assignment.id
            AND ra.rubric_id = v_assignment.grading_rubric_id
            AND ra.submission_id = s.id
        )
      ORDER BY s.id
    LOOP
      IF v_submission.agid IS NOT NULL THEN
        SELECT COALESCE(array_agg(DISTINCT agm.profile_id), '{}'::uuid[])
        INTO v_member_profiles
        FROM public.assignment_groups_members agm
        WHERE agm.assignment_group_id = v_submission.agid
          AND agm.class_id = v_assignment.class_id
          AND agm.assignment_id = v_assignment.id;
      ELSE
        v_member_profiles := '{}'::uuid[];
      END IF;

      v_student_profiles := ARRAY(
        SELECT DISTINCT mp
        FROM unnest(v_member_profiles || ARRAY[v_submission.pid]) AS t(mp)
        WHERE mp IS NOT NULL
      );

      SELECT ur.lab_section_id INTO v_lab_section_id
      FROM public.user_roles ur
      WHERE ur.class_id = v_assignment.class_id
        AND ur.lab_section_id IS NOT NULL
        AND ur.private_profile_id = ANY(v_student_profiles)
      LIMIT 1;

      IF v_lab_section_id IS NULL THEN
        CONTINUE;
      END IF;

      FOR v_leader_id IN
        SELECT lsl.profile_id
        FROM public.lab_section_leaders lsl
        JOIN public.user_roles ur
          ON ur.private_profile_id = lsl.profile_id
          AND ur.class_id = v_assignment.class_id
          AND ur.disabled = false
          AND ur.role IN ('grader', 'instructor')
        WHERE lsl.class_id = v_assignment.class_id
          AND lsl.lab_section_id = v_lab_section_id
      LOOP
        IF EXISTS (
          SELECT 1
          FROM public.grading_conflicts gc
          WHERE gc.class_id = v_assignment.class_id
            AND gc.grader_profile_id = v_leader_id
            AND gc.student_profile_id = ANY(v_student_profiles)
        ) THEN
          CONTINUE;
        END IF;

        v_draft_assignments := v_draft_assignments || jsonb_build_array(
          jsonb_build_object(
            'assignee_profile_id', v_leader_id,
            'submission_id', v_submission.sid,
            'rubric_part_id', NULL
          )
        );
      END LOOP;
    END LOOP;
  ELSIF v_assignment.auto_assign_assignee_pool = 'group_mentors' THEN
    FOR v_submission IN
      SELECT s.id AS sid, s.profile_id AS pid, s.assignment_group_id AS agid
      FROM public.submissions s
      WHERE s.assignment_id = v_assignment.id
        AND s.class_id = v_assignment.class_id
        AND s.is_active = true
        AND NOT EXISTS (
          SELECT 1
          FROM public.review_assignments ra
          WHERE ra.assignment_id = v_assignment.id
            AND ra.rubric_id = v_assignment.grading_rubric_id
            AND ra.submission_id = s.id
        )
      ORDER BY s.id
    LOOP
      IF v_submission.agid IS NULL THEN
        CONTINUE;
      END IF;

      SELECT ag.mentor_profile_id
      INTO v_mentor_id
      FROM public.assignment_groups ag
      WHERE ag.id = v_submission.agid
        AND ag.class_id = v_assignment.class_id
        AND ag.assignment_id = v_assignment.id;

      IF v_mentor_id IS NULL THEN
        CONTINUE;
      END IF;

      IF NOT EXISTS (
        SELECT 1
        FROM public.user_roles ur
        WHERE ur.private_profile_id = v_mentor_id
          AND ur.class_id = v_assignment.class_id
          AND ur.disabled = false
          AND ur.role IN ('grader', 'instructor')
      ) THEN
        CONTINUE;
      END IF;

      SELECT COALESCE(array_agg(DISTINCT agm.profile_id), '{}'::uuid[])
      INTO v_member_profiles
      FROM public.assignment_groups_members agm
      WHERE agm.assignment_group_id = v_submission.agid
        AND agm.class_id = v_assignment.class_id
        AND agm.assignment_id = v_assignment.id;

      v_student_profiles := ARRAY(
        SELECT DISTINCT mp
        FROM unnest(v_member_profiles || ARRAY[v_submission.pid]) AS t(mp)
        WHERE mp IS NOT NULL
      );

      IF EXISTS (
        SELECT 1
        FROM public.grading_conflicts gc
        WHERE gc.class_id = v_assignment.class_id
          AND gc.grader_profile_id = v_mentor_id
          AND gc.student_profile_id = ANY(v_student_profiles)
      ) THEN
        CONTINUE;
      END IF;

      v_draft_assignments := v_draft_assignments || jsonb_build_array(
        jsonb_build_object(
          'assignee_profile_id', v_mentor_id,
          'submission_id', v_submission.sid,
          'rubric_part_id', NULL
        )
      );
    END LOOP;
  END IF;

  IF jsonb_array_length(v_draft_assignments) = 0 THEN
    RETURN 0;
  END IF;

  SELECT public.bulk_assign_reviews(
    v_assignment.class_id,
    v_assignment.id,
    v_assignment.grading_rubric_id,
    v_draft_assignments,
    v_review_due_date
  )
  INTO v_result;

  IF COALESCE((v_result->>'success')::boolean, false) IS DISTINCT FROM true THEN
    RAISE WARNING 'bulk_assign_reviews failed for assignment %: %', v_assignment.id, v_result;
    RETURN -1;
  END IF;

  RETURN COALESCE((v_result->>'assignments_created')::integer, 0)
    + COALESCE((v_result->>'assignments_updated')::integer, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.queue_late_grading_reminders_for_assignment(
  p_assignment_id bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment public.assignments%ROWTYPE;
  v_batch_id bigint;
  v_subject text;
  v_email_count integer := 0;
BEGIN
  SELECT *
  INTO v_assignment
  FROM public.assignments
  WHERE id = p_assignment_id
    AND archived_at IS NULL;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  IF NOT v_assignment.late_grading_reminders_enabled THEN
    RETURN 0;
  END IF;

  IF v_assignment.late_grading_reminder_interval_hours IS NULL
     OR v_assignment.late_grading_reminder_interval_hours <= 0 THEN
    RETURN 0;
  END IF;

  v_subject := format('Late grading reminder: %s', v_assignment.title);

  INSERT INTO public.email_batches (subject, body, class_id, cc_emails, reply_to)
  VALUES (
    v_subject,
    '',
    v_assignment.class_id,
    v_assignment.late_grading_cc_emails,
    v_assignment.late_grading_reply_to
  )
  RETURNING id INTO v_batch_id;

  WITH reminder_recipients AS (
    SELECT
      ur.user_id,
      COUNT(*)::integer AS incomplete_count
    FROM public.review_assignments ra
    JOIN public.user_roles ur
      ON ur.private_profile_id = ra.assignee_profile_id
     AND ur.class_id = ra.class_id
    WHERE ra.assignment_id = v_assignment.id
      AND ra.completed_at IS NULL
      AND COALESCE(ra.due_date, v_assignment.due_date) <= now()
      AND (v_assignment.grading_rubric_id IS NULL OR ra.rubric_id = v_assignment.grading_rubric_id)
      AND ur.disabled = false
      AND ur.role IN ('grader', 'instructor')
    GROUP BY ur.user_id
  ),
  inserted AS (
    INSERT INTO public.emails (
      user_id,
      batch_id,
      class_id,
      subject,
      body,
      cc_emails,
      reply_to
    )
    SELECT
      rr.user_id,
      v_batch_id,
      v_assignment.class_id,
      v_subject,
      format(
        'You currently have %s incomplete grading assignment%s for "%s". Please visit the assignment reviews page to finish grading.',
        rr.incomplete_count,
        CASE WHEN rr.incomplete_count = 1 THEN '' ELSE 's' END,
        v_assignment.title
      ),
      v_assignment.late_grading_cc_emails,
      v_assignment.late_grading_reply_to
    FROM reminder_recipients rr
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_email_count FROM inserted;

  IF v_email_count = 0 THEN
    DELETE FROM public.email_batches WHERE id = v_batch_id;
  END IF;

  RETURN v_email_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.run_assignment_grading_automation()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_assignment record;
  v_state record;
  v_auto_assigned_count integer;
  v_reminder_count integer;
  -- Bound the candidate window so cron cost stays proportional to recent work,
  -- not to the lifetime size of the assignments table. Auto-assign is a one-
  -- shot action that only makes sense near the deadline; reminders nag for a
  -- bounded period after deadline. If a deadline-bound action wasn't taken
  -- within these windows it will not retroactively fire.
  c_auto_assign_window_days constant integer := 7;
  c_reminder_window_days constant integer := 30;
BEGIN
  FOR v_assignment IN
    SELECT
      a.id,
      a.class_id,
      a.auto_assign_at_deadline,
      a.late_grading_reminders_enabled,
      a.late_grading_reminder_interval_hours,
      a.due_date,
      s.auto_assigned_at,
      s.last_reminder_sent_at
    FROM public.assignments a
    LEFT JOIN public.assignment_grading_automation_state s ON s.assignment_id = a.id
    WHERE a.archived_at IS NULL
      AND a.due_date <= now()
      AND a.due_date >= now() - make_interval(days => c_reminder_window_days)
      AND (
        -- Auto-assign: only consider rows that have not yet been auto-assigned
        -- and whose deadline is still within the auto-assign window.
        (
          a.auto_assign_at_deadline
          AND s.auto_assigned_at IS NULL
          AND a.due_date >= now() - make_interval(days => c_auto_assign_window_days)
        )
        OR
        -- Reminders: only consider rows whose interval has actually elapsed.
        (
          a.late_grading_reminders_enabled
          AND COALESCE(a.late_grading_reminder_interval_hours, 0) > 0
          AND (
            s.last_reminder_sent_at IS NULL
            OR s.last_reminder_sent_at
                 + make_interval(hours => a.late_grading_reminder_interval_hours) <= now()
          )
        )
      )
  LOOP
    INSERT INTO public.assignment_grading_automation_state (assignment_id, class_id)
    VALUES (v_assignment.id, v_assignment.class_id)
    ON CONFLICT (assignment_id) DO NOTHING;

    SELECT s.auto_assigned_at, s.last_reminder_sent_at
    INTO v_state
    FROM public.assignment_grading_automation_state s
    WHERE s.assignment_id = v_assignment.id
    FOR UPDATE;

    IF v_assignment.auto_assign_at_deadline AND v_state.auto_assigned_at IS NULL THEN
      v_auto_assigned_count := public.auto_assign_grading_reviews_for_assignment(v_assignment.id);
      IF v_auto_assigned_count >= 0 THEN
        UPDATE public.assignment_grading_automation_state
        SET auto_assigned_at = now(),
            updated_at = now()
        WHERE assignment_id = v_assignment.id;
        IF v_auto_assigned_count > 0 THEN
          RAISE LOG 'Auto-assigned grading for assignment %: created/updated=%', v_assignment.id, v_auto_assigned_count;
        ELSE
          RAISE LOG 'Auto-assign grading for assignment %: marked complete (no new review assignments required)', v_assignment.id;
        END IF;
      ELSE
        RAISE LOG 'Auto-assign grading for assignment %: deferred or failed (code %)', v_assignment.id, v_auto_assigned_count;
      END IF;
    END IF;

    IF v_assignment.late_grading_reminders_enabled
       AND COALESCE(v_assignment.late_grading_reminder_interval_hours, 0) > 0
       AND (
         v_state.last_reminder_sent_at IS NULL
         OR v_state.last_reminder_sent_at
              + make_interval(hours => v_assignment.late_grading_reminder_interval_hours) <= now()
       ) THEN
      v_reminder_count := public.queue_late_grading_reminders_for_assignment(v_assignment.id);
      UPDATE public.assignment_grading_automation_state
      SET last_reminder_sent_at = now(),
          last_reminder_recipient_count = v_reminder_count,
          updated_at = now()
      WHERE assignment_id = v_assignment.id;

      RAISE LOG 'Queued late grading reminders for assignment %, recipients=%', v_assignment.id, v_reminder_count;
    END IF;
  END LOOP;
END;
$$;

-- Submission-time auto-assignment for late submissions.
--
-- The cron above batch-assigns at the deadline. Students with due-date
-- extensions submit after that batch has already run, so we also fire on
-- submission insert: when the assignment is past its deadline AND
-- auto_assign_at_deadline is enabled, create a review_assignment for the new
-- submission right away.
--
-- Picks the pool member with the FEWEST existing review_assignments for this
-- assignment so trigger-time picks stay balanced against the cron's prior
-- batch (we can't see in-flight cron drafts, only the DB state, so this is
-- a best-effort load balance).
CREATE OR REPLACE FUNCTION public.auto_assign_grading_review_for_submission(p_submission_id bigint)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_submission record;
  v_assignment public.assignments%ROWTYPE;
  v_actor_user_id uuid;
  v_review_due_date timestamptz;
  v_assignee uuid;
  v_draft_assignments jsonb := '[]'::jsonb;
  v_result jsonb;
  v_member_profiles uuid[];
  v_student_profiles uuid[];
  v_lab_section_id bigint;
  v_leader_id uuid;
  v_mentor_id uuid;
BEGIN
  SELECT s.id, s.profile_id, s.assignment_group_id, s.assignment_id, s.class_id, s.is_active
  INTO v_submission
  FROM public.submissions s
  WHERE s.id = p_submission_id;

  IF NOT FOUND OR NOT v_submission.is_active THEN
    RETURN 0;
  END IF;

  SELECT *
  INTO v_assignment
  FROM public.assignments
  WHERE id = v_submission.assignment_id
    AND archived_at IS NULL;

  IF NOT FOUND
     OR NOT v_assignment.auto_assign_at_deadline
     OR v_assignment.grading_rubric_id IS NULL
     OR v_assignment.due_date > now() THEN
    -- Pre-deadline submissions and non-auto-assign assignments are left for
    -- the cron's deadline batch.
    RETURN 0;
  END IF;

  -- Skip if this student/group already has a review_assignment for this
  -- assignment+rubric (on any submission). Catches:
  --   (a) the row was just created by the cron's batch in the same window;
  --   (b) re-submissions where existing repoint triggers move the prior RA
  --       to the new active submission.
  IF EXISTS (
    SELECT 1
    FROM public.review_assignments ra
    JOIN public.submissions s ON s.id = ra.submission_id
    WHERE ra.assignment_id = v_assignment.id
      AND ra.rubric_id = v_assignment.grading_rubric_id
      AND (
        (v_submission.assignment_group_id IS NOT NULL
          AND s.assignment_group_id = v_submission.assignment_group_id)
        OR (v_submission.assignment_group_id IS NULL
          AND s.assignment_group_id IS NULL
          AND s.profile_id = v_submission.profile_id)
      )
  ) THEN
    RETURN 0;
  END IF;

  SELECT ur.user_id
  INTO v_actor_user_id
  FROM public.user_roles ur
  WHERE ur.class_id = v_assignment.class_id
    AND ur.role = 'instructor'
    AND ur.disabled = false
  ORDER BY ur.created_at
  LIMIT 1;

  IF v_actor_user_id IS NULL THEN
    RAISE WARNING 'auto_assign_grading_review_for_submission skipped for submission %: no active instructor', v_submission.id;
    RETURN 0;
  END IF;

  PERFORM set_config('request.jwt.claim.sub', v_actor_user_id::text, true);

  v_review_due_date :=
    v_assignment.due_date + make_interval(hours => GREATEST(v_assignment.auto_assign_review_due_hours, 0));

  IF v_submission.assignment_group_id IS NOT NULL THEN
    SELECT COALESCE(array_agg(DISTINCT agm.profile_id), '{}'::uuid[])
    INTO v_member_profiles
    FROM public.assignment_groups_members agm
    WHERE agm.assignment_group_id = v_submission.assignment_group_id
      AND agm.class_id = v_assignment.class_id
      AND agm.assignment_id = v_assignment.id;
  ELSE
    v_member_profiles := '{}'::uuid[];
  END IF;

  v_student_profiles := ARRAY(
    SELECT DISTINCT mp
    FROM unnest(v_member_profiles || ARRAY[v_submission.profile_id]) AS t(mp)
    WHERE mp IS NOT NULL
  );

  IF v_assignment.auto_assign_assignee_pool IN ('graders', 'instructors', 'instructors_and_graders') THEN
    SELECT picked.private_profile_id
    INTO v_assignee
    FROM (
      SELECT ur.private_profile_id,
             COALESCE(ra_count.c, 0)::integer AS c
      FROM public.user_roles ur
      LEFT JOIN (
        SELECT assignee_profile_id, COUNT(*) AS c
        FROM public.review_assignments
        WHERE assignment_id = v_assignment.id
          AND rubric_id = v_assignment.grading_rubric_id
        GROUP BY assignee_profile_id
      ) ra_count ON ra_count.assignee_profile_id = ur.private_profile_id
      WHERE ur.class_id = v_assignment.class_id
        AND ur.disabled = false
        AND ur.private_profile_id IS NOT NULL
        AND (
          (v_assignment.auto_assign_assignee_pool = 'graders' AND ur.role = 'grader')
          OR (v_assignment.auto_assign_assignee_pool = 'instructors' AND ur.role = 'instructor')
          OR (v_assignment.auto_assign_assignee_pool = 'instructors_and_graders' AND ur.role IN ('grader', 'instructor'))
        )
        AND (
          v_assignment.auto_assign_assignee_pool <> 'graders'
          OR COALESCE(jsonb_array_length(v_assignment.auto_assign_grader_subset_private_profile_ids), 0) = 0
          OR EXISTS (
            SELECT 1
            FROM jsonb_array_elements_text(v_assignment.auto_assign_grader_subset_private_profile_ids) AS subset_id(txt)
            WHERE subset_id.txt IS NOT NULL
              AND btrim(subset_id.txt) <> ''
              AND subset_id.txt ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
              AND subset_id.txt::uuid = ur.private_profile_id
          )
        )
    ) picked
    ORDER BY picked.c ASC, picked.private_profile_id ASC
    LIMIT 1;

    IF v_assignee IS NOT NULL THEN
      v_draft_assignments := jsonb_build_array(jsonb_build_object(
        'assignee_profile_id', v_assignee,
        'submission_id', v_submission.id,
        'rubric_part_id', NULL
      ));
    END IF;
  ELSIF v_assignment.auto_assign_assignee_pool = 'lab_leaders' THEN
    SELECT ur.lab_section_id
    INTO v_lab_section_id
    FROM public.user_roles ur
    WHERE ur.class_id = v_assignment.class_id
      AND ur.lab_section_id IS NOT NULL
      AND ur.private_profile_id = ANY(v_student_profiles)
    LIMIT 1;

    IF v_lab_section_id IS NOT NULL THEN
      FOR v_leader_id IN
        SELECT lsl.profile_id
        FROM public.lab_section_leaders lsl
        JOIN public.user_roles ur
          ON ur.private_profile_id = lsl.profile_id
          AND ur.class_id = v_assignment.class_id
          AND ur.disabled = false
          AND ur.role IN ('grader', 'instructor')
        WHERE lsl.class_id = v_assignment.class_id
          AND lsl.lab_section_id = v_lab_section_id
      LOOP
        IF NOT EXISTS (
          SELECT 1
          FROM public.grading_conflicts gc
          WHERE gc.class_id = v_assignment.class_id
            AND gc.grader_profile_id = v_leader_id
            AND gc.student_profile_id = ANY(v_student_profiles)
        ) THEN
          v_draft_assignments := v_draft_assignments || jsonb_build_array(
            jsonb_build_object(
              'assignee_profile_id', v_leader_id,
              'submission_id', v_submission.id,
              'rubric_part_id', NULL
            )
          );
        END IF;
      END LOOP;
    END IF;
  ELSIF v_assignment.auto_assign_assignee_pool = 'group_mentors' THEN
    IF v_submission.assignment_group_id IS NOT NULL THEN
      SELECT ag.mentor_profile_id
      INTO v_mentor_id
      FROM public.assignment_groups ag
      WHERE ag.id = v_submission.assignment_group_id
        AND ag.class_id = v_assignment.class_id
        AND ag.assignment_id = v_assignment.id;

      IF v_mentor_id IS NOT NULL
         AND EXISTS (
           SELECT 1
           FROM public.user_roles ur
           WHERE ur.private_profile_id = v_mentor_id
             AND ur.class_id = v_assignment.class_id
             AND ur.disabled = false
             AND ur.role IN ('grader', 'instructor')
         )
         AND NOT EXISTS (
           SELECT 1
           FROM public.grading_conflicts gc
           WHERE gc.class_id = v_assignment.class_id
             AND gc.grader_profile_id = v_mentor_id
             AND gc.student_profile_id = ANY(v_student_profiles)
         ) THEN
        v_draft_assignments := jsonb_build_array(jsonb_build_object(
          'assignee_profile_id', v_mentor_id,
          'submission_id', v_submission.id,
          'rubric_part_id', NULL
        ));
      END IF;
    END IF;
  END IF;

  IF jsonb_array_length(v_draft_assignments) = 0 THEN
    RETURN 0;
  END IF;

  SELECT public.bulk_assign_reviews(
    v_assignment.class_id,
    v_assignment.id,
    v_assignment.grading_rubric_id,
    v_draft_assignments,
    v_review_due_date
  )
  INTO v_result;

  IF COALESCE((v_result->>'success')::boolean, false) IS DISTINCT FROM true THEN
    RAISE WARNING 'bulk_assign_reviews failed for late submission %: %', v_submission.id, v_result;
    RETURN 0;
  END IF;

  RETURN COALESCE((v_result->>'assignments_created')::integer, 0)
       + COALESCE((v_result->>'assignments_updated')::integer, 0);
END;
$$;

-- Wrap the trigger so a failure in auto-assignment never blocks the underlying
-- submission INSERT. The student must always be able to submit; auto-assign is
-- best-effort and an operator can re-run the cron RPC to recover.
CREATE OR REPLACE FUNCTION public.trigger_auto_assign_review_on_submission()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public, pg_temp
AS $$
BEGIN
  BEGIN
    PERFORM public.auto_assign_grading_review_for_submission(NEW.id);
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'auto_assign_grading_review_for_submission failed for submission %: %', NEW.id, SQLERRM;
  END;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auto_assign_review_on_submission ON public.submissions;
CREATE TRIGGER trg_auto_assign_review_on_submission
  AFTER INSERT ON public.submissions
  FOR EACH ROW
  WHEN (NEW.is_active = true)
  EXECUTE FUNCTION public.trigger_auto_assign_review_on_submission();

REVOKE ALL ON FUNCTION public.auto_assign_grading_reviews_for_assignment(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_assign_grading_reviews_for_assignment(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.auto_assign_grading_review_for_submission(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_assign_grading_review_for_submission(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.queue_late_grading_reminders_for_assignment(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.queue_late_grading_reminders_for_assignment(bigint) TO service_role;

REVOKE ALL ON FUNCTION public.run_assignment_grading_automation() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.run_assignment_grading_automation() TO service_role;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    BEGIN
      IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'run-assignment-grading-automation-every-5-minutes') THEN
        PERFORM cron.unschedule('run-assignment-grading-automation-every-5-minutes');
      END IF;

      PERFORM cron.schedule(
        'run-assignment-grading-automation-every-5-minutes',
        '*/5 * * * *',
        $cron$SELECT public.run_assignment_grading_automation();$cron$
      );
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Unable to schedule grading automation cron job: %', SQLERRM;
    END;
  ELSE
    RAISE NOTICE 'pg_cron extension not available - grading automation schedule not created';
  END IF;
END $$;
