-------------------------------------------------------------------------------
-- LTI grade sync: durable per-student state + on-release automation.
--
-- Today grade push is manual (one assignment at a time, no record of what
-- actually synced). This migration adds:
--   1. lti_grade_sync_state  — durable per-student record (what value we last
--      pushed, status, errors) so we can do incremental pushes, retract stale
--      scores, and show instructors who failed / has no LTI identity.
--   2. lti_grade_sync_queue  — coalesced work list (one row per assignment that
--      needs a (re)sync).
--   3. an on-release trigger on gradebook_column_students that enqueues affected
--      assignments and kicks /api/lti/push-grades {"drain": true} (fire-and-forget,
--      after commit) so released grades flow to the LMS without a manual click.
--   4. an optional pg_cron safety-net that re-kicks the drain only when the queue
--      is non-empty (self-heals a dropped HTTP kick / app-down window).
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- 1. Per-student sync state
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_grade_sync_state" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "class_id" bigint NOT NULL REFERENCES "public"."classes"("id") ON DELETE CASCADE,
    "assignment_id" bigint NOT NULL REFERENCES "public"."assignments"("id") ON DELETE CASCADE,
    "line_item_id" bigint REFERENCES "public"."lti_line_items"("id") ON DELETE SET NULL,
    "student_profile_id" uuid NOT NULL,         -- gradebook_column_students.student_id (private profile)
    "lti_user_sub" text,                        -- resolved AGS userId; NULL => no_identity
    "synced_score" numeric,                     -- last value sent (NULL => cleared / retracted)
    "status" text NOT NULL,                     -- 'synced' | 'retracted' | 'failed' | 'no_identity'
    "error" text,
    "attempts" integer DEFAULT 0 NOT NULL,
    "last_attempt_at" timestamp with time zone,
    "synced_at" timestamp with time zone,
    CONSTRAINT "lti_grade_sync_state_status_chk"
      CHECK (status IN ('synced', 'retracted', 'failed', 'no_identity')),
    CONSTRAINT "lti_grade_sync_state_unique" UNIQUE ("assignment_id", "student_profile_id")
);

ALTER TABLE "public"."lti_grade_sync_state" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_grade_sync_state" TO "service_role";
GRANT SELECT ON TABLE "public"."lti_grade_sync_state" TO "authenticated";

-- Mirror lti_line_items: instructors read their class's rows, service role writes.
CREATE POLICY "Instructors read lti_grade_sync_state" ON "public"."lti_grade_sync_state"
    FOR SELECT USING (public.authorizeforclassinstructor(class_id));
CREATE POLICY "Admins manage lti_grade_sync_state" ON "public"."lti_grade_sync_state"
    FOR ALL USING (authorize_for_admin()) WITH CHECK (authorize_for_admin());
CREATE POLICY "Service role manages lti_grade_sync_state" ON "public"."lti_grade_sync_state"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS "lti_grade_sync_state_class_id_idx"
    ON "public"."lti_grade_sync_state" ("class_id");
CREATE INDEX IF NOT EXISTS "lti_grade_sync_state_assignment_id_idx"
    ON "public"."lti_grade_sync_state" ("assignment_id");

CREATE TRIGGER "lti_grade_sync_state_touch" BEFORE UPDATE ON "public"."lti_grade_sync_state"
    FOR EACH ROW EXECUTE FUNCTION public.lti_touch_updated_at();

-------------------------------------------------------------------------------
-- 2. Coalesced work queue (one row per assignment needing a sync)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."lti_grade_sync_queue" (
    "class_id" bigint NOT NULL REFERENCES "public"."classes"("id") ON DELETE CASCADE,
    "assignment_id" bigint NOT NULL REFERENCES "public"."assignments"("id") ON DELETE CASCADE,
    "enqueued_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("class_id", "assignment_id")
);

ALTER TABLE "public"."lti_grade_sync_queue" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."lti_grade_sync_queue" TO "service_role";
GRANT SELECT ON TABLE "public"."lti_grade_sync_queue" TO "authenticated";

CREATE POLICY "Instructors read lti_grade_sync_queue" ON "public"."lti_grade_sync_queue"
    FOR SELECT USING (public.authorizeforclassinstructor(class_id));
CREATE POLICY "Service role manages lti_grade_sync_queue" ON "public"."lti_grade_sync_queue"
    FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-------------------------------------------------------------------------------
-- 3. Drain kick — fire-and-forget POST to the grade-push endpoint.
-- Mirrors trigger_lti_roster_sync(); no-ops (and never raises) when app_url or
-- pg_net is unavailable, so grading writes are never blocked by sync.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lti_kick_grade_drain()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    v_url text := current_setting('app.settings.app_url', true);
    v_secret text := current_setting('app.settings.lti_cron_secret', true);
BEGIN
    IF v_url IS NULL OR v_url = '' THEN
        RETURN;
    END IF;
    PERFORM net.http_post(
        url := v_url || '/api/lti/push-grades',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-lti-cron-secret', COALESCE(v_secret, '')
        ),
        body := '{"drain": true}'::jsonb
    );
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'LTI grade drain kick failed: %', SQLERRM;
END;
$$;

REVOKE ALL ON FUNCTION public.lti_kick_grade_drain() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lti_kick_grade_drain() TO service_role;
GRANT EXECUTE ON FUNCTION public.lti_kick_grade_drain() TO postgres;

-------------------------------------------------------------------------------
-- 4. On-release enqueue triggers (statement-level, transition tables).
-- A bulk release of N students fires the enqueue once, not per row. We only
-- enqueue assignment-backed columns belonging to a class with grade sync on.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lti_enqueue_grade_sync_insert()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    n integer;
BEGIN
    INSERT INTO public.lti_grade_sync_queue (class_id, assignment_id)
    SELECT DISTINCT nr.class_id, a.id
    FROM new_rows nr
    JOIN public.assignments a
      ON a.gradebook_column_id = nr.gradebook_column_id AND a.class_id = nr.class_id
    WHERE nr.is_private = true
      AND nr.released = true
      AND EXISTS (
        SELECT 1 FROM public.lti_context_links l
        WHERE l.class_id = nr.class_id AND l.grade_sync_enabled
      )
    ON CONFLICT (class_id, assignment_id) DO UPDATE SET enqueued_at = now();
    GET DIAGNOSTICS n = ROW_COUNT;
    IF n > 0 THEN
        PERFORM public.lti_kick_grade_drain();
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.lti_enqueue_grade_sync_update()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
DECLARE
    n integer;
BEGIN
    INSERT INTO public.lti_grade_sync_queue (class_id, assignment_id)
    SELECT DISTINCT nr.class_id, a.id
    FROM new_rows nr
    JOIN old_rows orr ON orr.id = nr.id
    JOIN public.assignments a
      ON a.gradebook_column_id = nr.gradebook_column_id AND a.class_id = nr.class_id
    WHERE nr.is_private = true
      AND EXISTS (
        SELECT 1 FROM public.lti_context_links l
        WHERE l.class_id = nr.class_id AND l.grade_sync_enabled
      )
      AND (
        -- release/unrelease transition (unrelease => retraction)
        orr.released IS DISTINCT FROM nr.released
        -- a released grade's value/excused state changed
        OR (nr.released AND (
              orr.score IS DISTINCT FROM nr.score
           OR orr.score_override IS DISTINCT FROM nr.score_override
           OR orr.is_excused IS DISTINCT FROM nr.is_excused
        ))
      )
    ON CONFLICT (class_id, assignment_id) DO UPDATE SET enqueued_at = now();
    GET DIAGNOSTICS n = ROW_COUNT;
    IF n > 0 THEN
        PERFORM public.lti_kick_grade_drain();
    END IF;
    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.lti_enqueue_grade_sync_insert() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.lti_enqueue_grade_sync_update() FROM PUBLIC;

CREATE TRIGGER "lti_grade_sync_enqueue_insert"
    AFTER INSERT ON "public"."gradebook_column_students"
    REFERENCING NEW TABLE AS new_rows
    FOR EACH STATEMENT EXECUTE FUNCTION public.lti_enqueue_grade_sync_insert();

CREATE TRIGGER "lti_grade_sync_enqueue_update"
    AFTER UPDATE ON "public"."gradebook_column_students"
    REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows
    FOR EACH STATEMENT EXECUTE FUNCTION public.lti_enqueue_grade_sync_update();

-------------------------------------------------------------------------------
-- 5. Optional safety-net: re-kick the drain when (and only when) the queue is
-- non-empty, so a lost HTTP kick or app-down window self-heals. This is a
-- drain-kick, not a periodic full re-sync.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lti_grade_drain_safety_net()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.lti_grade_sync_queue) THEN
        PERFORM public.lti_kick_grade_drain();
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.lti_grade_drain_safety_net() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lti_grade_drain_safety_net() TO service_role;
GRANT EXECUTE ON FUNCTION public.lti_grade_drain_safety_net() TO postgres;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        -- Every 15 minutes, offset from roster (:45) and SIS (:15) jobs.
        PERFORM cron.schedule(
            'lti-grade-drain-safety-net',
            '*/15 * * * *',
            'SELECT public.lti_grade_drain_safety_net();'
        );
        RAISE NOTICE 'LTI grade drain safety-net cron scheduled every 15 minutes';
    ELSE
        RAISE NOTICE 'pg_cron not available; skipping LTI grade drain safety-net schedule';
    END IF;
END;
$$;
