-- ============================================================================
-- GitHub deployments ingestion + checks-by-head_sha read layer (PR mode P1)
-- ============================================================================
-- Phase 4 of the PR-submission-mode epic needs a read-only data layer for the
-- "Deployments" and "Checks" UI surfaces of a PR submission. Two pieces:
--
--   1. `github_deployments` -- one row per GitHub deployment_status delivery,
--      ingested by the github-repo-webhook edge function. For student repos that
--      are in `repositories` we resolve class_id/repository_id; for fork or
--      shared-project repos that are NOT in `repositories` (PR submissions can
--      target an upstream/class repo and the actual CI/deploy runs on the fork)
--      we still record the row keyed by (repository_name, sha). The UI joins it
--      to a submission by head_sha.
--
--   2. `get_submission_checks` -- given a submission id, return the
--      `workflow_events` (GitHub Actions runs) matching that submission's
--      head_sha, even when the run lives on a fork that is not in `repositories`.
--      This is what the future Checks UI lists for a PR submission.
--
-- RLS model (see the long comment on the policies below): we mirror the INTENT
-- of the existing CI tables. `workflow_run_error` already scopes students to
-- their own submissions via authorize_for_submission(); `repositories` scopes
-- students to repos they own. `github_deployments` combines both: staff read
-- all in the class; a student reads a row only when it is tied to a repository
-- they own OR to one of their own submissions by head_sha. We deliberately do
-- NOT copy `workflow_events`' blanket "any authenticated user can read every
-- row" policy -- that table predates per-submission scoping and is effectively
-- public-to-logged-in-users; a deployments feed (with target_url / environment /
-- payload) is more sensitive, so we scope it like submission-owned data.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Step 1: github_deployments table
-- ----------------------------------------------------------------------------

CREATE TABLE public.github_deployments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  -- Resolved when the repo is one of ours; NULL for fork/shared-project repos
  -- that are not tracked in `repositories` (joined to a submission by head_sha).
  repository_id bigint REFERENCES public.repositories(id) ON DELETE SET NULL,
  repository_name text NOT NULL,
  sha text,
  environment text,
  state text,
  target_url text,
  github_deployment_id bigint,
  github_deployment_status_id bigint,
  creator_login text,
  payload jsonb
);

COMMENT ON TABLE public.github_deployments IS
  'One row per GitHub deployment_status webhook delivery. repository_id is set when the repo is tracked in `repositories`; otherwise the row is keyed by (repository_name, sha) and the UI joins it to a PR submission by head_sha.';

CREATE INDEX idx_github_deployments_class_id
  ON public.github_deployments (class_id);
CREATE INDEX idx_github_deployments_repository_id
  ON public.github_deployments (repository_id);
-- Drives the fork/shared-project join: deployment.(repository_name, sha) ->
-- submission.(repository, head_sha).
CREATE INDEX idx_github_deployments_repo_name_sha
  ON public.github_deployments (repository_name, sha);

-- Dedupe webhook re-delivery: GitHub retries deliveries, so the same
-- (deployment, deployment_status) pair can arrive multiple times. NULLS NOT
-- DISTINCT so two rows that both lack ids (shouldn't happen for real
-- deployment_status payloads, but be safe) are treated as equal rather than
-- silently duplicated. Postgres 15+.
CREATE UNIQUE INDEX github_deployments_delivery_unique
  ON public.github_deployments (github_deployment_id, github_deployment_status_id)
  NULLS NOT DISTINCT;

ALTER TABLE public.github_deployments ENABLE ROW LEVEL SECURITY;

-- Service role (the webhook ingester) does everything.
CREATE POLICY "github_deployments_service_role_all"
ON public.github_deployments
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Read policy. Three independent paths, matching how the other CI / repo tables
-- authorize SELECT:
--   * staff (instructor/grader) read every row in their class -- same as
--     `workflow_run_error_select`'s authorizeforclassgrader(class_id) branch and
--     the staff branch of the `repositories` SELECT policy.
--   * a student reads a row tied to a repository they own -- the exact
--     profile/group ownership test the `repositories` SELECT policy uses
--     (so a deployment of a repo they can already see is visible too).
--   * a student reads a row tied to one of THEIR submissions by head_sha --
--     this is the fork/shared-project case, where repository_id is NULL because
--     the deploy ran on a repo not in `repositories`. We match the deployment's
--     (repository_name, sha) to a submission's (repository, head_sha) the
--     student owns (directly or via their assignment group). We scope by
--     submission ownership explicitly rather than calling
--     authorize_for_submission() because that helper is row-insensitive (it
--     returns true if the caller owns ANY submission), which would not scope
--     per-row here.
CREATE POLICY "github_deployments_read"
ON public.github_deployments
FOR SELECT
USING (
  -- Path 1: staff in the class
  public.authorizeforclassgrader(class_id)
  OR
  -- Path 2: a repository the student owns (profile or group)
  (
    repository_id IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.repositories r
      WHERE r.id = github_deployments.repository_id
        AND (
          r.profile_id IN (
            SELECT up.private_profile_id FROM public.user_privileges up
              WHERE up.user_id = auth.uid() AND up.private_profile_id IS NOT NULL
            UNION
            SELECT up.public_profile_id FROM public.user_privileges up
              WHERE up.user_id = auth.uid() AND up.public_profile_id IS NOT NULL
          )
          OR (
            r.assignment_group_id IS NOT NULL
            AND r.assignment_group_id IN (
              SELECT agm.assignment_group_id
              FROM public.assignment_groups_members agm
              JOIN public.user_privileges up ON up.private_profile_id = agm.profile_id
              WHERE up.user_id = auth.uid()
            )
          )
        )
    )
  )
  OR
  -- Path 3: one of the student's own submissions matches by (repo, head sha)
  (
    sha IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.submissions s
      WHERE s.repository = github_deployments.repository_name
        -- match the deployment sha against the submission head (PR mode) or its
        -- plain sha (push mode); coalesce mirrors get_submission_checks below.
        AND coalesce(s.head_sha, s.sha) = github_deployments.sha
        AND (
          s.profile_id IN (
            SELECT up.private_profile_id FROM public.user_privileges up
              WHERE up.user_id = auth.uid() AND up.private_profile_id IS NOT NULL
            UNION
            SELECT up.public_profile_id FROM public.user_privileges up
              WHERE up.user_id = auth.uid() AND up.public_profile_id IS NOT NULL
          )
          OR (
            s.assignment_group_id IS NOT NULL
            AND s.assignment_group_id IN (
              SELECT agm.assignment_group_id
              FROM public.assignment_groups_members agm
              JOIN public.user_privileges up ON up.private_profile_id = agm.profile_id
              WHERE up.user_id = auth.uid()
            )
          )
        )
    )
  )
);

-- Privilege grants mirror `submission_pr_links`: Supabase blanket-grants all
-- privileges to `authenticated` on new public tables, so strip them and re-grant
-- SELECT only (clients never write deployments; the webhook writes as
-- service_role). RLS is the primary gate; this is defense in depth.
REVOKE ALL ON TABLE public.github_deployments FROM anon;
REVOKE ALL ON TABLE public.github_deployments FROM authenticated;
GRANT SELECT ON TABLE public.github_deployments TO authenticated;
GRANT ALL ON TABLE public.github_deployments TO service_role;

-- ----------------------------------------------------------------------------
-- Step 2: upsert_github_deployment -- idempotent ingestion entry point
-- ----------------------------------------------------------------------------
-- Called as service_role by the github-repo-webhook edge function for each
-- deployment_status delivery. Idempotent on (github_deployment_id,
-- github_deployment_status_id) re-delivery: a repeat delivery refreshes the
-- mutable fields (state/target_url/environment/payload) instead of inserting a
-- duplicate. Doing this in the DB (rather than two round-trips from the edge
-- function) keeps the upsert atomic under concurrent re-delivery.
CREATE OR REPLACE FUNCTION public.upsert_github_deployment(
  p_class_id bigint,
  p_repository_name text,
  p_repository_id bigint DEFAULT NULL,
  p_sha text DEFAULT NULL,
  p_environment text DEFAULT NULL,
  p_state text DEFAULT NULL,
  p_target_url text DEFAULT NULL,
  p_github_deployment_id bigint DEFAULT NULL,
  p_github_deployment_status_id bigint DEFAULT NULL,
  p_creator_login text DEFAULT NULL,
  p_payload jsonb DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
declare
  v_id bigint;
begin
  if p_class_id is null or p_repository_name is null then
    raise exception 'p_class_id and p_repository_name are required';
  end if;

  insert into public.github_deployments(
    class_id, repository_id, repository_name, sha, environment, state,
    target_url, github_deployment_id, github_deployment_status_id,
    creator_login, payload
  ) values (
    p_class_id, p_repository_id, p_repository_name, p_sha, p_environment, p_state,
    p_target_url, p_github_deployment_id, p_github_deployment_status_id,
    p_creator_login, p_payload
  )
  on conflict (github_deployment_id, github_deployment_status_id)
  do update set
    -- repository may have become resolvable since a prior delivery; keep the
    -- non-null value. Mutable status fields always take the latest delivery.
    repository_id   = coalesce(excluded.repository_id, public.github_deployments.repository_id),
    state           = excluded.state,
    target_url      = excluded.target_url,
    environment     = coalesce(excluded.environment, public.github_deployments.environment),
    creator_login   = coalesce(excluded.creator_login, public.github_deployments.creator_login),
    payload         = excluded.payload
  returning id into v_id;

  return v_id;
end;
$$;

-- Only the webhook (service_role) ingests deployments.
REVOKE ALL ON FUNCTION public.upsert_github_deployment(
  bigint, text, bigint, text, text, text, text, bigint, bigint, text, jsonb
) FROM public;
REVOKE ALL ON FUNCTION public.upsert_github_deployment(
  bigint, text, bigint, text, text, text, text, bigint, bigint, text, jsonb
) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_github_deployment(
  bigint, text, bigint, text, text, text, text, bigint, bigint, text, jsonb
) TO service_role;

-- ----------------------------------------------------------------------------
-- Step 3: get_submission_checks -- CI runs for a submission, by head_sha
-- ----------------------------------------------------------------------------
-- Returns the workflow_events (GitHub Actions runs / checks) whose head_sha
-- matches the given submission's head_sha (falling back to submissions.sha,
-- which mirrors head for non-PR submissions). This resolves CI even when the
-- run lives on a fork repo that is NOT in `repositories` (repository_id NULL on
-- the event) -- the match is purely by sha, which is what the Checks UI needs
-- for a PR submission.
--
-- SECURITY: SECURITY INVOKER (pinned explicitly) so the caller's RLS applies to
-- BOTH joined tables. The authorization gate is the caller's row-level RLS on
-- `public.submissions`: the join only yields the `s` row when the caller can
-- already see that submission (staff-in-class or owner, per the submissions
-- SELECT policy), so a caller cannot use a submission id they cannot read to
-- learn its sha or its CI. `workflow_events` rows are themselves readable by any
-- authenticated user today, so this exposes nothing beyond the direct two-table
-- query the caller could already run by hand. We deliberately do NOT add a
-- separate authorize_for_submission() predicate: that helper is row-insensitive
-- (true if the caller owns ANY submission) and would not tighten anything here
-- given submissions-RLS is already the per-row gate.
CREATE OR REPLACE FUNCTION public.get_submission_checks(p_submission_id bigint)
RETURNS SETOF public.workflow_events
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT we.*
  FROM public.submissions s
  JOIN public.workflow_events we
    ON we.head_sha = coalesce(s.head_sha, s.sha)
  WHERE s.id = p_submission_id;
$$;

REVOKE ALL ON FUNCTION public.get_submission_checks(bigint) FROM public;
GRANT EXECUTE ON FUNCTION public.get_submission_checks(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_submission_checks(bigint) TO service_role;

COMMENT ON FUNCTION public.get_submission_checks(bigint) IS
  'CI runs (workflow_events) matching a submission''s head_sha, including runs on fork repos not in `repositories`. SECURITY INVOKER; gated on the caller being able to read the submission.';
